"""Source-of-truth Figma CLI operation inventory."""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Final


FigmaAPI_SPEC_URL: Final[str] = "https://raw.githubusercontent.com/figma/rest-api-spec/main/openapi/openapi.yaml"
FigmaDocsBase: Final[str] = "https://developers.figma.com/docs/rest-api/"


@dataclass(frozen=True)
class SafetyClassification:
    mode: str
    requires_yes: bool
    requires_ack_irreversible: bool
    live_verification_note: str


@dataclass(frozen=True)
class OperationSpec:
    area: str
    op_key: str
    title: str
    method: str
    path_template: str
    docs_url: str
    scope_notes: str
    auth_notes: str
    required_path_params: list[str]
    required_query_params: list[str]
    body_json_file_expected: bool
    safety: SafetyClassification
    required_query_exactly_one_of: list[list[str]] = field(default_factory=list)
    optional_query_params: list[str] = field(default_factory=list)
    verification_strategy: str | None = None


AREAS_DOC_URLS: Final[dict[str, str]] = {
    "files": "https://developers.figma.com/docs/rest-api/file-endpoints/",
    "version-history": "https://developers.figma.com/docs/rest-api/version-history-endpoints/",
    "comments": "https://developers.figma.com/docs/rest-api/comments-endpoints/",
    "users": "https://developers.figma.com/docs/rest-api/users-endpoints/",
    "projects": "https://developers.figma.com/docs/rest-api/projects-endpoints/",
    "components": "https://developers.figma.com/docs/rest-api/component-endpoints/",
    "webhooks": "https://developers.figma.com/docs/rest-api/webhooks-endpoints/",
    "activity-logs": "https://developers.figma.com/docs/rest-api/activity-logs-endpoints/",
    "developer-logs": "https://developers.figma.com/docs/rest-api/developer-logs-endpoints/",
    "discovery": "https://developers.figma.com/docs/rest-api/discovery-endpoints/",
    "payments": "https://developers.figma.com/docs/rest-api/payments-endpoints/",
    "variables": "https://developers.figma.com/docs/rest-api/variables-endpoints/",
    "dev-resources": "https://developers.figma.com/docs/rest-api/dev-resources-endpoints/",
    "library-analytics": "https://developers.figma.com/docs/rest-api/library-analytics-endpoints/",
    "oembed": "https://developers.figma.com/docs/rest-api/oembed-endpoints/",
}

_PENDING_VERIFY = "Pending live verification once this operation is wired into the runtime and auth mode is connected"


OPERATION_SPECS: Final[list[OperationSpec]] = [
    OperationSpec(
        area="files",
        op_key="get-file",
        title="Get file JSON",
        method="GET",
        path_template="/v1/files/{file_key}",
        docs_url=AREAS_DOC_URLS["files"],
        scope_notes="Get full file JSON, optional filters for version, ids, depth, geometry, plugin_data, branch_data.",
        auth_notes="PAT/Plan token or OAuth2 with file_content:read + files:read.",
        required_path_params=["file_key"],
        required_query_params=[],
        body_json_file_expected=False,
        optional_query_params=["version", "ids", "depth", "geometry", "plugin_data", "branch_data"],
        safety=SafetyClassification(
            mode="read-only",
            requires_yes=False,
            requires_ack_irreversible=False,
            live_verification_note=_PENDING_VERIFY,
        ),
    ),
    OperationSpec(
        area="files",
        op_key="get-file-nodes",
        title="Get file JSON for specific nodes",
        method="GET",
        path_template="/v1/files/{file_key}/nodes",
        docs_url=AREAS_DOC_URLS["files"],
        scope_notes="Subset mode for rendering one or more nodes from a file.",
        auth_notes="PAT/Plan token or OAuth2 with file_content:read + files:read.",
        required_path_params=["file_key"],
        required_query_params=["ids"],
        body_json_file_expected=False,
        optional_query_params=["version", "depth", "geometry", "plugin_data"],
        safety=SafetyClassification(
            mode="read-only",
            requires_yes=False,
            requires_ack_irreversible=False,
            live_verification_note=_PENDING_VERIFY,
        ),
    ),
    OperationSpec(
        area="files",
        op_key="render-images",
        title="Render images of file nodes",
        method="GET",
        path_template="/v1/images/{file_key}",
        docs_url=AREAS_DOC_URLS["files"],
        scope_notes="Render and return image URLs for one or more node ids.",
        auth_notes="PAT/Plan token or OAuth2 with file_content:read + files:read.",
        required_path_params=["file_key"],
        required_query_params=["ids"],
        body_json_file_expected=False,
        optional_query_params=[
            "version",
            "scale",
            "format",
            "svg_outline_text",
            "svg_include_id",
            "svg_include_node_id",
            "svg_simplify_stroke",
            "contents_only",
            "use_absolute_bounds",
        ],
        safety=SafetyClassification(
            mode="read-only",
            requires_yes=False,
            requires_ack_irreversible=False,
            live_verification_note=_PENDING_VERIFY,
        ),
    ),
    OperationSpec(
        area="files",
        op_key="get-image-fills",
        title="Get image fills",
        method="GET",
        path_template="/v1/files/{file_key}/images",
        docs_url=AREAS_DOC_URLS["files"],
        scope_notes="Get download links for all image fill references in a document.",
        auth_notes="PAT/Plan token or OAuth2 with file_content:read + files:read.",
        required_path_params=["file_key"],
        required_query_params=[],
        body_json_file_expected=False,
        safety=SafetyClassification(
            mode="read-only",
            requires_yes=False,
            requires_ack_irreversible=False,
            live_verification_note=_PENDING_VERIFY,
        ),
    ),
    OperationSpec(
        area="files",
        op_key="get-file-meta",
        title="Get file metadata",
        method="GET",
        path_template="/v1/files/{file_key}/meta",
        docs_url=AREAS_DOC_URLS["files"],
        scope_notes="Get file metadata summary object.",
        auth_notes="PAT/Plan token or OAuth2 with file_metadata:read + files:read.",
        required_path_params=["file_key"],
        required_query_params=[],
        body_json_file_expected=False,
        safety=SafetyClassification(
            mode="read-only",
            requires_yes=False,
            requires_ack_irreversible=False,
            live_verification_note=_PENDING_VERIFY,
        ),
    ),
    OperationSpec(
        area="version-history",
        op_key="get-file-versions",
        title="Get file versions",
        method="GET",
        path_template="/v1/files/{file_key}/versions",
        docs_url=AREAS_DOC_URLS["version-history"],
        scope_notes="List file history versions with optional paging by before/after/size.",
        auth_notes="PAT/Plan token or OAuth2 with file_versions:read + files:read.",
        required_path_params=["file_key"],
        required_query_params=[],
        body_json_file_expected=False,
        optional_query_params=["page_size", "before", "after"],
        safety=SafetyClassification(
            mode="read-only",
            requires_yes=False,
            requires_ack_irreversible=False,
            live_verification_note=_PENDING_VERIFY,
        ),
    ),
    OperationSpec(
        area="comments",
        op_key="get-comments",
        title="Get comments in file",
        method="GET",
        path_template="/v1/files/{file_key}/comments",
        docs_url=AREAS_DOC_URLS["comments"],
        scope_notes="Read comments list for a file, optionally in markdown format.",
        auth_notes="PAT/Plan token or OAuth2 with file_comments:read + files:read.",
        required_path_params=["file_key"],
        required_query_params=[],
        body_json_file_expected=False,
        optional_query_params=["as_md"],
        safety=SafetyClassification(
            mode="read-only",
            requires_yes=False,
            requires_ack_irreversible=False,
            live_verification_note=_PENDING_VERIFY,
        ),
    ),
    OperationSpec(
        area="comments",
        op_key="post-comment",
        title="Add comment",
        method="POST",
        path_template="/v1/files/{file_key}/comments",
        docs_url=AREAS_DOC_URLS["comments"],
        scope_notes="Create a new comment or reply in a file.",
        auth_notes="OAuth2 file_comments:write or PAT with matching write scope.",
        required_path_params=["file_key"],
        required_query_params=[],
        body_json_file_expected=True,
        safety=SafetyClassification(
            mode="write",
            requires_yes=True,
            requires_ack_irreversible=False,
            live_verification_note=_PENDING_VERIFY,
        ),
        verification_strategy="comment-post",
    ),
    OperationSpec(
        area="comments",
        op_key="delete-comment",
        title="Delete comment",
        method="DELETE",
        path_template="/v1/files/{file_key}/comments/{comment_id}",
        docs_url=AREAS_DOC_URLS["comments"],
        scope_notes="Delete one comment. API validates caller ownership in implementation.",
        auth_notes="OAuth2 file_comments:write or PAT with write scope.",
        required_path_params=["file_key", "comment_id"],
        required_query_params=[],
        body_json_file_expected=False,
        safety=SafetyClassification(
            mode="write",
            requires_yes=True,
            requires_ack_irreversible=True,
            live_verification_note="Live check needed; deletion is irreversible.",
        ),
        verification_strategy="comment-delete",
    ),
    OperationSpec(
        area="comments",
        op_key="get-comment-reactions",
        title="Get comment reactions",
        method="GET",
        path_template="/v1/files/{file_key}/comments/{comment_id}/reactions",
        docs_url=AREAS_DOC_URLS["comments"],
        scope_notes="List reactions for a comment; supports pagination cursor.",
        auth_notes="PAT/Plan token or OAuth2 with file_comments:read + files:read.",
        required_path_params=["file_key", "comment_id"],
        required_query_params=[],
        body_json_file_expected=False,
        optional_query_params=["cursor"],
        safety=SafetyClassification(
            mode="read-only",
            requires_yes=False,
            requires_ack_irreversible=False,
            live_verification_note=_PENDING_VERIFY,
        ),
    ),
    OperationSpec(
        area="comments",
        op_key="post-comment-reaction",
        title="Add comment reaction",
        method="POST",
        path_template="/v1/files/{file_key}/comments/{comment_id}/reactions",
        docs_url=AREAS_DOC_URLS["comments"],
        scope_notes="Add one emoji reaction to a comment.",
        auth_notes="OAuth2 file_comments:write or PAT with write scope.",
        required_path_params=["file_key", "comment_id"],
        required_query_params=[],
        body_json_file_expected=True,
        safety=SafetyClassification(
            mode="write",
            requires_yes=True,
            requires_ack_irreversible=False,
            live_verification_note=_PENDING_VERIFY,
        ),
        verification_strategy="comment-reaction-post",
    ),
    OperationSpec(
        area="comments",
        op_key="delete-comment-reaction",
        title="Delete comment reaction",
        method="DELETE",
        path_template="/v1/files/{file_key}/comments/{comment_id}/reactions",
        docs_url=AREAS_DOC_URLS["comments"],
        scope_notes="Delete one reaction by emoji.",
        auth_notes="OAuth2 file_comments:write or PAT with write scope.",
        required_path_params=["file_key", "comment_id"],
        required_query_params=["emoji"],
        body_json_file_expected=False,
        safety=SafetyClassification(
            mode="write",
            requires_yes=True,
            requires_ack_irreversible=False,
            live_verification_note=_PENDING_VERIFY,
        ),
        verification_strategy="comment-reaction-delete",
    ),
    OperationSpec(
        area="users",
        op_key="get-me",
        title="Get current user",
        method="GET",
        path_template="/v1/me",
        docs_url=AREAS_DOC_URLS["users"],
        scope_notes="Fetch profile for authenticated principal.",
        auth_notes="PAT or OAuth2 current_user:read (+ files:read optional in docs for compatibility).",
        required_path_params=[],
        required_query_params=[],
        body_json_file_expected=False,
        safety=SafetyClassification(
            mode="read-only",
            requires_yes=False,
            requires_ack_irreversible=False,
            live_verification_note=_PENDING_VERIFY,
        ),
    ),
    OperationSpec(
        area="projects",
        op_key="get-team-projects",
        title="Get projects in team",
        method="GET",
        path_template="/v1/teams/{team_id}/projects",
        docs_url=AREAS_DOC_URLS["projects"],
        scope_notes="List projects visible to the authenticated user/owner for a team.",
        auth_notes="PAT/Plan token or OAuth2 with projects:read + files:read.",
        required_path_params=["team_id"],
        required_query_params=[],
        body_json_file_expected=False,
        safety=SafetyClassification(
            mode="read-only",
            requires_yes=False,
            requires_ack_irreversible=False,
            live_verification_note=_PENDING_VERIFY,
        ),
    ),
    OperationSpec(
        area="projects",
        op_key="get-project-meta",
        title="Get project metadata",
        method="GET",
        path_template="/v1/projects/{project_id}/meta",
        docs_url=AREAS_DOC_URLS["projects"],
        scope_notes="Fetch project metadata for an org/project ID.",
        auth_notes="PAT/Plan token or OAuth2 with project_metadata:read.",
        required_path_params=["project_id"],
        required_query_params=[],
        body_json_file_expected=False,
        safety=SafetyClassification(
            mode="read-only",
            requires_yes=False,
            requires_ack_irreversible=False,
            live_verification_note=_PENDING_VERIFY,
        ),
    ),
    OperationSpec(
        area="projects",
        op_key="get-project-files",
        title="Get files in project",
        method="GET",
        path_template="/v1/projects/{project_id}/files",
        docs_url=AREAS_DOC_URLS["projects"],
        scope_notes="List files in project, with optional branch metadata.",
        auth_notes="PAT/Plan token or OAuth2 with projects:read + files:read.",
        required_path_params=["project_id"],
        required_query_params=[],
        body_json_file_expected=False,
        optional_query_params=["branch_data"],
        safety=SafetyClassification(
            mode="read-only",
            requires_yes=False,
            requires_ack_irreversible=False,
            live_verification_note=_PENDING_VERIFY,
        ),
    ),
    OperationSpec(
        area="components",
        op_key="get-team-components",
        title="Get team components",
        method="GET",
        path_template="/v1/teams/{team_id}/components",
        docs_url=AREAS_DOC_URLS["components"],
        scope_notes="Paginated list of published components in a team library.",
        auth_notes="PAT/Plan token or OAuth2 with team_library_content:read + files:read.",
        required_path_params=["team_id"],
        required_query_params=[],
        body_json_file_expected=False,
        optional_query_params=["page_size", "after", "before"],
        safety=SafetyClassification(
            mode="read-only",
            requires_yes=False,
            requires_ack_irreversible=False,
            live_verification_note=_PENDING_VERIFY,
        ),
    ),
    OperationSpec(
        area="components",
        op_key="get-file-components",
        title="Get file components",
        method="GET",
        path_template="/v1/files/{file_key}/components",
        docs_url=AREAS_DOC_URLS["components"],
        scope_notes="List published components from a file library.",
        auth_notes="PAT/Plan token or OAuth2 with library_content:read + files:read.",
        required_path_params=["file_key"],
        required_query_params=[],
        body_json_file_expected=False,
        safety=SafetyClassification(
            mode="read-only",
            requires_yes=False,
            requires_ack_irreversible=False,
            live_verification_note=_PENDING_VERIFY,
        ),
    ),
    OperationSpec(
        area="components",
        op_key="get-component",
        title="Get component",
        method="GET",
        path_template="/v1/components/{key}",
        docs_url=AREAS_DOC_URLS["components"],
        scope_notes="Get a component metadata object by key.",
        auth_notes="PAT/Plan token or OAuth2 with library_assets:read + files:read.",
        required_path_params=["key"],
        required_query_params=[],
        body_json_file_expected=False,
        safety=SafetyClassification(
            mode="read-only",
            requires_yes=False,
            requires_ack_irreversible=False,
            live_verification_note=_PENDING_VERIFY,
        ),
    ),
    OperationSpec(
        area="components",
        op_key="get-team-component-sets",
        title="Get team component sets",
        method="GET",
        path_template="/v1/teams/{team_id}/component_sets",
        docs_url=AREAS_DOC_URLS["components"],
        scope_notes="Paginated list of published component sets in team library.",
        auth_notes="PAT/Plan token or OAuth2 with team_library_content:read + files:read.",
        required_path_params=["team_id"],
        required_query_params=[],
        body_json_file_expected=False,
        optional_query_params=["page_size", "after", "before"],
        safety=SafetyClassification(
            mode="read-only",
            requires_yes=False,
            requires_ack_irreversible=False,
            live_verification_note=_PENDING_VERIFY,
        ),
    ),
    OperationSpec(
        area="components",
        op_key="get-file-component-sets",
        title="Get file component sets",
        method="GET",
        path_template="/v1/files/{file_key}/component_sets",
        docs_url=AREAS_DOC_URLS["components"],
        scope_notes="List published component sets from a file library.",
        auth_notes="PAT/Plan token or OAuth2 with library_content:read + files:read.",
        required_path_params=["file_key"],
        required_query_params=[],
        body_json_file_expected=False,
        safety=SafetyClassification(
            mode="read-only",
            requires_yes=False,
            requires_ack_irreversible=False,
            live_verification_note=_PENDING_VERIFY,
        ),
    ),
    OperationSpec(
        area="components",
        op_key="get-component-set",
        title="Get component set",
        method="GET",
        path_template="/v1/component_sets/{key}",
        docs_url=AREAS_DOC_URLS["components"],
        scope_notes="Get component set metadata by key.",
        auth_notes="PAT/Plan token or OAuth2 with library_assets:read + files:read.",
        required_path_params=["key"],
        required_query_params=[],
        body_json_file_expected=False,
        safety=SafetyClassification(
            mode="read-only",
            requires_yes=False,
            requires_ack_irreversible=False,
            live_verification_note=_PENDING_VERIFY,
        ),
    ),
    OperationSpec(
        area="components",
        op_key="get-team-styles",
        title="Get team styles",
        method="GET",
        path_template="/v1/teams/{team_id}/styles",
        docs_url=AREAS_DOC_URLS["components"],
        scope_notes="Paginated list of published styles in a team library.",
        auth_notes="PAT/Plan token or OAuth2 with team_library_content:read + files:read.",
        required_path_params=["team_id"],
        required_query_params=[],
        body_json_file_expected=False,
        optional_query_params=["page_size", "after", "before"],
        safety=SafetyClassification(
            mode="read-only",
            requires_yes=False,
            requires_ack_irreversible=False,
            live_verification_note=_PENDING_VERIFY,
        ),
    ),
    OperationSpec(
        area="components",
        op_key="get-file-styles",
        title="Get file styles",
        method="GET",
        path_template="/v1/files/{file_key}/styles",
        docs_url=AREAS_DOC_URLS["components"],
        scope_notes="List published styles from a file library.",
        auth_notes="PAT/Plan token or OAuth2 with library_content:read + files:read.",
        required_path_params=["file_key"],
        required_query_params=[],
        body_json_file_expected=False,
        safety=SafetyClassification(
            mode="read-only",
            requires_yes=False,
            requires_ack_irreversible=False,
            live_verification_note=_PENDING_VERIFY,
        ),
    ),
    OperationSpec(
        area="components",
        op_key="get-style",
        title="Get style",
        method="GET",
        path_template="/v1/styles/{key}",
        docs_url=AREAS_DOC_URLS["components"],
        scope_notes="Get style metadata by key.",
        auth_notes="PAT/Plan token or OAuth2 with library_assets:read + files:read.",
        required_path_params=["key"],
        required_query_params=[],
        body_json_file_expected=False,
        safety=SafetyClassification(
            mode="read-only",
            requires_yes=False,
            requires_ack_irreversible=False,
            live_verification_note=_PENDING_VERIFY,
        ),
    ),
    OperationSpec(
        area="webhooks",
        op_key="get-webhooks",
        title="Get webhooks",
        method="GET",
        path_template="/v2/webhooks",
        docs_url=AREAS_DOC_URLS["webhooks"],
        scope_notes="List webhooks by context or plan pagination.",
        auth_notes="PAT/Plan token or OAuth2 webhooks:read.",
        required_path_params=[],
        required_query_params=[],
        body_json_file_expected=False,
        optional_query_params=["context", "context_id", "plan_api_id", "cursor"],
        safety=SafetyClassification(
            mode="read-only",
            requires_yes=False,
            requires_ack_irreversible=False,
            live_verification_note=_PENDING_VERIFY,
        ),
    ),
    OperationSpec(
        area="webhooks",
        op_key="create-webhook",
        title="Create webhook",
        method="POST",
        path_template="/v2/webhooks",
        docs_url=AREAS_DOC_URLS["webhooks"],
        scope_notes="Create webhook subscription for supported event set.",
        auth_notes="PAT/Plan token or OAuth2 webhooks:write.",
        required_path_params=[],
        required_query_params=[],
        body_json_file_expected=True,
        safety=SafetyClassification(
            mode="write",
            requires_yes=True,
            requires_ack_irreversible=False,
            live_verification_note=_PENDING_VERIFY,
        ),
        verification_strategy="webhook-create",
    ),
    OperationSpec(
        area="webhooks",
        op_key="get-webhook",
        title="Get webhook",
        method="GET",
        path_template="/v2/webhooks/{webhook_id}",
        docs_url=AREAS_DOC_URLS["webhooks"],
        scope_notes="Fetch webhook metadata by id.",
        auth_notes="PAT/Plan token or OAuth2 webhooks:read + files:read.",
        required_path_params=["webhook_id"],
        required_query_params=[],
        body_json_file_expected=False,
        safety=SafetyClassification(
            mode="read-only",
            requires_yes=False,
            requires_ack_irreversible=False,
            live_verification_note=_PENDING_VERIFY,
        ),
    ),
    OperationSpec(
        area="webhooks",
        op_key="update-webhook",
        title="Update webhook",
        method="PUT",
        path_template="/v2/webhooks/{webhook_id}",
        docs_url=AREAS_DOC_URLS["webhooks"],
        scope_notes="Update event_type/endpoint/description/passcode/status.",
        auth_notes="PAT/Plan token or OAuth2 webhooks:write.",
        required_path_params=["webhook_id"],
        required_query_params=[],
        body_json_file_expected=True,
        safety=SafetyClassification(
            mode="write",
            requires_yes=True,
            requires_ack_irreversible=False,
            live_verification_note=_PENDING_VERIFY,
        ),
        verification_strategy="webhook-update",
    ),
    OperationSpec(
        area="webhooks",
        op_key="delete-webhook",
        title="Delete webhook",
        method="DELETE",
        path_template="/v2/webhooks/{webhook_id}",
        docs_url=AREAS_DOC_URLS["webhooks"],
        scope_notes="Delete webhook subscription. Not reversible.",
        auth_notes="PAT/Plan token or OAuth2 webhooks:write.",
        required_path_params=["webhook_id"],
        required_query_params=[],
        body_json_file_expected=False,
        safety=SafetyClassification(
            mode="write",
            requires_yes=True,
            requires_ack_irreversible=True,
            live_verification_note="Live check needed; deletion cannot be undone.",
        ),
        verification_strategy="webhook-delete",
    ),
    OperationSpec(
        area="webhooks",
        op_key="get-team-webhooks",
        title="Get team webhooks (deprecated)",
        method="GET",
        path_template="/v2/teams/{team_id}/webhooks",
        docs_url=AREAS_DOC_URLS["webhooks"],
        scope_notes="Deprecated endpoint retained for compatibility.",
        auth_notes="PAT/Plan token or OAuth2 webhooks:read + files:read.",
        required_path_params=["team_id"],
        required_query_params=[],
        body_json_file_expected=False,
        safety=SafetyClassification(
            mode="read-only",
            requires_yes=False,
            requires_ack_irreversible=False,
            live_verification_note=_PENDING_VERIFY,
        ),
    ),
    OperationSpec(
        area="webhooks",
        op_key="get-webhook-requests",
        title="Get webhook requests",
        method="GET",
        path_template="/v2/webhooks/{webhook_id}/requests",
        docs_url=AREAS_DOC_URLS["webhooks"],
        scope_notes="Get webhook request attempts in last week for debugging.",
        auth_notes="PAT/Plan token or OAuth2 webhooks:read + files:read.",
        required_path_params=["webhook_id"],
        required_query_params=[],
        body_json_file_expected=False,
        safety=SafetyClassification(
            mode="read-only",
            requires_yes=False,
            requires_ack_irreversible=False,
            live_verification_note=_PENDING_VERIFY,
        ),
    ),
    OperationSpec(
        area="activity-logs",
        op_key="get-activity-logs",
        title="Get activity logs",
        method="GET",
        path_template="/v1/activity_logs",
        docs_url=AREAS_DOC_URLS["activity-logs"],
        scope_notes="Org-scoped activity log events; supports filters and paging order options.",
        auth_notes="PlanAccessToken with org:activity_log_read or OrgOAuth2 org:activity_log_read.",
        required_path_params=[],
        required_query_params=[],
        body_json_file_expected=False,
        optional_query_params=["events", "start_time", "end_time", "limit", "order"],
        safety=SafetyClassification(
            mode="read-only",
            requires_yes=False,
            requires_ack_irreversible=False,
            live_verification_note=_PENDING_VERIFY,
        ),
    ),
    OperationSpec(
        area="developer-logs",
        op_key="get-developer-logs",
        title="Get developer logs",
        method="POST",
        path_template="/v1/developer_logs",
        docs_url=AREAS_DOC_URLS["developer-logs"],
        scope_notes="Read logs for REST API and MCP calls in org; filter using optional request body.",
        auth_notes="PlanAccessToken only (org developer log read scope in org settings).",
        required_path_params=[],
        required_query_params=[],
        body_json_file_expected=False,
        safety=SafetyClassification(
            mode="read-only",
            requires_yes=False,
            requires_ack_irreversible=False,
            live_verification_note=_PENDING_VERIFY,
        ),
    ),
    OperationSpec(
        area="discovery",
        op_key="get-discovery",
        title="Discovery",
        method="GET",
        path_template="/v1/discovery",
        docs_url=AREAS_DOC_URLS["discovery"],
        scope_notes="Endpoint is documented in Figma docs but missing from the published OpenAPI YAML; kept as manual docs-only mapping.",
        auth_notes="PAT/Plan token or OAuth2 subject to area-specific auth gates.",
        required_path_params=[],
        required_query_params=["start_date"],
        required_query_exactly_one_of=[],
        body_json_file_expected=False,
        optional_query_params=["end_date", "file_ttl_in_seconds"],
        safety=SafetyClassification(
            mode="read-only",
            requires_yes=False,
            requires_ack_irreversible=False,
            live_verification_note="Pending manual endpoint validation against live API since it is not in openapi.yaml.",
        ),
    ),
    OperationSpec(
        area="payments",
        op_key="get-payments-by-plugin-payment-token",
        title="Get payments by plugin payment token",
        method="GET",
        path_template="/v1/payments",
        docs_url=AREAS_DOC_URLS["payments"],
        scope_notes="Plugin/widget style read path using plugin_payment_token.",
        auth_notes="PersonalAccessToken; token accepted from plugin payment flow in docs.",
        required_path_params=[],
        required_query_params=["plugin_payment_token"],
        body_json_file_expected=False,
        safety=SafetyClassification(
            mode="read-only",
            requires_yes=False,
            requires_ack_irreversible=False,
            live_verification_note=_PENDING_VERIFY,
        ),
    ),
    OperationSpec(
        area="payments",
        op_key="get-payments-by-user-resource",
        title="Get payments by user and resource",
        method="GET",
        path_template="/v1/payments",
        docs_url=AREAS_DOC_URLS["payments"],
        scope_notes="Non-plugin path requiring user_id and exactly one resource id (community_file_id, plugin_id, or widget_id).",
        auth_notes="PersonalAccessToken; used outside plugin/widget runtime.",
        required_path_params=[],
        required_query_params=["user_id"],
        required_query_exactly_one_of=[["community_file_id", "plugin_id", "widget_id"]],
        body_json_file_expected=False,
        safety=SafetyClassification(
            mode="read-only",
            requires_yes=False,
            requires_ack_irreversible=False,
            live_verification_note="Pending validation against user+resource mode behavior per docs.",
        ),
    ),
    OperationSpec(
        area="variables",
        op_key="get-local-variables",
        title="Get local variables",
        method="GET",
        path_template="/v1/files/{file_key}/variables/local",
        docs_url=AREAS_DOC_URLS["variables"],
        scope_notes="Get local variables and remote variables used by a file.",
        auth_notes="PAT or OAuth2 with file_variables:read.",
        required_path_params=["file_key"],
        required_query_params=[],
        body_json_file_expected=False,
        safety=SafetyClassification(
            mode="read-only",
            requires_yes=False,
            requires_ack_irreversible=False,
            live_verification_note=_PENDING_VERIFY,
        ),
    ),
    OperationSpec(
        area="variables",
        op_key="get-published-variables",
        title="Get published variables",
        method="GET",
        path_template="/v1/files/{file_key}/variables/published",
        docs_url=AREAS_DOC_URLS["variables"],
        scope_notes="Get published variables for a main file key.",
        auth_notes="PAT or OAuth2 with file_variables:read.",
        required_path_params=["file_key"],
        required_query_params=[],
        body_json_file_expected=False,
        safety=SafetyClassification(
            mode="read-only",
            requires_yes=False,
            requires_ack_irreversible=False,
            live_verification_note=_PENDING_VERIFY,
        ),
    ),
    OperationSpec(
        area="variables",
        op_key="post-variables",
        title="Create/modify/delete variables",
        method="POST",
        path_template="/v1/files/{file_key}/variables",
        docs_url=AREAS_DOC_URLS["variables"],
        scope_notes="Bulk create/update/delete variable collections, modes, vars, and values (atomic request).",
        auth_notes="PAT or OAuth2 with file_variables:write.",
        required_path_params=["file_key"],
        required_query_params=[],
        body_json_file_expected=True,
        safety=SafetyClassification(
            mode="write",
            requires_yes=True,
            requires_ack_irreversible=False,
            live_verification_note="Pending live verification; changes are not automatically reversible.",
        ),
    ),
    OperationSpec(
        area="dev-resources",
        op_key="get-dev-resources",
        title="Get dev resources",
        method="GET",
        path_template="/v1/files/{file_key}/dev_resources",
        docs_url=AREAS_DOC_URLS["dev-resources"],
        scope_notes="List dev resources in file; optional node_ids filter.",
        auth_notes="PAT/Plan token or OAuth2 with file_dev_resources:read.",
        required_path_params=["file_key"],
        required_query_params=[],
        body_json_file_expected=False,
        optional_query_params=["node_ids"],
        safety=SafetyClassification(
            mode="read-only",
            requires_yes=False,
            requires_ack_irreversible=False,
            live_verification_note=_PENDING_VERIFY,
        ),
    ),
    OperationSpec(
        area="dev-resources",
        op_key="create-dev-resources",
        title="Create dev resources",
        method="POST",
        path_template="/v1/dev_resources",
        docs_url=AREAS_DOC_URLS["dev-resources"],
        scope_notes="Bulk create across files. Response includes created and error arrays.",
        auth_notes="PAT/Plan token or OAuth2 with file_dev_resources:write.",
        required_path_params=[],
        required_query_params=[],
        body_json_file_expected=True,
        safety=SafetyClassification(
            mode="write",
            requires_yes=True,
            requires_ack_irreversible=False,
            live_verification_note="Pending live validation; creation changes cannot be auto-rolled back.",
        ),
    ),
    OperationSpec(
        area="dev-resources",
        op_key="update-dev-resources",
        title="Update dev resources",
        method="PUT",
        path_template="/v1/dev_resources",
        docs_url=AREAS_DOC_URLS["dev-resources"],
        scope_notes="Bulk update link name and URL for existing resources.",
        auth_notes="PAT/Plan token or OAuth2 with file_dev_resources:write.",
        required_path_params=[],
        required_query_params=[],
        body_json_file_expected=True,
        safety=SafetyClassification(
            mode="write",
            requires_yes=True,
            requires_ack_irreversible=False,
            live_verification_note=_PENDING_VERIFY,
        ),
    ),
    OperationSpec(
        area="dev-resources",
        op_key="delete-dev-resource",
        title="Delete dev resource",
        method="DELETE",
        path_template="/v1/files/{file_key}/dev_resources/{dev_resource_id}",
        docs_url=AREAS_DOC_URLS["dev-resources"],
        scope_notes="Delete a single dev resource by id from a file.",
        auth_notes="PAT/Plan token or OAuth2 with file_dev_resources:write.",
        required_path_params=["file_key", "dev_resource_id"],
        required_query_params=[],
        body_json_file_expected=False,
        safety=SafetyClassification(
            mode="write",
            requires_yes=True,
            requires_ack_irreversible=True,
            live_verification_note="Live check needed; deletion cannot be undone.",
        ),
        verification_strategy="dev-resource-delete",
    ),
    OperationSpec(
        area="library-analytics",
        op_key="get-library-analytics-component-actions",
        title="Get component actions analytics",
        method="GET",
        path_template="/v1/analytics/libraries/{file_key}/component/actions",
        docs_url=AREAS_DOC_URLS["library-analytics"],
        scope_notes="Requires group_by parameter; optional paging with cursor.",
        auth_notes="PAT/Plan token or OAuth2 with library_analytics:read.",
        required_path_params=["file_key"],
        required_query_params=["group_by"],
        body_json_file_expected=False,
        optional_query_params=["cursor", "start_date", "end_date"],
        safety=SafetyClassification(
            mode="read-only",
            requires_yes=False,
            requires_ack_irreversible=False,
            live_verification_note=_PENDING_VERIFY,
        ),
    ),
    OperationSpec(
        area="library-analytics",
        op_key="get-library-analytics-component-usages",
        title="Get component usage analytics",
        method="GET",
        path_template="/v1/analytics/libraries/{file_key}/component/usages",
        docs_url=AREAS_DOC_URLS["library-analytics"],
        scope_notes="Requires group_by parameter; optional paging with cursor.",
        auth_notes="PAT/Plan token or OAuth2 with library_analytics:read.",
        required_path_params=["file_key"],
        required_query_params=["group_by"],
        body_json_file_expected=False,
        optional_query_params=["cursor"],
        safety=SafetyClassification(
            mode="read-only",
            requires_yes=False,
            requires_ack_irreversible=False,
            live_verification_note=_PENDING_VERIFY,
        ),
    ),
    OperationSpec(
        area="library-analytics",
        op_key="get-library-analytics-style-actions",
        title="Get style actions analytics",
        method="GET",
        path_template="/v1/analytics/libraries/{file_key}/style/actions",
        docs_url=AREAS_DOC_URLS["library-analytics"],
        scope_notes="Requires group_by parameter; optional paging with cursor.",
        auth_notes="PAT/Plan token or OAuth2 with library_analytics:read.",
        required_path_params=["file_key"],
        required_query_params=["group_by"],
        body_json_file_expected=False,
        optional_query_params=["cursor", "start_date", "end_date"],
        safety=SafetyClassification(
            mode="read-only",
            requires_yes=False,
            requires_ack_irreversible=False,
            live_verification_note=_PENDING_VERIFY,
        ),
    ),
    OperationSpec(
        area="library-analytics",
        op_key="get-library-analytics-style-usages",
        title="Get style usage analytics",
        method="GET",
        path_template="/v1/analytics/libraries/{file_key}/style/usages",
        docs_url=AREAS_DOC_URLS["library-analytics"],
        scope_notes="Requires group_by parameter; optional paging with cursor.",
        auth_notes="PAT/Plan token or OAuth2 with library_analytics:read.",
        required_path_params=["file_key"],
        required_query_params=["group_by"],
        body_json_file_expected=False,
        optional_query_params=["cursor"],
        safety=SafetyClassification(
            mode="read-only",
            requires_yes=False,
            requires_ack_irreversible=False,
            live_verification_note=_PENDING_VERIFY,
        ),
    ),
    OperationSpec(
        area="library-analytics",
        op_key="get-library-analytics-variable-actions",
        title="Get variable actions analytics",
        method="GET",
        path_template="/v1/analytics/libraries/{file_key}/variable/actions",
        docs_url=AREAS_DOC_URLS["library-analytics"],
        scope_notes="Requires group_by parameter; optional paging with cursor.",
        auth_notes="PAT/Plan token or OAuth2 with library_analytics:read.",
        required_path_params=["file_key"],
        required_query_params=["group_by"],
        body_json_file_expected=False,
        optional_query_params=["cursor", "start_date", "end_date"],
        safety=SafetyClassification(
            mode="read-only",
            requires_yes=False,
            requires_ack_irreversible=False,
            live_verification_note=_PENDING_VERIFY,
        ),
    ),
    OperationSpec(
        area="library-analytics",
        op_key="get-library-analytics-variable-usages",
        title="Get variable usage analytics",
        method="GET",
        path_template="/v1/analytics/libraries/{file_key}/variable/usages",
        docs_url=AREAS_DOC_URLS["library-analytics"],
        scope_notes="Requires group_by parameter; optional paging with cursor.",
        auth_notes="PAT/Plan token or OAuth2 with library_analytics:read.",
        required_path_params=["file_key"],
        required_query_params=["group_by"],
        body_json_file_expected=False,
        optional_query_params=["cursor"],
        safety=SafetyClassification(
            mode="read-only",
            requires_yes=False,
            requires_ack_irreversible=False,
            live_verification_note=_PENDING_VERIFY,
        ),
    ),
    OperationSpec(
        area="oembed",
        op_key="get-oembed",
        title="Get oEmbed data",
        method="GET",
        path_template="/v1/oembed",
        docs_url=AREAS_DOC_URLS["oembed"],
        scope_notes="Convert a Figma file or published Make URL to oEmbed payload.",
        auth_notes="PAT or OAuth2 with file_metadata:read.",
        required_path_params=[],
        required_query_params=["url"],
        body_json_file_expected=False,
        optional_query_params=["maxwidth", "maxheight"],
        safety=SafetyClassification(
            mode="read-only",
            requires_yes=False,
            requires_ack_irreversible=False,
            live_verification_note=_PENDING_VERIFY,
        ),
    ),
]


OPERATION_INDEX: Final[dict[str, OperationSpec]] = {
    f"{spec.area}:{spec.op_key}": spec for spec in OPERATION_SPECS
}


def get_operation(area: str, op_key: str) -> OperationSpec | None:
    return OPERATION_INDEX.get(f"{area}:{op_key}")


def list_operations(*, area: str | None = None, method: str | None = None, include_writes: bool = False, contains: str | None = None) -> list[OperationSpec]:
    needle = (contains or "").strip().lower()
    out: list[OperationSpec] = []
    method_u = method.upper() if method else None
    for spec in OPERATION_SPECS:
        if area and spec.area != area:
            continue
        if method_u and spec.method != method_u:
            continue
        if not include_writes and spec.safety.mode == "write":
            continue
        if needle:
            haystack = " ".join(
                [
                    spec.area,
                    spec.op_key,
                    spec.title,
                    spec.path_template,
                    spec.scope_notes,
                    spec.auth_notes,
                ]
            ).lower()
            if needle not in haystack:
                continue
        out.append(spec)
    return out


def list_operation_query_params(spec: OperationSpec) -> list[str]:
    names: list[str] = []
    seen: set[str] = set()

    def _add(name: str) -> None:
        if name in seen:
            return
        seen.add(name)
        names.append(name)

    for name in spec.required_query_params:
        _add(name)

    for group in spec.required_query_exactly_one_of:
        for name in group:
            _add(name)

    for name in spec.optional_query_params:
        _add(name)

    return names
