from __future__ import annotations

from typing import Final

# THIS FILE IS GENERATED. DO NOT EDIT BY HAND.

OPERATIONS: Final = {'collection_sha256': 'd330b3df8f1b1962fcae295b0dc47b831c15f68d0d90db73c4dcb151968e33fe',
 'collection_url': 'https://documenter.gw.postman.com/api/collections/9688716/TzzANHFJ?segregateAuth=true&versionTag=latest',
 'command_prefix': 'sav',
 'operation_count': 12,
 'operations': [{'command_path': 'domains active',
                 'endpoint': '/domains_api_v1/get_active_domains_in_account',
                 'http_method': 'GET',
                 'kind': 'read',
                 'operation_id': 'get_active_domains_in_account',
                 'required_params': [],
                 'requires_approval': False},
                {'command_path': 'sales recent-auction',
                 'endpoint': '/domains_api_v1/get_recent_auction_sales',
                 'http_method': 'GET',
                 'kind': 'read',
                 'operation_id': 'get_recent_auction_sales',
                 'required_params': [],
                 'requires_approval': False},
                {'command_path': 'sales recent-premium',
                 'endpoint': '/domains_api_v1/get_recent_premium_sales',
                 'http_method': 'GET',
                 'kind': 'read',
                 'operation_id': 'get_recent_premium_sales',
                 'required_params': [],
                 'requires_approval': False},
                {'command_path': 'pricing list',
                 'endpoint': '/domains_api_v1/get_domain_pricing',
                 'http_method': 'GET',
                 'kind': 'read',
                 'operation_id': 'get_domain_pricing',
                 'required_params': [],
                 'requires_approval': False},
                {'command_path': 'domains remove-from-sale',
                 'endpoint': '/domains_api_v1/remove_domain_for_sale',
                 'http_method': 'GET',
                 'kind': 'write',
                 'operation_id': 'remove_domain_for_sale',
                 'required_params': [{'cli_flag': '--domain-name',
                                      'name': 'domain_name',
                                      'required': True,
                                      'source': 'query_example'}],
                 'requires_approval': True},
                {'command_path': 'domains submit-transfer-code',
                 'endpoint': '/domains_api_v1/submit_auth_code_for_pending_transfer_in',
                 'http_method': 'GET',
                 'kind': 'write',
                 'operation_id': 'submit_auth_code_for_pending_transfer_in',
                 'required_params': [{'cli_flag': '--domain-name',
                                      'name': 'domain_name',
                                      'required': True,
                                      'source': 'query_example'},
                                     {'cli_flag': '--auth-code-file',
                                      'name': 'auth_code',
                                      'required': True,
                                      'source': 'query_example'}],
                 'requires_approval': True},
                {'command_path': 'domains set-auto-renewal',
                 'endpoint': '/domains_api_v1/update_domain_auto_renewal',
                 'http_method': 'GET',
                 'kind': 'write',
                 'operation_id': 'update_domain_auto_renewal',
                 'required_params': [{'cli_flag': '--domain-name',
                                      'name': 'domain_name',
                                      'required': True,
                                      'source': 'query_example'},
                                     {'cli_flag': '--enabled',
                                      'name': 'enabled',
                                      'required': True,
                                      'source': 'query_example'}],
                 'requires_approval': True},
                {'command_path': 'domains set-sale-price',
                 'endpoint': '/domains_api_v1/update_domain_for_sale_price',
                 'http_method': 'GET',
                 'kind': 'write',
                 'operation_id': 'update_domain_for_sale_price',
                 'required_params': [{'cli_flag': '--domain-name',
                                      'name': 'domain_name',
                                      'required': True,
                                      'source': 'query_example'},
                                     {'cli_flag': '--sale-price',
                                      'name': 'sale_price',
                                      'required': True,
                                      'source': 'query_example'}],
                 'requires_approval': True},
                {'command_path': 'domains set-nameservers',
                 'endpoint': '/domains_api_v1/update_domain_nameservers',
                 'http_method': 'GET',
                 'kind': 'write',
                 'operation_id': 'update_domain_nameservers',
                 'required_params': [{'cli_flag': '--domain-name',
                                      'name': 'domain_name',
                                      'required': True,
                                      'source': 'query_example'},
                                     {'cli_flag': '--ns-1',
                                      'name': 'ns_1',
                                      'required': True,
                                      'source': 'query_example'},
                                     {'cli_flag': '--ns-2',
                                      'name': 'ns_2',
                                      'required': True,
                                      'source': 'query_example'}],
                 'requires_approval': True},
                {'command_path': 'domains set-privacy',
                 'endpoint': '/domains_api_v1/update_domain_privacy',
                 'http_method': 'GET',
                 'kind': 'write',
                 'operation_id': 'update_domain_privacy',
                 'required_params': [{'cli_flag': '--domain-name',
                                      'name': 'domain_name',
                                      'required': True,
                                      'source': 'query_example'},
                                     {'cli_flag': '--enabled',
                                      'name': 'enabled',
                                      'required': True,
                                      'source': 'query_example'}],
                 'requires_approval': True},
                {'command_path': 'domains set-whois-contacts',
                 'endpoint': '/domains_api_v1/update_domain_whois_contacts',
                 'http_method': 'GET',
                 'kind': 'write',
                 'operation_id': 'update_domain_whois_contacts',
                 'required_params': [{'cli_flag': '--domain-name',
                                      'name': 'domain_name',
                                      'required': True,
                                      'source': 'query_example'},
                                     {'cli_flag': '--name',
                                      'name': 'name',
                                      'required': True,
                                      'source': 'query_example'},
                                     {'cli_flag': '--organization',
                                      'name': 'organization',
                                      'required': True,
                                      'source': 'query_example'},
                                     {'cli_flag': '--email-address',
                                      'name': 'email_address',
                                      'required': True,
                                      'source': 'query_example'},
                                     {'cli_flag': '--street',
                                      'name': 'street',
                                      'required': True,
                                      'source': 'query_example'},
                                     {'cli_flag': '--city',
                                      'name': 'city',
                                      'required': True,
                                      'source': 'query_example'},
                                     {'cli_flag': '--country',
                                      'name': 'country',
                                      'required': True,
                                      'source': 'query_example'},
                                     {'cli_flag': '--phone',
                                      'name': 'phone',
                                      'required': True,
                                      'source': 'query_example'},
                                     {'cli_flag': '--state',
                                      'name': 'state',
                                      'required': True,
                                      'source': 'query_example'},
                                     {'cli_flag': '--postal-code',
                                      'name': 'postal_code',
                                      'required': True,
                                      'source': 'query_example'},
                                     {'cli_flag': '--update-registrant',
                                      'name': 'update_registrant',
                                      'required': True,
                                      'source': 'query_example'},
                                     {'cli_flag': '--update-tech',
                                      'name': 'update_tech',
                                      'required': True,
                                      'source': 'query_example'},
                                     {'cli_flag': '--update-admin',
                                      'name': 'update_admin',
                                      'required': True,
                                      'source': 'query_example'}],
                 'requires_approval': True},
                {'command_path': 'domains list-external-sale',
                 'endpoint': '/domains_api_v1/list_external_domain_for_sale',
                 'http_method': 'GET',
                 'kind': 'write',
                 'operation_id': 'list_external_domain_for_sale',
                 'required_params': [{'cli_flag': '--domain-name',
                                      'name': 'domain_name',
                                      'required': True,
                                      'source': 'query_example'},
                                     {'cli_flag': '--sale-price',
                                      'name': 'sale_price',
                                      'required': True,
                                      'source': 'query_example'}],
                 'requires_approval': True}],
 'schema_version': 1}
