from __future__ import annotations

from dataclasses import dataclass
from typing import Sequence
import re


@dataclass(frozen=True)
class Operation:
    name: str
    section: str
    description: str
    method: str
    path: str
    cli_command: str
    safety: Sequence[str]
    doc_url: str
    sample_args: Sequence[str] = ()


@dataclass(frozen=True)
class InventoryEntry:
    name: str
    section: str
    description: str
    method: str
    path: str
    status: str
    doc_url: str
    safety: Sequence[str]
    cli_command: str | None = None
    sample_args: Sequence[str] = ()


_PLACEHOLDER_SAMPLE_VALUES: dict[str, str] = {
    "voice_id": "voice-123",
    "generated_voice_id": "voice-preview-1",
    "dubbing_id": "dub-foo",
    "speaker_id": "speaker-1",
    "resource_id": "resource-1",
    "service_account_user_id": "svc-acc",
    "documentation_id": "doc-1",
    "project_id": "proj-1",
    "token_type": "tts_websocket",
}


def _default_sample_args(entry: InventoryEntry) -> tuple[str, ...]:
    if not entry.cli_command:
        return ()
    args: list[str] = []
    placeholders = re.findall(r"{([^}]+)}", entry.path)
    for placeholder in placeholders:
        args.append(f"--{placeholder.replace('_', '-')}")
        args.append(_PLACEHOLDER_SAMPLE_VALUES.get(placeholder, "value"))
    method = entry.method.upper()
    if method not in {"GET", "DELETE", "WEBSOCKET"}:
        args.extend(["--body", '{"example":"value"}'])
    safety = tuple(entry.safety or ())
    needs_out = "binary_output" in safety or ("sensitive_output" in safety and "write" in safety)
    if needs_out:
        suffix = "bin" if "binary_output" in safety else "json"
        args.extend(["--out", f"sample.{suffix}"])
    return tuple(args)


inventory_data: list[dict[str, object]] = [   {   "cli_command": "auth check",
        "description": "Retrieve the workspace profile and API key status.",
        "doc_url": "https://elevenlabs.io/docs/api-reference/user/get",
        "method": "GET",
        "name": "user_info",
        "path": "/v1/user",
        "safety": ("read", "sensitive_output"),
        "section": "User",
        "status": "Implemented"},
    {   "cli_command": "voices list",
        "description": "List all voices available to the workspace.",
        "doc_url": "https://elevenlabs.io/docs/api-reference/voices/get-all",
        "method": "GET",
        "name": "list_voices",
        "path": "/v1/voices",
        "safety": ("read",),
        "section": "Voices",
        "status": "Implemented"},
    {   "cli_command": "tts synthesize",
        "description": "Synthesize text into audio for a chosen voice.",
        "doc_url": "https://elevenlabs.io/docs/api-reference/text-to-speech/convert",
        "method": "POST",
        "name": "text_to_speech",
        "path": "/v1/text-to-speech/{voice_id}",
        "safety": ("write", "spend_money", "binary_output"),
        "section": "Text-to-speech",
        "status": "Implemented",
        "sample_args": ("--voice-id", "voice-123", "--text", "hi", "--out", "out.mp3")},
    {   "cli_command": "history list",
        "description": "Read the workspace generation history index.",
        "doc_url": "https://elevenlabs.io/docs/api-reference/history/list",
        "method": "GET",
        "name": "history_list",
        "path": "/v1/history",
        "safety": ("read", "sensitive_output"),
        "section": "Speech history",
        "status": "Implemented"},
    {   "cli_command": "history download",
        "description": "Download generated audio files from history.",
        "doc_url": "https://elevenlabs.io/docs/api-reference/history/download",
        "method": "POST",
        "name": "history_download",
        "path": "/v1/history/download",
        "safety": ("write", "binary_output"),
        "section": "Speech history",
        "status": "Implemented",
        "sample_args": ("--history-item-id", "item-1", "--out", "history.mp3")},
    {   "cli_command": "tts stream",
        "description": "Stream speech output for real-time playback.",
        "doc_url": "https://elevenlabs.io/docs/api-reference/text-to-speech/stream",
        "method": "POST",
        "name": "tts_stream",
        "path": "/v1/text-to-speech/{voice_id}/stream",
        "safety": ("write", "spend_money", "binary_output"),
        "section": "Text-to-speech",
        "status": "Implemented"},
    {   "cli_command": "stt transcribe",
        "description": "Transcribe audio files into text.",
        "doc_url": "https://elevenlabs.io/docs/api-reference/speech-to-text/convert",
        "method": "POST",
        "name": "speech_to_text",
        "path": "/v1/speech-to-text",
        "safety": ("write", "spend_money", "sensitive_output"),
        "section": "Speech-to-text",
        "status": "Implemented"},
    {   "cli_command": "stt realtime",
        "description": "WebSocket stream for live transcription.",
        "doc_url": "https://elevenlabs.io/docs/api-reference/speech-to-text/realtime",
        "method": "WEBSOCKET",
        "name": "speech_to_text_realtime",
        "path": "wss://api.elevenlabs.io/v1/speech-to-text/realtime",
        "safety": ("write", "sensitive_output"),
        "section": "Speech-to-text",
        "status": "Implemented"},
    {   "cli_command": "music compose",
        "description": "Compose songs from prompts or plans.",
        "doc_url": "https://elevenlabs.io/docs/api-reference/music/compose",
        "method": "POST",
        "name": "music_compose",
        "path": "/v1/music",
        "safety": ("write", "spend_money", "binary_output"),
        "section": "Music",
        "status": "Implemented"},
    {   "cli_command": "music stream",
        "description": "Stream compositional output while it runs.",
        "doc_url": "https://elevenlabs.io/docs/api-reference/music/stream",
        "method": "POST",
        "name": "music_stream",
        "path": "/v1/music/stream",
        "safety": ("write", "spend_money", "binary_output"),
        "section": "Music",
        "status": "Implemented"},
    {   "cli_command": "music plan create",
        "description": "Create a reusable composition plan.",
        "doc_url": "https://elevenlabs.io/docs/api-reference/music/create-composition-plan",
        "method": "POST",
        "name": "music_plan",
        "path": "/v1/music/plan",
        "safety": ("write", "spend_money"),
        "section": "Music",
        "status": "Implemented"},
    {   "cli_command": "music upload",
        "description": "Upload audio to influence composition plans.",
        "doc_url": "https://elevenlabs.io/docs/api-reference/music/upload",
        "method": "POST",
        "name": "music_upload",
        "path": "/v1/music/upload",
        "safety": ("write", "spend_money", "binary_output"),
        "section": "Music",
        "status": "Implemented"},
    {   "cli_command": "music stem-separation",
        "description": "Separate audio into instrument stems.",
        "doc_url": "https://elevenlabs.io/docs/api-reference/music/separate-stems",
        "method": "POST",
        "name": "music_stem_separation",
        "path": "/v1/music/stem-separation",
        "safety": ("write", "spend_money", "binary_output"),
        "section": "Music",
        "status": "Implemented"},
    {   "cli_command": "dialogue convert",
        "description": "Convert scripts into multi-voice dialogue.",
        "doc_url": "https://elevenlabs.io/docs/api-reference/text-to-dialogue",
        "method": "POST",
        "name": "text_to_dialogue",
        "path": "/v1/text-to-dialogue",
        "safety": ("write", "spend_money", "binary_output"),
        "section": "Text-to-dialogue",
        "status": "Implemented"},
    {   "cli_command": "voice-changer convert",
        "description": "Transform audio into a different voice.",
        "doc_url": "https://elevenlabs.io/docs/api-reference/speech-to-speech/convert",
        "method": "POST",
        "name": "speech_to_speech",
        "path": "/v1/speech-to-speech/{voice_id}",
        "safety": ("write", "spend_money", "binary_output"),
        "section": "Voice changer",
        "status": "Implemented"},
    {   "cli_command": "voice-design design",
        "description": "Generate preview voices from prompts.",
        "doc_url": "https://elevenlabs.io/docs/api-reference/text-to-voice/design",
        "method": "POST",
        "name": "voice_design",
        "path": "/v1/text-to-voice/design",
        "safety": ("write", "spend_money", "binary_output"),
        "section": "Voice design",
        "status": "Implemented"},
    {   "cli_command": "voice-design create",
        "description": "Persist a generated voice for reuse.",
        "doc_url": "https://elevenlabs.io/docs/api-reference/text-to-voice/create",
        "method": "POST",
        "name": "voice_create",
        "path": "/v1/text-to-voice",
        "safety": ("write", "spend_money", "binary_output"),
        "section": "Voice design",
        "status": "Implemented"},
    {   "cli_command": "voice-design remix",
        "description": "Remix a voice to refresh previews.",
        "doc_url": "https://elevenlabs.io/docs/api-reference/text-to-voice/remix",
        "method": "POST",
        "name": "voice_remix",
        "path": "/v1/text-to-voice/{voice_id}/remix",
        "safety": ("write", "spend_money", "binary_output"),
        "section": "Voice design",
        "status": "Implemented"},
    {   "cli_command": "voice-design stream",
        "description": "Stream a generated preview audio file.",
        "doc_url": "https://elevenlabs.io/docs/api-reference/text-to-voice/stream",
        "method": "GET",
        "name": "voice_preview_stream",
        "path": "/v1/text-to-voice/{generated_voice_id}/stream",
        "safety": ("read", "binary_output"),
        "section": "Voice design",
        "status": "Implemented"},
    {   "cli_command": "sound-effects generate",
        "description": "Create cinematic FX from text prompts.",
        "doc_url": "https://elevenlabs.io/docs/api-reference/text-to-sound-effects/convert",
        "method": "POST",
        "name": "sound_effects",
        "path": "/v1/sound-generation",
        "safety": ("write", "binary_output", "spend_money"),
        "section": "Sound effects",
        "status": "Implemented"},
    {   "cli_command": "audio-isolation convert",
        "description": "Isolate vocals from background noise.",
        "doc_url": "https://elevenlabs.io/docs/api-reference/audio-isolation/convert",
        "method": "POST",
        "name": "audio_isolation",
        "path": "/v1/audio-isolation",
        "safety": ("write", "spend_money", "binary_output"),
        "section": "Audio isolation",
        "status": "Implemented"},
    {   "cli_command": "dubbing create",
        "description": "Create a dubbed project in another language.",
        "doc_url": "https://elevenlabs.io/docs/api-reference/dubbing/create",
        "method": "POST",
        "name": "dubbing_create",
        "path": "/v1/dubbing",
        "safety": ("write", "spend_money", "binary_output"),
        "section": "Dubbing",
        "status": "Implemented"},
    {   "cli_command": "dubbing similar-voices",
        "description": "List voices similar to a dubbing speaker.",
        "doc_url": "https://elevenlabs.io/docs/api-reference/dubbing/resources/get-similar-voices",
        "method": "GET",
        "name": "dubbing_similar_voices",
        "path": "/v1/dubbing/resource/{dubbing_id}/speaker/{speaker_id}/similar-voices",
        "safety": ("read",),
        "section": "Dubbing",
        "status": "Implemented"},
    {   "cli_command": "forced-alignment create",
        "description": "Align transcripts to audio timestamps.",
        "doc_url": "https://elevenlabs.io/docs/api-reference/forced-alignment/create",
        "method": "POST",
        "name": "forced_alignment",
        "path": "/v1/forced-alignment",
        "safety": ("write", "spend_money", "sensitive_output"),
        "section": "Forced alignment",
        "status": "Implemented"},
    {   "cli_command": "pronunciation-dictionaries list",
        "description": "List workspace pronunciation dictionaries.",
        "doc_url": "https://elevenlabs.io/docs/api-reference/pronunciation-dictionaries/list",
        "method": "GET",
        "name": "pronunciation_dictionaries_list",
        "path": "/v1/pronunciation-dictionaries",
        "safety": ("read",),
        "section": "Pronunciation dictionaries",
        "status": "Implemented"},
    {   "cli_command": "models list",
        "description": "List available audio and dialogue models.",
        "doc_url": "https://elevenlabs.io/docs/api-reference/models",
        "method": "GET",
        "name": "models_list",
        "path": "/v1/models",
        "safety": ("read",),
        "section": "Core resources",
        "status": "Implemented"},
    {   "cli_command": "usage get",
        "description": "Fetch workspace usage metrics and quotas.",
        "doc_url": "https://elevenlabs.io/docs/api-reference/usage/character-stats",
        "method": "GET",
        "name": "usage_metrics",
        "path": "/v1/usage/character-stats",
        "safety": ("read",),
        "section": "Workspace",
        "status": "Implemented"},
    {   "cli_command": "tokens single-use create",
        "description": "Create a short-lived single-use token.",
        "doc_url": "https://elevenlabs.io/docs/api-reference/tokens/create",
        "method": "POST",
        "name": "tokens_single_use_create",
        "path": "/v1/single-use-token/{token_type}",
        "safety": ("write",),
        "section": "Tokens",
        "status": "Implemented",
        "sample_args": ("--token-type", "tts_websocket", "--body", "{}")},
    {   "cli_command": "service-accounts list",
        "description": "List workspace service accounts.",
        "doc_url": "https://elevenlabs.io/docs/api-reference/service-accounts/list",
        "method": "GET",
        "name": "service_accounts_list",
        "path": "/v1/service-accounts",
        "safety": ("read",),
        "section": "Service accounts",
        "status": "Implemented"},
    {   "cli_command": "service-accounts api-keys list",
        "description": "Enumerate API keys tied to a service account.",
        "doc_url": "https://elevenlabs.io/docs/api-reference/service-accounts/api-keys/list",
        "method": "GET",
        "name": "service_account_api_keys_list",
        "path": "/v1/service-accounts/{service_account_user_id}/api-keys",
        "safety": ("read",),
        "section": "Service accounts",
        "status": "Implemented"},
    {   "cli_command": "service-accounts api-keys create",
        "description": "Create a new API key for a service account.",
        "doc_url": "https://elevenlabs.io/docs/api-reference/service-accounts/api-keys/create",
        "method": "POST",
        "name": "service_account_api_keys_create",
        "path": "/v1/service-accounts/{service_account_user_id}/api-keys",
        "safety": ("write", "sensitive_output"),
        "section": "Service accounts",
        "status": "Implemented",
        "sample_args": (
            "--service-account-user-id",
            "svc-acc",
            "--body",
            '{"name":"api key"}',
            "--out",
            "api-key.json",
        )},
    {   "cli_command": "service-accounts api-keys delete",
        "description": "Delete an API key for a service account.",
        "doc_url": "https://elevenlabs.io/docs/api-reference/service-accounts/api-keys/delete",
        "method": "DELETE",
        "name": "service_account_api_keys_delete",
        "path": "/v1/service-accounts/{service_account_user_id}/api-keys/{api_key_id}",
        "safety": ("write", "irreversible"),
        "section": "Service accounts",
        "status": "Implemented",
        "sample_args": (
            "--service-account-user-id",
            "svc-acc",
            "--api-key-id",
            "key-1",
        )},
    {   "cli_command": "workspace resources share",
        "description": "Share a workspace resource with an identity.",
        "doc_url": "https://elevenlabs.io/docs/api-reference/workspace/resources/share",
        "method": "POST",
        "name": "workspace_share_resource",
        "path": "/v1/workspace/resources/{resource_id}/share",
        "safety": ("write",),
        "section": "Workspace",
        "status": "Implemented"},
    {   "cli_command": "workspace invites add",
        "description": "Invite a teammate into the workspace.",
        "doc_url": "https://elevenlabs.io/docs/api-reference/workspace/invite-user",
        "method": "POST",
        "name": "workspace_invite_user",
        "path": "/v1/workspace/invites/add",
        "safety": ("write",),
        "section": "Workspace",
        "status": "Implemented"},
    {   "cli_command": "workspace groups search",
        "description": "Search workspace user groups.",
        "doc_url": "https://elevenlabs.io/docs/api-reference/workspace/search-user-groups",
        "method": "GET",
        "name": "workspace_group_search",
        "path": "/v1/workspace/groups/search",
        "safety": ("read",),
        "section": "Workspace",
        "status": "Implemented",
        "sample_args": ("--param", "name=test")},
    {   "cli_command": "workspace webhooks list",
        "description": "List configured workspace webhooks.",
        "doc_url": "https://elevenlabs.io/docs/api-reference/webhooks/list",
        "method": "GET",
        "name": "webhooks_list",
        "path": "/v1/workspace/webhooks",
        "safety": ("read", "sensitive_output"),
        "section": "Webhooks",
        "status": "Implemented"},
    {   "cli_command": "workspace webhooks create",
        "description": "Create workspace webhook subscriptions.",
        "doc_url": "https://elevenlabs.io/docs/api-reference/webhooks/create",
        "method": "POST",
        "name": "webhooks_create",
        "path": "/v1/workspace/webhooks",
        "safety": ("write", "sensitive_output"),
        "section": "Webhooks",
        "status": "Implemented"},
    {   "cli_command": "workspace webhooks delete",
        "description": "Delete a workspace webhook subscription.",
        "doc_url": "https://elevenlabs.io/docs/api-reference/webhooks/delete",
        "method": "DELETE",
        "name": "webhooks_delete",
        "path": "/v1/workspace/webhooks/{webhook_id}",
        "safety": ("write", "irreversible", "sensitive_output"),
        "section": "Webhooks",
        "status": "Implemented",
        "sample_args": ("--webhook-id", "hook-1", "--out", "delete.json")},
    {   "cli_command": "convai agents list",
        "description": "List conversational agents and metadata.",
        "doc_url": "https://elevenlabs.io/docs/api-reference/agents/list",
        "method": "GET",
        "name": "agents_list",
        "path": "/v1/convai/agents",
        "safety": ("read",),
        "section": "Agents",
        "status": "Implemented"},
    {   "cli_command": "convai tools list",
        "description": "Enumerate tools available to agents.",
        "doc_url": "https://elevenlabs.io/docs/api-reference/tools/list",
        "method": "GET",
        "name": "tools_list",
        "path": "/v1/convai/tools",
        "safety": ("read",),
        "section": "Tools",
        "status": "Implemented"},
    {   "cli_command": "convai tools create",
        "description": "Create a tool for convai agents.",
        "doc_url": "https://elevenlabs.io/docs/api-reference/tools/create",
        "method": "POST",
        "name": "tools_create",
        "path": "/v1/convai/tools",
        "safety": ("write",),
        "section": "Tools",
        "status": "Implemented",
        "sample_args": (
            "--body",
            '{"tool_config":{"type":"client","name":"tool-1","description":"test tool","expects_response":false}}',
        )},
    {   "cli_command": "convai tools update",
        "description": "Update metadata for a convai tool.",
        "doc_url": "https://elevenlabs.io/docs/eleven-agents/api-reference/tools/update",
        "method": "PATCH",
        "name": "tools_update",
        "path": "/v1/convai/tools/{tool_id}",
        "safety": ("write",),
        "section": "Tools",
        "status": "Implemented",
        "sample_args": (
            "--tool-id",
            "tool-123",
            "--body",
            '{"tool_config":{"type":"client","name":"tool-123-updated","description":"updated test tool","expects_response":false}}',
        )},
    {   "cli_command": "convai tools delete",
        "description": "Delete a convai tool.",
        "doc_url": "https://elevenlabs.io/docs/eleven-agents/api-reference/tools/delete",
        "method": "DELETE",
        "name": "tools_delete",
        "path": "/v1/convai/tools/{tool_id}",
        "safety": ("write", "irreversible"),
        "section": "Tools",
        "status": "Implemented",
        "sample_args": ("--tool-id", "tool-123")},
    {   "cli_command": "convai knowledge-base list",
        "description": "List knowledge base documents.",
        "doc_url": "https://elevenlabs.io/docs/api-reference/knowledge-base/",
        "method": "GET",
        "name": "knowledge_base_list",
        "path": "/v1/convai/knowledge-base",
        "safety": ("read",),
        "section": "Knowledge base",
        "status": "Implemented"},
    {   "cli_command": "convai knowledge-base get-content",
        "description": "Fetch knowledge base document content.",
        "doc_url": "https://elevenlabs.io/docs/api-reference/knowledge-base/get-content",
        "method": "GET",
        "name": "knowledge_base_content",
        "path": "/v1/convai/knowledge-base/{documentation_id}/content",
        "safety": ("read", "sensitive_output"),
        "section": "Knowledge base",
        "status": "Implemented"},
    {   "cli_command": "convai conversations list",
        "description": "List agent conversations and metadata.",
        "doc_url": "https://elevenlabs.io/docs/api-reference/conversations/list",
        "method": "GET",
        "name": "conversations_list",
        "path": "/v1/convai/conversations",
        "safety": ("read", "sensitive_output"),
        "section": "Conversations",
        "status": "Implemented"},
    {   "cli_command": "convai conversations text-search",
        "description": "Text-search within collected conversations.",
        "doc_url": "https://elevenlabs.io/docs/api-reference/conversations/messages/text-search",
        "method": "GET",
        "name": "conversations_text_search",
        "path": "/v1/convai/conversations/messages/text-search",
        "safety": ("read", "sensitive_output"),
        "section": "Conversations",
        "status": "Implemented",
        "sample_args": ("--param", "text_query=test", "--out", "conversation-search.json")},
    {   "cli_command": "convai tests list",
        "description": "List conversational tests in the workspace.",
        "doc_url": "https://elevenlabs.io/docs/api-reference/tests/list",
        "method": "GET",
        "name": "tests_list",
        "path": "/v1/convai/agent-testing",
        "safety": ("read",),
        "section": "Tests",
        "status": "Implemented"},
    {   "cli_command": "convai tests invocations list",
        "description": "List recent test invocations.",
        "doc_url": "https://elevenlabs.io/docs/api-reference/tests/test-invocations/list",
        "method": "GET",
        "name": "test_invocations_list",
        "path": "/v1/convai/test-invocations",
        "safety": ("read",),
        "section": "Tests",
        "status": "Implemented",
        "sample_args": ("--param", "agent_id=agent-1")},
    {   "cli_command": "convai analytics live-count",
        "description": "Return the live conversation count summary.",
        "doc_url": "https://elevenlabs.io/docs/api-reference/analytics/live-count",
        "method": "GET",
        "name": "analytics_live_count",
        "path": "/v1/convai/analytics/live-count",
        "safety": ("read",),
        "section": "Analytics",
        "status": "Implemented"},
    {   "cli_command": "convai phone-numbers list",
        "description": "List Twilio/SIP numbers assigned to agents.",
        "doc_url": "https://elevenlabs.io/docs/api-reference/phone-numbers/list",
        "method": "GET",
        "name": "phone_numbers_list",
        "path": "/v1/convai/phone-numbers",
        "safety": ("read", "sensitive_output"),
        "section": "Phone numbers",
        "status": "Implemented"},
    {   "cli_command": "convai twilio register-call",
        "description": "Register a Twilio call for TwiML delivery.",
        "doc_url": "https://elevenlabs.io/docs/api-reference/twilio/register-call",
        "method": "POST",
        "name": "twilio_register_call",
        "path": "/v1/convai/twilio/register-call",
        "safety": ("write", "spend_money", "irreversible"),
        "section": "Twilio",
        "status": "Implemented"},
    {   "cli_command": "convai whatsapp outbound-call",
        "description": "Initiate an outbound WhatsApp call.",
        "doc_url": "https://elevenlabs.io/docs/eleven-agents/api-reference/whats-app/outbound-call",
        "method": "POST",
        "name": "whatsapp_outbound_call",
        "path": "/v1/convai/whatsapp/outbound-call",
        "safety": ("write", "spend_money", "irreversible"),
        "section": "WhatsApp",
        "status": "Implemented"},
    {   "cli_command": "convai batch-calling submit",
        "description": "Submit multiple outbound calls as a batch.",
        "doc_url": "https://elevenlabs.io/docs/api-reference/batch-calling/create",
        "method": "POST",
        "name": "batch_calling_submit",
        "path": "/v1/convai/batch-calling/submit",
        "safety": ("write", "spend_money", "irreversible"),
        "section": "Batch calling",
        "status": "Implemented"},
    {   "cli_command": "convai mcp-servers list",
        "description": "List Model Context Protocol server configs.",
        "doc_url": "https://elevenlabs.io/docs/api-reference/mcp/list",
        "method": "GET",
        "name": "mcp_servers_list",
        "path": "/v1/convai/mcp-servers",
        "safety": ("read",),
        "section": "MCP servers",
        "status": "Implemented"},
    {   "cli_command": "convai llm-usage calculate",
        "description": "Estimate LLM pricing for prompts.",
        "doc_url": "https://elevenlabs.io/docs/api-reference/llm-usage/calculate",
        "method": "POST",
        "name": "llm_usage_calculate",
        "path": "/v1/convai/llm-usage/calculate",
        "safety": ("read", "post_read"),
        "section": "LLM usage",
        "status": "Implemented",
        "sample_args": (
            "--body",
            '{"prompt_length":100,"number_of_pages":1,"rag_enabled":false}',
        )},
    {   "cli_command": "audio-native create",
        "description": "Create an embeddable Audio Native project.",
        "doc_url": "https://elevenlabs.io/docs/api-reference/audio-native/create",
        "method": "POST",
        "name": "audio_native_create",
        "path": "/v1/audio-native",
        "safety": ("write", "binary_output"),
        "section": "Audio native",
        "status": "Implemented"},
    {   "cli_command": "audio-native settings get",
        "description": "Fetch Audio Native project settings.",
        "doc_url": "https://elevenlabs.io/docs/api-reference/audio-native/get-settings",
        "method": "GET",
        "name": "audio_native_settings",
        "path": "/v1/audio-native/{project_id}/settings",
        "safety": ("read",),
        "section": "Audio native",
        "status": "Implemented"},
    {   "description": "Document how to store API keys and env vars.",
        "doc_url": "https://elevenlabs.io/docs/api-reference/authentication",
        "method": "DOC",
        "name": "environment_variables_doc",
        "path": "https://elevenlabs.io/docs/api-reference/authentication",
        "safety": ("read",),
        "section": "Authentication",
        "status": "Docs-only"}]

INVENTORY: tuple[InventoryEntry, ...] = tuple(InventoryEntry(**entry) for entry in inventory_data)



def _operation_from_entry(entry: InventoryEntry) -> Operation:
    if not entry.cli_command:
        raise ValueError(f"Inventory entry '{entry.name}' has no CLI command")
    sample_args = entry.sample_args or _default_sample_args(entry)
    return Operation(
        name=entry.name,
        section=entry.section,
        description=entry.description,
        method=entry.method,
        path=entry.path,
        cli_command=entry.cli_command,
        safety=entry.safety,
        doc_url=entry.doc_url,
        sample_args=sample_args,
    )


OPERATIONS: tuple[Operation, ...] = tuple(
    _operation_from_entry(entry) for entry in INVENTORY if entry.status.lower().startswith("impl")
)
