from __future__ import annotations

import dataclasses


@dataclasses.dataclass(frozen=True)
class Operation:
    rpc: str
    domain: str
    service: str
    method: str
    http_verb: str
    http_path: str
    path_params: tuple[tuple[str, str], ...]
    command_name: str


INVENTORY_VERSION = 'v1'
INVENTORY_OPERATION_COUNT = 118

OPERATIONS: tuple[Operation, ...] = (
    Operation(rpc='qdrant.cloud.account.v1.AccountService.AcceptAccountInvite', domain='account-v1', service='AccountService', method='AcceptAccountInvite', http_verb='POST', http_path='/api/account/v1/accounts/{account_id}/invites/{invite_id}/accept', path_params=(('account_id', 'account_id'), ('invite_id', 'invite_id')), command_name='accept-account-invite'),
    Operation(rpc='qdrant.cloud.account.v1.AccountService.CreateAccount', domain='account-v1', service='AccountService', method='CreateAccount', http_verb='POST', http_path='/api/account/v1/accounts', path_params=(), command_name='create-account'),
    Operation(rpc='qdrant.cloud.account.v1.AccountService.CreateAccountInvite', domain='account-v1', service='AccountService', method='CreateAccountInvite', http_verb='POST', http_path='/api/account/v1/accounts/{account_invite.account_id}/invites', path_params=(('account_invite.account_id', 'account_invite_account_id'),), command_name='create-account-invite'),
    Operation(rpc='qdrant.cloud.account.v1.AccountService.DeleteAccount', domain='account-v1', service='AccountService', method='DeleteAccount', http_verb='DELETE', http_path='/api/account/v1/accounts/{account_id}', path_params=(('account_id', 'account_id'),), command_name='delete-account'),
    Operation(rpc='qdrant.cloud.account.v1.AccountService.DeleteAccountInvite', domain='account-v1', service='AccountService', method='DeleteAccountInvite', http_verb='DELETE', http_path='/api/account/v1/accounts/{account_id}/invites/{invite_id}', path_params=(('account_id', 'account_id'), ('invite_id', 'invite_id')), command_name='delete-account-invite'),
    Operation(rpc='qdrant.cloud.account.v1.AccountService.DeleteAccountMember', domain='account-v1', service='AccountService', method='DeleteAccountMember', http_verb='DELETE', http_path='/api/account/v1/accounts/{account_id}/members/{user_id}', path_params=(('account_id', 'account_id'), ('user_id', 'user_id')), command_name='delete-account-member'),
    Operation(rpc='qdrant.cloud.account.v1.AccountService.GetAccount', domain='account-v1', service='AccountService', method='GetAccount', http_verb='GET', http_path='/api/account/v1/accounts/{account_id}', path_params=(('account_id', 'account_id'),), command_name='get-account'),
    Operation(rpc='qdrant.cloud.account.v1.AccountService.GetAccountInvite', domain='account-v1', service='AccountService', method='GetAccountInvite', http_verb='GET', http_path='/api/account/v1/accounts/{account_id}/invites/{invite_id}', path_params=(('account_id', 'account_id'), ('invite_id', 'invite_id')), command_name='get-account-invite'),
    Operation(rpc='qdrant.cloud.account.v1.AccountService.GetAccountMember', domain='account-v1', service='AccountService', method='GetAccountMember', http_verb='GET', http_path='/api/account/v1/accounts/{account_id}/members/{user_id}', path_params=(('account_id', 'account_id'), ('user_id', 'user_id')), command_name='get-account-member'),
    Operation(rpc='qdrant.cloud.account.v1.AccountService.LeaveAccount', domain='account-v1', service='AccountService', method='LeaveAccount', http_verb='POST', http_path='/api/account/v1/accounts/{account_id}/leave', path_params=(('account_id', 'account_id'),), command_name='leave-account'),
    Operation(rpc='qdrant.cloud.account.v1.AccountService.ListAccountInvites', domain='account-v1', service='AccountService', method='ListAccountInvites', http_verb='GET', http_path='/api/account/v1/accounts/{account_id}/invites', path_params=(('account_id', 'account_id'),), command_name='list-account-invites'),
    Operation(rpc='qdrant.cloud.account.v1.AccountService.ListAccountMembers', domain='account-v1', service='AccountService', method='ListAccountMembers', http_verb='GET', http_path='/api/account/v1/accounts/{account_id}/members', path_params=(('account_id', 'account_id'),), command_name='list-account-members'),
    Operation(rpc='qdrant.cloud.account.v1.AccountService.ListAccounts', domain='account-v1', service='AccountService', method='ListAccounts', http_verb='GET', http_path='/api/account/v1/accounts', path_params=(), command_name='list-accounts'),
    Operation(rpc='qdrant.cloud.account.v1.AccountService.ListReceivedAccountInvites', domain='account-v1', service='AccountService', method='ListReceivedAccountInvites', http_verb='GET', http_path='/api/account/v1/self/invites', path_params=(), command_name='list-received-account-invites'),
    Operation(rpc='qdrant.cloud.account.v1.AccountService.RejectAccountInvite', domain='account-v1', service='AccountService', method='RejectAccountInvite', http_verb='POST', http_path='/api/account/v1/accounts/{account_id}/invites/{invite_id}/reject', path_params=(('account_id', 'account_id'), ('invite_id', 'invite_id')), command_name='reject-account-invite'),
    Operation(rpc='qdrant.cloud.account.v1.AccountService.SuggestCompanies', domain='account-v1', service='AccountService', method='SuggestCompanies', http_verb='GET', http_path='/api/account/v1/suggest-company', path_params=(), command_name='suggest-companies'),
    Operation(rpc='qdrant.cloud.account.v1.AccountService.UpdateAccount', domain='account-v1', service='AccountService', method='UpdateAccount', http_verb='PUT', http_path='/api/account/v1/accounts/{account.id}', path_params=(('account.id', 'account_id'),), command_name='update-account'),
    Operation(rpc='qdrant.cloud.auth.v1.AuthService.CreateManagementKey', domain='auth-v1', service='AuthService', method='CreateManagementKey', http_verb='POST', http_path='/api/auth/v1/accounts/{management_key.account_id}/management-keys', path_params=(('management_key.account_id', 'management_key_account_id'),), command_name='create-management-key'),
    Operation(rpc='qdrant.cloud.auth.v1.AuthService.DeleteManagementKey', domain='auth-v1', service='AuthService', method='DeleteManagementKey', http_verb='DELETE', http_path='/api/auth/v1/accounts/{account_id}/management-keys/{management_key_id}', path_params=(('account_id', 'account_id'), ('management_key_id', 'management_key_id')), command_name='delete-management-key'),
    Operation(rpc='qdrant.cloud.auth.v1.AuthService.ListManagementKeys', domain='auth-v1', service='AuthService', method='ListManagementKeys', http_verb='GET', http_path='/api/auth/v1/accounts/{account_id}/management-keys', path_params=(('account_id', 'account_id'),), command_name='list-management-keys'),
    Operation(rpc='qdrant.cloud.billing.v1.BillingService.ListDiscounts', domain='billing-v1', service='BillingService', method='ListDiscounts', http_verb='GET', http_path='/api/billing/v1/accounts/{account_id}/discounts', path_params=(('account_id', 'account_id'),), command_name='list-discounts'),
    Operation(rpc='qdrant.cloud.billing.v1.BillingService.ListInvoices', domain='billing-v1', service='BillingService', method='ListInvoices', http_verb='GET', http_path='/api/billing/v1/accounts/{account_id}/invoices', path_params=(('account_id', 'account_id'),), command_name='list-invoices'),
    Operation(rpc='qdrant.cloud.booking.v1.BookingService.GetBackupQuote', domain='booking-v1', service='BookingService', method='GetBackupQuote', http_verb='POST', http_path='/api/booking/v1/accounts/{account_id}/backup-quote', path_params=(('account_id', 'account_id'),), command_name='get-backup-quote'),
    Operation(rpc='qdrant.cloud.booking.v1.BookingService.GetPackage', domain='booking-v1', service='BookingService', method='GetPackage', http_verb='GET', http_path='/api/booking/v1/accounts/{account_id}/packages/{id}', path_params=(('account_id', 'account_id'), ('id', 'id')), command_name='get-package'),
    Operation(rpc='qdrant.cloud.booking.v1.BookingService.GetQuote', domain='booking-v1', service='BookingService', method='GetQuote', http_verb='POST', http_path='/api/booking/v1/accounts/{account_id}/quote', path_params=(('account_id', 'account_id'),), command_name='get-quote'),
    Operation(rpc='qdrant.cloud.booking.v1.BookingService.ListGlobalPackages', domain='booking-v1', service='BookingService', method='ListGlobalPackages', http_verb='GET', http_path='/api/booking/v1/packages', path_params=(), command_name='list-global-packages'),
    Operation(rpc='qdrant.cloud.booking.v1.BookingService.ListInferenceModels', domain='booking-v1', service='BookingService', method='ListInferenceModels', http_verb='GET', http_path='/api/booking/v1/accounts/{account_id}/inference-models', path_params=(('account_id', 'account_id'),), command_name='list-inference-models'),
    Operation(rpc='qdrant.cloud.booking.v1.BookingService.ListPackages', domain='booking-v1', service='BookingService', method='ListPackages', http_verb='GET', http_path='/api/booking/v1/accounts/{account_id}/packages', path_params=(('account_id', 'account_id'),), command_name='list-packages'),
    Operation(rpc='qdrant.cloud.booking.v1.BookingService.ListStorageTierTypes', domain='booking-v1', service='BookingService', method='ListStorageTierTypes', http_verb='GET', http_path='/api/booking/v1/accounts/{account_id}/storage-tiers', path_params=(('account_id', 'account_id'),), command_name='list-storage-tier-types'),
    Operation(rpc='qdrant.cloud.cluster.auth.v1.DatabaseApiKeyService.CreateDatabaseApiKey', domain='cluster-auth-v1', service='DatabaseApiKeyService', method='CreateDatabaseApiKey', http_verb='POST', http_path='/api/cluster/auth/v1/accounts/{database_api_key.account_id}/database-api-keys', path_params=(('database_api_key.account_id', 'database_api_key_account_id'),), command_name='create-database-api-key'),
    Operation(rpc='qdrant.cloud.cluster.auth.v1.DatabaseApiKeyService.DeleteDatabaseApiKey', domain='cluster-auth-v1', service='DatabaseApiKeyService', method='DeleteDatabaseApiKey', http_verb='DELETE', http_path='/api/cluster/auth/v1/accounts/{account_id}/database-api-keys/{database_api_key_id}', path_params=(('account_id', 'account_id'), ('database_api_key_id', 'database_api_key_id')), command_name='delete-database-api-key'),
    Operation(rpc='qdrant.cloud.cluster.auth.v1.DatabaseApiKeyService.ListDatabaseApiKeys', domain='cluster-auth-v1', service='DatabaseApiKeyService', method='ListDatabaseApiKeys', http_verb='GET', http_path='/api/cluster/auth/v1/accounts/{account_id}/database-api-keys', path_params=(('account_id', 'account_id'),), command_name='list-database-api-keys'),
    Operation(rpc='qdrant.cloud.cluster.auth.v1.EphemeralDashboardTokenService.CreateEphemeralDashboardToken', domain='cluster-auth-v1', service='EphemeralDashboardTokenService', method='CreateEphemeralDashboardToken', http_verb='POST', http_path='/api/cluster/auth/v1/accounts/{account_id}/ephemeral-dashboard-tokens', path_params=(('account_id', 'account_id'),), command_name='create-ephemeral-dashboard-token'),
    Operation(rpc='qdrant.cloud.cluster.auth.v2.DatabaseApiKeyService.CreateDatabaseApiKey', domain='cluster-auth-v2', service='DatabaseApiKeyService', method='CreateDatabaseApiKey', http_verb='POST', http_path='/api/cluster/auth/v2/accounts/{database_api_key.account_id}/database-api-keys', path_params=(('database_api_key.account_id', 'database_api_key_account_id'),), command_name='create-database-api-key'),
    Operation(rpc='qdrant.cloud.cluster.auth.v2.DatabaseApiKeyService.DeleteDatabaseApiKey', domain='cluster-auth-v2', service='DatabaseApiKeyService', method='DeleteDatabaseApiKey', http_verb='DELETE', http_path='/api/cluster/auth/v2/accounts/{account_id}/database-api-keys/{database_api_key_id}', path_params=(('account_id', 'account_id'), ('database_api_key_id', 'database_api_key_id')), command_name='delete-database-api-key'),
    Operation(rpc='qdrant.cloud.cluster.auth.v2.DatabaseApiKeyService.ListDatabaseApiKeys', domain='cluster-auth-v2', service='DatabaseApiKeyService', method='ListDatabaseApiKeys', http_verb='GET', http_path='/api/cluster/auth/v2/accounts/{account_id}/database-api-keys', path_params=(('account_id', 'account_id'),), command_name='list-database-api-keys'),
    Operation(rpc='qdrant.cloud.cluster.backup.v1.BackupService.CreateBackup', domain='cluster-backup-v1', service='BackupService', method='CreateBackup', http_verb='POST', http_path='/api/cluster/backup/v1/accounts/{backup.account_id}/backups', path_params=(('backup.account_id', 'backup_account_id'),), command_name='create-backup'),
    Operation(rpc='qdrant.cloud.cluster.backup.v1.BackupService.CreateBackupSchedule', domain='cluster-backup-v1', service='BackupService', method='CreateBackupSchedule', http_verb='POST', http_path='/api/cluster/backup/v1/accounts/{backup_schedule.account_id}/backup_schedules', path_params=(('backup_schedule.account_id', 'backup_schedule_account_id'),), command_name='create-backup-schedule'),
    Operation(rpc='qdrant.cloud.cluster.backup.v1.BackupService.DeleteBackup', domain='cluster-backup-v1', service='BackupService', method='DeleteBackup', http_verb='DELETE', http_path='/api/cluster/backup/v1/accounts/{account_id}/backups/{backup_id}', path_params=(('account_id', 'account_id'), ('backup_id', 'backup_id')), command_name='delete-backup'),
    Operation(rpc='qdrant.cloud.cluster.backup.v1.BackupService.DeleteBackupSchedule', domain='cluster-backup-v1', service='BackupService', method='DeleteBackupSchedule', http_verb='DELETE', http_path='/api/cluster/backup/v1/accounts/{account_id}/backup_schedules/{backup_schedule_id}', path_params=(('account_id', 'account_id'), ('backup_schedule_id', 'backup_schedule_id')), command_name='delete-backup-schedule'),
    Operation(rpc='qdrant.cloud.cluster.backup.v1.BackupService.GetBackup', domain='cluster-backup-v1', service='BackupService', method='GetBackup', http_verb='GET', http_path='/api/cluster/backup/v1/accounts/{account_id}/backups/{backup_id}', path_params=(('account_id', 'account_id'), ('backup_id', 'backup_id')), command_name='get-backup'),
    Operation(rpc='qdrant.cloud.cluster.backup.v1.BackupService.GetBackupSchedule', domain='cluster-backup-v1', service='BackupService', method='GetBackupSchedule', http_verb='GET', http_path='/api/cluster/backup/v1/accounts/{account_id}/backup_schedules/{backup_schedule_id}', path_params=(('account_id', 'account_id'), ('backup_schedule_id', 'backup_schedule_id')), command_name='get-backup-schedule'),
    Operation(rpc='qdrant.cloud.cluster.backup.v1.BackupService.ListBackupRestores', domain='cluster-backup-v1', service='BackupService', method='ListBackupRestores', http_verb='GET', http_path='/api/cluster/backup/v1/accounts/{account_id}/backup_restores', path_params=(('account_id', 'account_id'),), command_name='list-backup-restores'),
    Operation(rpc='qdrant.cloud.cluster.backup.v1.BackupService.ListBackupSchedules', domain='cluster-backup-v1', service='BackupService', method='ListBackupSchedules', http_verb='GET', http_path='/api/cluster/backup/v1/accounts/{account_id}/backup_schedules', path_params=(('account_id', 'account_id'),), command_name='list-backup-schedules'),
    Operation(rpc='qdrant.cloud.cluster.backup.v1.BackupService.ListBackups', domain='cluster-backup-v1', service='BackupService', method='ListBackups', http_verb='GET', http_path='/api/cluster/backup/v1/accounts/{account_id}/backups', path_params=(('account_id', 'account_id'),), command_name='list-backups'),
    Operation(rpc='qdrant.cloud.cluster.backup.v1.BackupService.RestoreBackup', domain='cluster-backup-v1', service='BackupService', method='RestoreBackup', http_verb='POST', http_path='/api/cluster/backup/v1/accounts/{account_id}/backups/{backup_id}/restore', path_params=(('account_id', 'account_id'), ('backup_id', 'backup_id')), command_name='restore-backup'),
    Operation(rpc='qdrant.cloud.cluster.backup.v1.BackupService.UpdateBackupSchedule', domain='cluster-backup-v1', service='BackupService', method='UpdateBackupSchedule', http_verb='PUT', http_path='/api/cluster/backup/v1/accounts/{backup_schedule.account_id}/backup_schedules/{backup_schedule.id}', path_params=(('backup_schedule.account_id', 'backup_schedule_account_id'), ('backup_schedule.id', 'backup_schedule_id')), command_name='update-backup-schedule'),
    Operation(rpc='qdrant.cloud.cluster.v1.ClusterService.CreateCluster', domain='cluster-v1', service='ClusterService', method='CreateCluster', http_verb='POST', http_path='/api/cluster/v1/accounts/{cluster.account_id}/clusters', path_params=(('cluster.account_id', 'cluster_account_id'),), command_name='create-cluster'),
    Operation(rpc='qdrant.cloud.cluster.v1.ClusterService.CreateClusterFromBackup', domain='cluster-v1', service='ClusterService', method='CreateClusterFromBackup', http_verb='POST', http_path='/api/cluster/v1/accounts/{account_id}/backups/{backup_id}/clusters', path_params=(('account_id', 'account_id'), ('backup_id', 'backup_id')), command_name='create-cluster-from-backup'),
    Operation(rpc='qdrant.cloud.cluster.v1.ClusterService.DeleteCluster', domain='cluster-v1', service='ClusterService', method='DeleteCluster', http_verb='DELETE', http_path='/api/cluster/v1/accounts/{account_id}/clusters/{cluster_id}', path_params=(('account_id', 'account_id'), ('cluster_id', 'cluster_id')), command_name='delete-cluster'),
    Operation(rpc='qdrant.cloud.cluster.v1.ClusterService.EnableClusterJwtRbac', domain='cluster-v1', service='ClusterService', method='EnableClusterJwtRbac', http_verb='POST', http_path='/api/cluster/v1/accounts/{account_id}/clusters/{cluster_id}/enable-jwt', path_params=(('account_id', 'account_id'), ('cluster_id', 'cluster_id')), command_name='enable-cluster-jwt-rbac'),
    Operation(rpc='qdrant.cloud.cluster.v1.ClusterService.GetCluster', domain='cluster-v1', service='ClusterService', method='GetCluster', http_verb='GET', http_path='/api/cluster/v1/accounts/{account_id}/clusters/{cluster_id}', path_params=(('account_id', 'account_id'), ('cluster_id', 'cluster_id')), command_name='get-cluster'),
    Operation(rpc='qdrant.cloud.cluster.v1.ClusterService.GetQdrantRelease', domain='cluster-v1', service='ClusterService', method='GetQdrantRelease', http_verb='GET', http_path='/api/cluster/v1/accounts/{account_id}/releases/{version}', path_params=(('account_id', 'account_id'), ('version', 'version')), command_name='get-qdrant-release'),
    Operation(rpc='qdrant.cloud.cluster.v1.ClusterService.ListClusters', domain='cluster-v1', service='ClusterService', method='ListClusters', http_verb='GET', http_path='/api/cluster/v1/accounts/{account_id}/clusters', path_params=(('account_id', 'account_id'),), command_name='list-clusters'),
    Operation(rpc='qdrant.cloud.cluster.v1.ClusterService.ListQdrantReleases', domain='cluster-v1', service='ClusterService', method='ListQdrantReleases', http_verb='GET', http_path='/api/cluster/v1/accounts/{account_id}/releases', path_params=(('account_id', 'account_id'),), command_name='list-qdrant-releases'),
    Operation(rpc='qdrant.cloud.cluster.v1.ClusterService.RestartCluster', domain='cluster-v1', service='ClusterService', method='RestartCluster', http_verb='POST', http_path='/api/cluster/v1/accounts/{account_id}/clusters/{cluster_id}/restart', path_params=(('account_id', 'account_id'), ('cluster_id', 'cluster_id')), command_name='restart-cluster'),
    Operation(rpc='qdrant.cloud.cluster.v1.ClusterService.SuggestClusterName', domain='cluster-v1', service='ClusterService', method='SuggestClusterName', http_verb='GET', http_path='/api/cluster/v1/accounts/{account_id}/clusters/suggest-name', path_params=(('account_id', 'account_id'),), command_name='suggest-cluster-name'),
    Operation(rpc='qdrant.cloud.cluster.v1.ClusterService.SuspendCluster', domain='cluster-v1', service='ClusterService', method='SuspendCluster', http_verb='POST', http_path='/api/cluster/v1/accounts/{account_id}/clusters/{cluster_id}/suspend', path_params=(('account_id', 'account_id'), ('cluster_id', 'cluster_id')), command_name='suspend-cluster'),
    Operation(rpc='qdrant.cloud.cluster.v1.ClusterService.UnsuspendCluster', domain='cluster-v1', service='ClusterService', method='UnsuspendCluster', http_verb='POST', http_path='/api/cluster/v1/accounts/{account_id}/clusters/{cluster_id}/unsuspend', path_params=(('account_id', 'account_id'), ('cluster_id', 'cluster_id')), command_name='unsuspend-cluster'),
    Operation(rpc='qdrant.cloud.cluster.v1.ClusterService.UpdateCluster', domain='cluster-v1', service='ClusterService', method='UpdateCluster', http_verb='PUT', http_path='/api/cluster/v1/accounts/{cluster.account_id}/clusters/{cluster.id}', path_params=(('cluster.account_id', 'cluster_account_id'), ('cluster.id', 'cluster_id')), command_name='update-cluster'),
    Operation(rpc='qdrant.cloud.hybrid.v1.HybridCloudService.CreateHybridCloudEnvironment', domain='hybrid-v1', service='HybridCloudService', method='CreateHybridCloudEnvironment', http_verb='POST', http_path='/api/hybrid/v1/accounts/{hybrid_cloud_environment.account_id}/hybrid-cloud-environments', path_params=(('hybrid_cloud_environment.account_id', 'hybrid_cloud_environment_account_id'),), command_name='create-hybrid-cloud-environment'),
    Operation(rpc='qdrant.cloud.hybrid.v1.HybridCloudService.DeleteHybridCloudEnvironment', domain='hybrid-v1', service='HybridCloudService', method='DeleteHybridCloudEnvironment', http_verb='DELETE', http_path='/api/hybrid/v1/accounts/{account_id}/hybrid-cloud-environments/{hybrid_cloud_environment_id}', path_params=(('account_id', 'account_id'), ('hybrid_cloud_environment_id', 'hybrid_cloud_environment_id')), command_name='delete-hybrid-cloud-environment'),
    Operation(rpc='qdrant.cloud.hybrid.v1.HybridCloudService.GenerateBootstrapCommands', domain='hybrid-v1', service='HybridCloudService', method='GenerateBootstrapCommands', http_verb='POST', http_path='/api/hybrid/v1/accounts/{account_id}/hybrid-cloud-environments/{hybrid_cloud_environment_id}/bootstrap-commands', path_params=(('account_id', 'account_id'), ('hybrid_cloud_environment_id', 'hybrid_cloud_environment_id')), command_name='generate-bootstrap-commands'),
    Operation(rpc='qdrant.cloud.hybrid.v1.HybridCloudService.GetHybridCloudEnvironment', domain='hybrid-v1', service='HybridCloudService', method='GetHybridCloudEnvironment', http_verb='GET', http_path='/api/hybrid/v1/accounts/{account_id}/hybrid-cloud-environments/{hybrid_cloud_environment_id}', path_params=(('account_id', 'account_id'), ('hybrid_cloud_environment_id', 'hybrid_cloud_environment_id')), command_name='get-hybrid-cloud-environment'),
    Operation(rpc='qdrant.cloud.hybrid.v1.HybridCloudService.ListHybridCloudEnvironments', domain='hybrid-v1', service='HybridCloudService', method='ListHybridCloudEnvironments', http_verb='GET', http_path='/api/hybrid/v1/accounts/{account_id}/hybrid-cloud-environments', path_params=(('account_id', 'account_id'),), command_name='list-hybrid-cloud-environments'),
    Operation(rpc='qdrant.cloud.hybrid.v1.HybridCloudService.UpdateHybridCloudEnvironment', domain='hybrid-v1', service='HybridCloudService', method='UpdateHybridCloudEnvironment', http_verb='PUT', http_path='/api/hybrid/v1/accounts/{hybrid_cloud_environment.account_id}/hybrid-cloud-environments/{hybrid_cloud_environment.id}', path_params=(('hybrid_cloud_environment.account_id', 'hybrid_cloud_environment_account_id'), ('hybrid_cloud_environment.id', 'hybrid_cloud_environment_id')), command_name='update-hybrid-cloud-environment'),
    Operation(rpc='qdrant.cloud.iam.v1.IAMService.AssignUserRoles', domain='iam-v1', service='IAMService', method='AssignUserRoles', http_verb='POST', http_path='/api/iam/v1/accounts/{account_id}/users/{user_id}/roles', path_params=(('account_id', 'account_id'), ('user_id', 'user_id')), command_name='assign-user-roles'),
    Operation(rpc='qdrant.cloud.iam.v1.IAMService.CreateRole', domain='iam-v1', service='IAMService', method='CreateRole', http_verb='POST', http_path='/api/iam/v1/accounts/{role.account_id}/roles', path_params=(('role.account_id', 'role_account_id'),), command_name='create-role'),
    Operation(rpc='qdrant.cloud.iam.v1.IAMService.DeleteRole', domain='iam-v1', service='IAMService', method='DeleteRole', http_verb='DELETE', http_path='/api/iam/v1/accounts/{account_id}/roles/{role_id}', path_params=(('account_id', 'account_id'), ('role_id', 'role_id')), command_name='delete-role'),
    Operation(rpc='qdrant.cloud.iam.v1.IAMService.GetAuthenticatedUser', domain='iam-v1', service='IAMService', method='GetAuthenticatedUser', http_verb='GET', http_path='/api/iam/v1/users/me', path_params=(), command_name='get-authenticated-user'),
    Operation(rpc='qdrant.cloud.iam.v1.IAMService.GetRole', domain='iam-v1', service='IAMService', method='GetRole', http_verb='GET', http_path='/api/iam/v1/accounts/{account_id}/roles/{role_id}', path_params=(('account_id', 'account_id'), ('role_id', 'role_id')), command_name='get-role'),
    Operation(rpc='qdrant.cloud.iam.v1.IAMService.GetUserConsent', domain='iam-v1', service='IAMService', method='GetUserConsent', http_verb='GET', http_path='/api/iam/v1/users/me/consent', path_params=(), command_name='get-user-consent'),
    Operation(rpc='qdrant.cloud.iam.v1.IAMService.GetUserProfile', domain='iam-v1', service='IAMService', method='GetUserProfile', http_verb='GET', http_path='/api/iam/v1/users/me/profile', path_params=(), command_name='get-user-profile'),
    Operation(rpc='qdrant.cloud.iam.v1.IAMService.ListEffectivePermissions', domain='iam-v1', service='IAMService', method='ListEffectivePermissions', http_verb='GET', http_path='/api/iam/v1/accounts/{account_id}/effective-permissions', path_params=(('account_id', 'account_id'),), command_name='list-effective-permissions'),
    Operation(rpc='qdrant.cloud.iam.v1.IAMService.ListPermissions', domain='iam-v1', service='IAMService', method='ListPermissions', http_verb='GET', http_path='/api/iam/v1/accounts/{account_id}/permissions', path_params=(('account_id', 'account_id'),), command_name='list-permissions'),
    Operation(rpc='qdrant.cloud.iam.v1.IAMService.ListRoleUsers', domain='iam-v1', service='IAMService', method='ListRoleUsers', http_verb='GET', http_path='/api/iam/v1/accounts/{account_id}/roles/{role_id}/users', path_params=(('account_id', 'account_id'), ('role_id', 'role_id')), command_name='list-role-users'),
    Operation(rpc='qdrant.cloud.iam.v1.IAMService.ListRoles', domain='iam-v1', service='IAMService', method='ListRoles', http_verb='GET', http_path='/api/iam/v1/accounts/{account_id}/roles', path_params=(('account_id', 'account_id'),), command_name='list-roles'),
    Operation(rpc='qdrant.cloud.iam.v1.IAMService.ListUserRoles', domain='iam-v1', service='IAMService', method='ListUserRoles', http_verb='GET', http_path='/api/iam/v1/accounts/{account_id}/users/{user_id}/roles', path_params=(('account_id', 'account_id'), ('user_id', 'user_id')), command_name='list-user-roles'),
    Operation(rpc='qdrant.cloud.iam.v1.IAMService.ListUsers', domain='iam-v1', service='IAMService', method='ListUsers', http_verb='GET', http_path='/api/iam/v1/accounts/{account_id}/users', path_params=(('account_id', 'account_id'),), command_name='list-users'),
    Operation(rpc='qdrant.cloud.iam.v1.IAMService.LogoutUser', domain='iam-v1', service='IAMService', method='LogoutUser', http_verb='POST', http_path='/api/iam/v1/users/me/logout', path_params=(), command_name='logout-user'),
    Operation(rpc='qdrant.cloud.iam.v1.IAMService.RecordUserConsent', domain='iam-v1', service='IAMService', method='RecordUserConsent', http_verb='POST', http_path='/api/iam/v1/users/me/consent', path_params=(), command_name='record-user-consent'),
    Operation(rpc='qdrant.cloud.iam.v1.IAMService.UpdateRole', domain='iam-v1', service='IAMService', method='UpdateRole', http_verb='PUT', http_path='/api/iam/v1/accounts/{role.account_id}/roles/{role.id}', path_params=(('role.account_id', 'role_account_id'), ('role.id', 'role_id')), command_name='update-role'),
    Operation(rpc='qdrant.cloud.iam.v1.IAMService.UpdateUser', domain='iam-v1', service='IAMService', method='UpdateUser', http_verb='PUT', http_path='/api/iam/v1/users/{user.id}', path_params=(('user.id', 'user_id'),), command_name='update-user'),
    Operation(rpc='qdrant.cloud.iam.v1.IAMService.UpdateUserProfile', domain='iam-v1', service='IAMService', method='UpdateUserProfile', http_verb='PUT', http_path='/api/iam/v1/users/me/profile', path_params=(), command_name='update-user-profile'),
    Operation(rpc='qdrant.cloud.metering.v1.MeteringService.ListMeterings', domain='metering-v1', service='MeteringService', method='ListMeterings', http_verb='GET', http_path='/api/metering/v1/accounts/{account_id}/meterings/{year}/{month}', path_params=(('account_id', 'account_id'), ('year', 'year'), ('month', 'month')), command_name='list-meterings'),
    Operation(rpc='qdrant.cloud.metering.v1.MeteringService.ListMonthlyMeterings', domain='metering-v1', service='MeteringService', method='ListMonthlyMeterings', http_verb='GET', http_path='/api/metering/v1/accounts/{account_id}/meterings', path_params=(('account_id', 'account_id'),), command_name='list-monthly-meterings'),
    Operation(rpc='qdrant.cloud.monitoring.v1.MonitoringService.GetClusterEvents', domain='monitoring-v1', service='MonitoringService', method='GetClusterEvents', http_verb='GET', http_path='/api/monitoring/v1/accounts/{account_id}/cluster/{cluster_id}/events', path_params=(('account_id', 'account_id'), ('cluster_id', 'cluster_id')), command_name='get-cluster-events'),
    Operation(rpc='qdrant.cloud.monitoring.v1.MonitoringService.GetClusterInferenceMetrics', domain='monitoring-v1', service='MonitoringService', method='GetClusterInferenceMetrics', http_verb='GET', http_path='/api/monitoring/v1/accounts/{account_id}/cluster/{cluster_id}/metrics/inference', path_params=(('account_id', 'account_id'), ('cluster_id', 'cluster_id')), command_name='get-cluster-inference-metrics'),
    Operation(rpc='qdrant.cloud.monitoring.v1.MonitoringService.GetClusterLogs', domain='monitoring-v1', service='MonitoringService', method='GetClusterLogs', http_verb='GET', http_path='/api/monitoring/v1/accounts/{account_id}/cluster/{cluster_id}/logs', path_params=(('account_id', 'account_id'), ('cluster_id', 'cluster_id')), command_name='get-cluster-logs'),
    Operation(rpc='qdrant.cloud.monitoring.v1.MonitoringService.GetClusterSummaryMetrics', domain='monitoring-v1', service='MonitoringService', method='GetClusterSummaryMetrics', http_verb='GET', http_path='/api/monitoring/v1/accounts/{account_id}/cluster/{cluster_id}/summary-metrics', path_params=(('account_id', 'account_id'), ('cluster_id', 'cluster_id')), command_name='get-cluster-summary-metrics'),
    Operation(rpc='qdrant.cloud.monitoring.v1.MonitoringService.GetClusterUsageMetrics', domain='monitoring-v1', service='MonitoringService', method='GetClusterUsageMetrics', http_verb='GET', http_path='/api/monitoring/v1/accounts/{account_id}/cluster/{cluster_id}/usage-metrics', path_params=(('account_id', 'account_id'), ('cluster_id', 'cluster_id')), command_name='get-cluster-usage-metrics'),
    Operation(rpc='qdrant.cloud.payment.v1.PaymentService.CreatePaymentMethod', domain='payment-v1', service='PaymentService', method='CreatePaymentMethod', http_verb='POST', http_path='/api/payment/v1/accounts/{payment_method.account_id}/payment-methods', path_params=(('payment_method.account_id', 'payment_method_account_id'),), command_name='create-payment-method'),
    Operation(rpc='qdrant.cloud.payment.v1.PaymentService.CreateStripeCheckoutSession', domain='payment-v1', service='PaymentService', method='CreateStripeCheckoutSession', http_verb='POST', http_path='/api/payment/v1/accounts/{account_id}/stripe-session', path_params=(('account_id', 'account_id'),), command_name='create-stripe-checkout-session'),
    Operation(rpc='qdrant.cloud.payment.v1.PaymentService.DeletePaymentMethod', domain='payment-v1', service='PaymentService', method='DeletePaymentMethod', http_verb='DELETE', http_path='/api/payment/v1/accounts/{account_id}/payment-methods/{payment_method_id}', path_params=(('account_id', 'account_id'), ('payment_method_id', 'payment_method_id')), command_name='delete-payment-method'),
    Operation(rpc='qdrant.cloud.payment.v1.PaymentService.GetPaymentMethod', domain='payment-v1', service='PaymentService', method='GetPaymentMethod', http_verb='GET', http_path='/api/payment/v1/accounts/{account_id}/payment-methods/{payment_method_id}', path_params=(('account_id', 'account_id'), ('payment_method_id', 'payment_method_id')), command_name='get-payment-method'),
    Operation(rpc='qdrant.cloud.payment.v1.PaymentService.GetPaymentMethodAvailability', domain='payment-v1', service='PaymentService', method='GetPaymentMethodAvailability', http_verb='GET', http_path='/api/payment/v1/accounts/{account_id}/payment-method-availability', path_params=(('account_id', 'account_id'),), command_name='get-payment-method-availability'),
    Operation(rpc='qdrant.cloud.payment.v1.PaymentService.GetStripeCheckoutSession', domain='payment-v1', service='PaymentService', method='GetStripeCheckoutSession', http_verb='GET', http_path='/api/payment/v1/accounts/{account_id}/stripe-session/{session_id}', path_params=(('account_id', 'account_id'), ('session_id', 'session_id')), command_name='get-stripe-checkout-session'),
    Operation(rpc='qdrant.cloud.payment.v1.PaymentService.ListPaymentMethods', domain='payment-v1', service='PaymentService', method='ListPaymentMethods', http_verb='GET', http_path='/api/payment/v1/accounts/{account_id}/payment-methods', path_params=(('account_id', 'account_id'),), command_name='list-payment-methods'),
    Operation(rpc='qdrant.cloud.payment.v1.PaymentService.RecordCloudMarketplaceEntitlement', domain='payment-v1', service='PaymentService', method='RecordCloudMarketplaceEntitlement', http_verb='POST', http_path='/api/payment/v1/accounts/{account_id}/marketplace-entitlements', path_params=(('account_id', 'account_id'),), command_name='record-cloud-marketplace-entitlement'),
    Operation(rpc='qdrant.cloud.payment.v1.PaymentService.UpdatePaymentMethod', domain='payment-v1', service='PaymentService', method='UpdatePaymentMethod', http_verb='PUT', http_path='/api/payment/v1/accounts/{payment_method.account_id}/payment-methods/{payment_method.id}', path_params=(('payment_method.account_id', 'payment_method_account_id'), ('payment_method.id', 'payment_method_id')), command_name='update-payment-method'),
    Operation(rpc='qdrant.cloud.platform.v1.PlatformService.GetCloudProviderRegion', domain='platform-v1', service='PlatformService', method='GetCloudProviderRegion', http_verb='GET', http_path='/api/platform/v1/accounts/{account_id}/cloud-providers/{cloud_provider_id}/regions/{region_id}', path_params=(('account_id', 'account_id'), ('cloud_provider_id', 'cloud_provider_id'), ('region_id', 'region_id')), command_name='get-cloud-provider-region'),
    Operation(rpc='qdrant.cloud.platform.v1.PlatformService.GetGlobalCloudProviderRegion', domain='platform-v1', service='PlatformService', method='GetGlobalCloudProviderRegion', http_verb='GET', http_path='/api/platform/v1/cloud-providers/{cloud_provider_id}/regions/{region_id}', path_params=(('cloud_provider_id', 'cloud_provider_id'), ('region_id', 'region_id')), command_name='get-global-cloud-provider-region'),
    Operation(rpc='qdrant.cloud.platform.v1.PlatformService.ListCloudProviderRegions', domain='platform-v1', service='PlatformService', method='ListCloudProviderRegions', http_verb='GET', http_path='/api/platform/v1/accounts/{account_id}/cloud-providers/{cloud_provider_id}/regions', path_params=(('account_id', 'account_id'), ('cloud_provider_id', 'cloud_provider_id')), command_name='list-cloud-provider-regions'),
    Operation(rpc='qdrant.cloud.platform.v1.PlatformService.ListCloudProviders', domain='platform-v1', service='PlatformService', method='ListCloudProviders', http_verb='GET', http_path='/api/platform/v1/accounts/{account_id}/cloud-providers', path_params=(('account_id', 'account_id'),), command_name='list-cloud-providers'),
    Operation(rpc='qdrant.cloud.platform.v1.PlatformService.ListGlobalCloudProviderRegions', domain='platform-v1', service='PlatformService', method='ListGlobalCloudProviderRegions', http_verb='GET', http_path='/api/platform/v1/cloud-providers/{cloud_provider_id}/regions', path_params=(('cloud_provider_id', 'cloud_provider_id'),), command_name='list-global-cloud-provider-regions'),
    Operation(rpc='qdrant.cloud.platform.v1.PlatformService.ListGlobalCloudProviders', domain='platform-v1', service='PlatformService', method='ListGlobalCloudProviders', http_verb='GET', http_path='/api/platform/v1/cloud-providers', path_params=(), command_name='list-global-cloud-providers'),
    Operation(rpc='qdrant.cloud.quota.v1.QuotaService.GetAccountQuotas', domain='quota-v1', service='QuotaService', method='GetAccountQuotas', http_verb='GET', http_path='/api/quota/v1/accounts/{account_id}/quotas', path_params=(('account_id', 'account_id'),), command_name='get-account-quotas'),
    Operation(rpc='qdrant.cloud.quota.v1.QuotaService.GetAuthenticatedUserQuotas', domain='quota-v1', service='QuotaService', method='GetAuthenticatedUserQuotas', http_verb='GET', http_path='/api/quota/v1/users/me/quotas', path_params=(), command_name='get-authenticated-user-quotas'),
    Operation(rpc='qdrant.cloud.serverless.collection.auth.v1.CollectionApiKeyService.CreateCollectionApiKey', domain='serverless-collection-auth-v1', service='CollectionApiKeyService', method='CreateCollectionApiKey', http_verb='POST', http_path='/api/serverless/auth/v1/accounts/{collection_api_key.account_id}/collections/{collection_api_key.collection_id}/api-keys', path_params=(('collection_api_key.account_id', 'collection_api_key_account_id'), ('collection_api_key.collection_id', 'collection_api_key_collection_id')), command_name='create-collection-api-key'),
    Operation(rpc='qdrant.cloud.serverless.collection.auth.v1.CollectionApiKeyService.DeleteCollectionApiKey', domain='serverless-collection-auth-v1', service='CollectionApiKeyService', method='DeleteCollectionApiKey', http_verb='DELETE', http_path='/api/serverless/auth/v1/accounts/{account_id}/collections/{collection_id}/api-keys/{collection_api_key_id}', path_params=(('account_id', 'account_id'), ('collection_id', 'collection_id'), ('collection_api_key_id', 'collection_api_key_id')), command_name='delete-collection-api-key'),
    Operation(rpc='qdrant.cloud.serverless.collection.auth.v1.CollectionApiKeyService.ListCollectionApiKeys', domain='serverless-collection-auth-v1', service='CollectionApiKeyService', method='ListCollectionApiKeys', http_verb='GET', http_path='/api/serverless/auth/v1/accounts/{account_id}/collections/{collection_id}/api-keys', path_params=(('account_id', 'account_id'), ('collection_id', 'collection_id')), command_name='list-collection-api-keys'),
    Operation(rpc='qdrant.cloud.serverless.collection.v1.CollectionService.CreateCollection', domain='serverless-collection-v1', service='CollectionService', method='CreateCollection', http_verb='POST', http_path='/api/serverless/v1/accounts/{collection.account_id}/collections', path_params=(('collection.account_id', 'collection_account_id'),), command_name='create-collection'),
    Operation(rpc='qdrant.cloud.serverless.collection.v1.CollectionService.DeleteCollection', domain='serverless-collection-v1', service='CollectionService', method='DeleteCollection', http_verb='DELETE', http_path='/api/serverless/v1/accounts/{account_id}/collections/{collection_id}', path_params=(('account_id', 'account_id'), ('collection_id', 'collection_id')), command_name='delete-collection'),
    Operation(rpc='qdrant.cloud.serverless.collection.v1.CollectionService.ListCollections', domain='serverless-collection-v1', service='CollectionService', method='ListCollections', http_verb='GET', http_path='/api/serverless/v1/accounts/{account_id}/collections', path_params=(('account_id', 'account_id'),), command_name='list-collections'),
    Operation(rpc='qdrant.cloud.serverless.collection.v1.CollectionService.UpgradeCollection', domain='serverless-collection-v1', service='CollectionService', method='UpgradeCollection', http_verb='PUT', http_path='/api/serverless/v1/accounts/{account_id}/collections/{collection_id}', path_params=(('account_id', 'account_id'), ('collection_id', 'collection_id')), command_name='upgrade-collection'),
    Operation(rpc='qdrant.cloud.ui.v1.AggregationService.ListUsersWithRoles', domain='ui-v1', service='AggregationService', method='ListUsersWithRoles', http_verb='GET', http_path='/api/ui/v1/accounts/{account_id}/users', path_params=(('account_id', 'account_id'),), command_name='list-users-with-roles'),
    Operation(rpc='qdrant.cloud.ui.v1.ClusterDataService.ListCollections', domain='ui-v1', service='ClusterDataService', method='ListCollections', http_verb='GET', http_path='/api/ui/v1/accounts/{account_id}/clusters/{cluster_id}/collections', path_params=(('account_id', 'account_id'), ('cluster_id', 'cluster_id')), command_name='list-collections'),
    Operation(rpc='qdrant.cloud.ui.v1.FeatureFlagsService.GetFeatureFlags', domain='ui-v1', service='FeatureFlagsService', method='GetFeatureFlags', http_verb='GET', http_path='/api/ui/v1/feature-flags', path_params=(), command_name='get-feature-flags'),
)

OPERATIONS_BY_DOMAIN: dict[str, list[Operation]] = {}
OPERATIONS_BY_RPC: dict[str, Operation] = {}
for op in OPERATIONS:
    OPERATIONS_BY_RPC[op.rpc] = op
    OPERATIONS_BY_DOMAIN.setdefault(op.domain, []).append(op)
for dom in OPERATIONS_BY_DOMAIN:
    OPERATIONS_BY_DOMAIN[dom] = sorted(OPERATIONS_BY_DOMAIN[dom], key=lambda o: o.rpc)


def find_operation_by_rpc(rpc: str) -> Operation:
    op = OPERATIONS_BY_RPC.get(str(rpc))
    if not op:
        raise KeyError(f"Unknown RPC: {rpc}")
    return op


def find_verification_read_op(op: Operation) -> Operation | None:
    # Deterministic best-effort: same path template, GET.
    for cand in OPERATIONS:
        if cand.http_verb.upper() == 'GET' and cand.http_path == op.http_path and cand.path_params == op.path_params:
            return cand
    return None
