from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Final


@dataclass(frozen=True)
class ActionSpec:
    family: str
    action: str
    method: str
    path: str
    query_args: tuple[tuple[str, dict[str, Any]], ...] = ()
    requires_body_file: bool = False
    write: bool = False
    require_apply: bool = False
    require_yes: bool = False
    require_ack: bool = False
    require_plan_in: bool = False
    notes: str = ""


_READ: Final[dict[str, bool]] = {
    "require_apply": False,
    "require_yes": False,
    "require_ack": False,
    "require_plan_in": False,
}
_WRITE: Final[dict[str, bool]] = {
    "require_apply": True,
    "require_yes": False,
    "require_ack": False,
    "require_plan_in": False,
}
_WRITE_YES: Final[dict[str, bool]] = {
    "require_apply": True,
    "require_yes": True,
    "require_ack": False,
    "require_plan_in": False,
}


_OPERATIONS_BY_FAMILY: Final[dict[str, tuple[ActionSpec, ...]]] = {
    "catalog-products": (
        ActionSpec(
            "catalog-products",
            "create",
            "POST",
            "/v1/catalogs/products",
            requires_body_file=True,
            write=True,
            **_WRITE,
            notes="Create product.",
        ),
        ActionSpec(
            "catalog-products",
            "list",
            "GET",
            "/v1/catalogs/products",
            write=False,
            notes="List products.",
        ),
        ActionSpec(
            "catalog-products",
            "get",
            "GET",
            "/v1/catalogs/products/{product_id}",
            write=False,
            notes="Show product details.",
        ),
        ActionSpec(
            "catalog-products",
            "patch",
            "PATCH",
            "/v1/catalogs/products/{product_id}",
            requires_body_file=True,
            write=True,
            **_WRITE,
            notes="Update product.",
        ),
    ),
    "disputes": (
        ActionSpec(
            "disputes",
            "list",
            "GET",
            "/v1/customer/disputes",
            write=False,
            notes="List disputes.",
        ),
        ActionSpec(
            "disputes",
            "get",
            "GET",
            "/v1/customer/disputes/{id}",
            write=False,
            notes=(
                "Show dispute details. [account-gated]"
            ),
        ),
        ActionSpec(
            "disputes",
            "send-message",
            "POST",
            "/v1/customer/disputes/{id}/send-message",
            requires_body_file=True,
            write=True,
            **_WRITE,
            notes="Send message about dispute to other party. [account-gated]",
        ),
        ActionSpec(
            "disputes",
            "adjudicate",
            "POST",
            "/v1/customer/disputes/{id}/adjudicate",
            requires_body_file=True,
            write=True,
            **_WRITE,
            notes="Settle dispute. [account-gated]",
        ),
        ActionSpec(
            "disputes",
            "make-offer",
            "POST",
            "/v1/customer/disputes/{id}/make-offer",
            requires_body_file=True,
            write=True,
            **_WRITE,
            notes="Make offer to resolve dispute. [account-gated]",
        ),
        ActionSpec(
            "disputes",
            "require-evidence",
            "POST",
            "/v1/customer/disputes/{id}/require-evidence",
            requires_body_file=True,
            write=True,
            **_WRITE,
            notes="Update dispute status. [account-gated]",
        ),
        ActionSpec(
            "disputes",
            "accept-claim",
            "POST",
            "/v1/customer/disputes/{id}/accept-claim",
            write=True,
            **_WRITE_YES,
            notes="Accept claim. [account-gated]",
        ),
        ActionSpec(
            "disputes",
            "provide-evidence",
            "POST",
            "/v1/customer/disputes/{id}/provide-evidence",
            requires_body_file=True,
            write=True,
            **_WRITE,
            notes="Provide evidence. [account-gated]",
        ),
        ActionSpec(
            "disputes",
            "acknowledge-return-item",
            "POST",
            "/v1/customer/disputes/{id}/acknowledge-return-item",
            write=True,
            **_WRITE,
            notes="Acknowledge returned item. [account-gated]",
        ),
        ActionSpec(
            "disputes",
            "provide-supporting-info",
            "POST",
            "/v1/customer/disputes/{id}/provide-supporting-info",
            requires_body_file=True,
            write=True,
            **_WRITE,
            notes="Provide supporting information for dispute. [account-gated]",
        ),
        ActionSpec(
            "disputes",
            "appeal",
            "POST",
            "/v1/customer/disputes/{id}/appeal",
            requires_body_file=True,
            write=True,
            **_WRITE,
            notes="Appeal dispute. [account-gated]",
        ),
        ActionSpec(
            "disputes",
            "accept-offer",
            "POST",
            "/v1/customer/disputes/{id}/accept-offer",
            write=True,
            **_WRITE,
            notes="Accept offer to resolve dispute. [account-gated]",
        ),
        ActionSpec(
            "disputes",
            "deny-offer",
            "POST",
            "/v1/customer/disputes/{id}/deny-offer",
            write=True,
            **_WRITE,
            notes="Deny offer to resolve dispute. [account-gated]",
        ),
        ActionSpec(
            "disputes",
            "escalate",
            "POST",
            "/v1/customer/disputes/{id}/escalate",
            write=True,
            **_WRITE,
            notes="Escalate dispute to claim. [account-gated]",
        ),
        ActionSpec(
            "disputes",
            "patch",
            "PATCH",
            "/v1/customer/disputes/{id}",
            requires_body_file=True,
            write=True,
            **_WRITE,
            notes="Partially update dispute. [account-gated]",
        ),
    ),
    "identity-v1": (
        ActionSpec(
            "identity-v1",
            "get-userinfo",
            "GET",
            "/v1/identity/openidconnect/userinfo",
            write=False,
            notes="Show user profile details.",
        ),
    ),
    "identity-v2": (
        ActionSpec(
            "identity-v2",
            "create",
            "POST",
            "/v2/scim/Users",
            requires_body_file=True,
            write=True,
            **_WRITE,
            notes="Create user.",
        ),
        ActionSpec(
            "identity-v2",
            "list",
            "GET",
            "/v2/scim/Users",
            write=False,
            notes="List users.",
        ),
        ActionSpec(
            "identity-v2",
            "update",
            "PATCH",
            "/v2/scim/Users/{id}",
            requires_body_file=True,
            write=True,
            **_WRITE,
            notes="Update user.",
        ),
        ActionSpec(
            "identity-v2",
            "get",
            "GET",
            "/v2/scim/Users/{id}",
            write=False,
            notes="Show user details.",
        ),
        ActionSpec(
            "identity-v2",
            "delete",
            "DELETE",
            "/v2/scim/Users/{id}",
            write=True,
            **_WRITE_YES,
            notes="Delete user.",
        ),
    ),
    "invoicing": (
        ActionSpec(
            "invoicing",
            "invoices-create",
            "POST",
            "/v2/invoicing/invoices",
            requires_body_file=True,
            write=True,
            **_WRITE,
            notes="Create draft invoice.",
        ),
        ActionSpec(
            "invoicing",
            "invoices-list",
            "GET",
            "/v2/invoicing/invoices",
            write=False,
            notes="List invoices.",
        ),
        ActionSpec(
            "invoicing",
            "invoices-send",
            "POST",
            "/v2/invoicing/invoices/{invoice_id}/send",
            requires_body_file=True,
            write=True,
            **_WRITE,
            notes="Send invoice.",
        ),
        ActionSpec(
            "invoicing",
            "invoices-get",
            "GET",
            "/v2/invoicing/invoices/{invoice_id}",
            write=False,
            notes="Show invoice details.",
        ),
        ActionSpec(
            "invoicing",
            "invoices-update",
            "PUT",
            "/v2/invoicing/invoices/{invoice_id}",
            requires_body_file=True,
            write=True,
            **_WRITE,
            notes="Fully update invoice.",
        ),
        ActionSpec(
            "invoicing",
            "invoices-delete",
            "DELETE",
            "/v2/invoicing/invoices/{invoice_id}",
            write=True,
            **_WRITE_YES,
            notes="Delete invoice.",
        ),
        ActionSpec(
            "invoicing",
            "search-invoices",
            "POST",
            "/v2/invoicing/search-invoices",
            requires_body_file=True,
            write=False,
            notes="Search for invoices.",
        ),
        ActionSpec(
            "invoicing",
            "invoices-cancel",
            "POST",
            "/v2/invoicing/invoices/{invoice_id}/cancel",
            requires_body_file=True,
            write=True,
            **_WRITE,
            notes="Cancel sent invoice.",
        ),
        ActionSpec(
            "invoicing",
            "invoices-remind",
            "POST",
            "/v2/invoicing/invoices/{invoice_id}/remind",
            requires_body_file=True,
            write=True,
            **_WRITE,
            notes="Send invoice reminder.",
        ),
        ActionSpec(
            "invoicing",
            "invoices-payments",
            "POST",
            "/v2/invoicing/invoices/{invoice_id}/payments",
            requires_body_file=True,
            write=True,
            **_WRITE,
            notes="Record payment for invoice.",
        ),
        ActionSpec(
            "invoicing",
            "invoices-payments-delete",
            "DELETE",
            "/v2/invoicing/invoices/{invoice_id}/payments/{transaction_id}",
            write=True,
            **_WRITE_YES,
            notes="Delete external payment.",
        ),
        ActionSpec(
            "invoicing",
            "invoices-refunds",
            "POST",
            "/v2/invoicing/invoices/{invoice_id}/refunds",
            requires_body_file=True,
            write=True,
            **_WRITE,
            notes="Record refund for invoice.",
        ),
        ActionSpec(
            "invoicing",
            "invoices-refunds-delete",
            "DELETE",
            "/v2/invoicing/invoices/{invoice_id}/refunds/{transaction_id}",
            write=True,
            **_WRITE_YES,
            notes="Delete external refund.",
        ),
        ActionSpec(
            "invoicing",
            "invoices-generate-next-invoice-number",
            "POST",
            "/v2/invoicing/generate-next-invoice-number",
            write=False,
            notes="Generate invoice number.",
        ),
        ActionSpec(
            "invoicing",
            "invoices-generate-qr-code",
            "POST",
            "/v2/invoicing/invoices/{invoice_id}/generate-qr-code",
            write=False,
            notes="Generate QR code.",
        ),
        ActionSpec(
            "invoicing",
            "templates-list",
            "GET",
            "/v2/invoicing/templates",
            write=False,
            notes="List templates.",
        ),
        ActionSpec(
            "invoicing",
            "templates-create",
            "POST",
            "/v2/invoicing/templates",
            requires_body_file=True,
            write=True,
            **_WRITE,
            notes="Create template.",
        ),
        ActionSpec(
            "invoicing",
            "templates-get",
            "GET",
            "/v2/invoicing/templates/{template_id}",
            write=False,
            notes="Show template details.",
        ),
        ActionSpec(
            "invoicing",
            "templates-update",
            "PUT",
            "/v2/invoicing/templates/{template_id}",
            requires_body_file=True,
            write=True,
            **_WRITE,
            notes="Fully update template.",
        ),
        ActionSpec(
            "invoicing",
            "templates-delete",
            "DELETE",
            "/v2/invoicing/templates/{template_id}",
            write=True,
            **_WRITE_YES,
            notes="Delete template.",
        ),
        ActionSpec(
            "invoicing",
            "auto-reminder-configuration.setup",
            "POST",
            "/v2/invoicing/setup-reminders",
            requires_body_file=True,
            write=True,
            **_WRITE,
            notes="Setup auto reminder configuration.",
        ),
        ActionSpec(
            "invoicing",
            "auto-reminder-configuration.get",
            "GET",
            "/v2/invoicing/reminders/{id}",
            write=False,
            notes="Retrieve an invoice auto reminder configuration.",
        ),
        ActionSpec(
            "invoicing",
            "auto-reminder-configuration-update",
            "PUT",
            "/v2/invoicing/reminders/{id}",
            requires_body_file=True,
            write=True,
            **_WRITE,
            notes="Update invoice auto reminder configuration.",
        ),
        ActionSpec(
            "invoicing",
            "auto-reminder-configuration.get-all",
            "GET",
            "/v2/invoicing/reminders",
            write=False,
            notes="Get all invoice auto reminder configuration.",
        ),
        ActionSpec(
            "invoicing",
            "auto-reminder-configuration.suspend",
            "POST",
            "/v2/invoicing/reminders/{id}/suspend",
            write=True,
            **_WRITE,
            notes="Suspend invoice auto reminder configuration.",
        ),
        ActionSpec(
            "invoicing",
            "auto-reminder-configuration.resume",
            "POST",
            "/v2/invoicing/reminders/{id}/resume",
            write=True,
            **_WRITE,
            notes="Resume invoice auto reminder configuration.",
        ),
        ActionSpec(
            "invoicing",
            "invoices-cancel-reminders",
            "POST",
            "/v2/invoicing/invoices/{id}/cancel-reminders",
            write=True,
            **_WRITE,
            notes="Cancel auto reminders for an invoice.",
        ),
    ),
    "orders": (
        ActionSpec(
            "orders",
            "create",
            "POST",
            "/v2/checkout/orders",
            requires_body_file=True,
            write=True,
            **_WRITE,
            notes="Create order.",
        ),
        ActionSpec(
            "orders",
            "get",
            "GET",
            "/v2/checkout/orders/{id}",
            write=False,
            notes="Show order details.",
        ),
        ActionSpec(
            "orders",
            "patch",
            "PATCH",
            "/v2/checkout/orders/{id}",
            requires_body_file=True,
            write=True,
            **_WRITE,
            notes="Update order.",
        ),
        ActionSpec(
            "orders",
            "confirm",
            "POST",
            "/v2/checkout/orders/{id}/confirm-payment-source",
            requires_body_file=True,
            write=True,
            **_WRITE,
            notes="Confirm the Order.",
        ),
        ActionSpec(
            "orders",
            "authorize",
            "POST",
            "/v2/checkout/orders/{id}/authorize",
            requires_body_file=True,
            write=True,
            **_WRITE,
            notes="Authorize payment for order.",
        ),
        ActionSpec(
            "orders",
            "capture",
            "POST",
            "/v2/checkout/orders/{id}/capture",
            requires_body_file=True,
            write=True,
            **_WRITE,
            notes="Capture payment for order.",
        ),
        ActionSpec(
            "orders",
            "track-create",
            "POST",
            "/v2/checkout/orders/{id}/track",
            requires_body_file=True,
            write=True,
            **_WRITE,
            notes="Add tracking information for an order.",
        ),
        ActionSpec(
            "orders",
            "trackers-patch",
            "PATCH",
            "/v2/checkout/orders/{id}/trackers/{tracker_id}",
            requires_body_file=True,
            write=True,
            **_WRITE,
            notes="Update or cancel tracking information for an order.",
        ),
    ),
    "payment-experience": (
        ActionSpec(
            "payment-experience",
            "create",
            "POST",
            "/v1/payment-experience/web-profiles",
            requires_body_file=True,
            write=True,
            **_WRITE,
            notes="Create web experience profile.",
        ),
        ActionSpec(
            "payment-experience",
            "get-list",
            "GET",
            "/v1/payment-experience/web-profiles",
            write=False,
            notes="List web experience profiles.",
        ),
        ActionSpec(
            "payment-experience",
            "get",
            "GET",
            "/v1/payment-experience/web-profiles/{id}",
            write=False,
            notes="Show web experience profile details by ID.",
        ),
        ActionSpec(
            "payment-experience",
            "update",
            "PUT",
            "/v1/payment-experience/web-profiles/{id}",
            requires_body_file=True,
            write=True,
            **_WRITE,
            notes="Update web experience profile.",
        ),
        ActionSpec(
            "payment-experience",
            "partial-update",
            "PATCH",
            "/v1/payment-experience/web-profiles/{id}",
            requires_body_file=True,
            write=True,
            **_WRITE,
            notes="Partially update web experience profile.",
        ),
        ActionSpec(
            "payment-experience",
            "delete",
            "DELETE",
            "/v1/payment-experience/web-profiles/{id}",
            write=True,
            **_WRITE_YES,
            notes="Delete web experience profile.",
        ),
    ),
    "payment-tokens": (
        ActionSpec(
            "payment-tokens",
            "create",
            "POST",
            "/v3/vault/payment-tokens",
            requires_body_file=True,
            write=True,
            **_WRITE,
            notes="Create payment token for a given payment source.",
        ),
        ActionSpec(
            "payment-tokens",
            "list",
            "GET",
            "/v3/vault/payment-tokens",
            write=False,
            notes="List all payment tokens.",
        ),
        ActionSpec(
            "payment-tokens",
            "get",
            "GET",
            "/v3/vault/payment-tokens/{id}",
            write=False,
            notes="Retrieve a payment token.",
        ),
        ActionSpec(
            "payment-tokens",
            "delete",
            "DELETE",
            "/v3/vault/payment-tokens/{id}",
            write=True,
            **_WRITE_YES,
            notes="Delete payment token.",
        ),
        ActionSpec(
            "payment-tokens",
            "setup-tokens.create",
            "POST",
            "/v3/vault/setup-tokens",
            requires_body_file=True,
            write=True,
            **_WRITE,
            notes="Create a setup token.",
        ),
        ActionSpec(
            "payment-tokens",
            "setup-tokens.get",
            "GET",
            "/v3/vault/setup-tokens/{id}",
            write=False,
            notes="Retrieve a setup token.",
        ),
    ),
    "payments": (
        ActionSpec(
            "payments",
            "authorizations.get",
            "GET",
            "/v2/payments/authorizations/{authorization_id}",
            write=False,
            notes="Show details for authorized payment.",
        ),
        ActionSpec(
            "payments",
            "authorizations.capture",
            "POST",
            "/v2/payments/authorizations/{authorization_id}/capture",
            requires_body_file=True,
            write=True,
            **_WRITE,
            notes="Capture authorized payment.",
        ),
        ActionSpec(
            "payments",
            "authorizations.reauthorize",
            "POST",
            "/v2/payments/authorizations/{authorization_id}/reauthorize",
            requires_body_file=True,
            write=True,
            **_WRITE,
            notes="Reauthorize authorized payment.",
        ),
        ActionSpec(
            "payments",
            "authorizations.void",
            "POST",
            "/v2/payments/authorizations/{authorization_id}/void",
            write=True,
            **_WRITE_YES,
            notes="Void authorized payment.",
        ),
        ActionSpec(
            "payments",
            "captures.get",
            "GET",
            "/v2/payments/captures/{capture_id}",
            write=False,
            notes="Show captured payment details.",
        ),
        ActionSpec(
            "payments",
            "captures.refund",
            "POST",
            "/v2/payments/captures/{capture_id}/refund",
            requires_body_file=True,
            write=True,
            **_WRITE,
            notes="Refund captured payment.",
        ),
        ActionSpec(
            "payments",
            "find-eligible-methods",
            "POST",
            "/v2/payments/find-eligible-methods",
            requires_body_file=True,
            write=False,
            notes="Find a list of eligible payment methods.",
        ),
        ActionSpec(
            "payments",
            "refunds.get",
            "GET",
            "/v2/payments/refunds/{refund_id}",
            write=False,
            notes="Show refund details.",
        ),
    ),
    "partner-referrals": (
        ActionSpec(
            "partner-referrals",
            "create",
            "POST",
            "/v2/customer/partner-referrals",
            requires_body_file=True,
            write=True,
            **_WRITE,
            notes="Create partner referral. [partner-gated]",
        ),
        ActionSpec(
            "partner-referrals",
            "get",
            "GET",
            "/v2/customer/partner-referrals/{partner_referral_id}",
            write=False,
            notes="Show referral data. [partner-gated]",
        ),
    ),
    "payouts": (
        ActionSpec(
            "payouts",
            "create",
            "POST",
            "/v1/payments/payouts",
            requires_body_file=True,
            write=True,
            **_WRITE,
            notes="Create batch payout. [account-gated]",
        ),
        ActionSpec(
            "payouts",
            "get",
            "GET",
            "/v1/payments/payouts/{id}",
            write=False,
            notes="Show payout batch details. [account-gated]",
        ),
        ActionSpec(
            "payouts",
            "item-get",
            "GET",
            "/v1/payments/payouts-item/{payout_item_id}",
            write=False,
            notes="Show payout item details. [account-gated]",
        ),
        ActionSpec(
            "payouts",
            "item-cancel",
            "POST",
            "/v1/payments/payouts-item/{payout_item_id}/cancel",
            requires_body_file=True,
            write=True,
            **_WRITE,
            notes="Cancel unclaimed payout item. [account-gated]",
        ),
    ),
    "pricing": (
        ActionSpec(
            "pricing",
            "quote-exchange-rates",
            "POST",
            "/v2/pricing/quote-exchange-rates",
            requires_body_file=True,
            write=False,
            notes="Create Exchange Rate Quote.",
        ),
    ),
    "referenced-payouts": (
        ActionSpec(
            "referenced-payouts",
            "create-batch",
            "POST",
            "/v1/payments/referenced-payouts",
            requires_body_file=True,
            write=True,
            **_WRITE,
            notes="Create referenced batch payout. [partner-gated, account-gated]",
        ),
        ActionSpec(
            "referenced-payouts",
            "get-batch-details",
            "GET",
            "/v1/payments/referenced-payouts/{payouts_batch_id}",
            write=False,
            notes="List items in referenced batch payout. [partner-gated, account-gated]",
        ),
        ActionSpec(
            "referenced-payouts",
            "items-create",
            "POST",
            "/v1/payments/referenced-payouts-items",
            requires_body_file=True,
            write=True,
            **_WRITE,
            notes="Create referenced payout item. [partner-gated, account-gated]",
        ),
        ActionSpec(
            "referenced-payouts",
            "items-get",
            "GET",
            "/v1/payments/referenced-payouts-items/{payouts_item_id}",
            write=False,
            notes="Show referenced payout item details. [partner-gated, account-gated]",
        ),
    ),
    "subscriptions": (
        ActionSpec(
            "subscriptions",
            "plans-create",
            "POST",
            "/v1/billing/plans",
            requires_body_file=True,
            write=True,
            **_WRITE,
            notes="Create plan.",
        ),
        ActionSpec(
            "subscriptions",
            "plans-list",
            "GET",
            "/v1/billing/plans",
            write=False,
            notes="List plans.",
        ),
        ActionSpec(
            "subscriptions",
            "plans-get",
            "GET",
            "/v1/billing/plans/{id}",
            write=False,
            notes="Show plan details.",
        ),
        ActionSpec(
            "subscriptions",
            "plans-patch",
            "PATCH",
            "/v1/billing/plans/{id}",
            requires_body_file=True,
            write=True,
            **_WRITE,
            notes="Update plan.",
        ),
        ActionSpec(
            "subscriptions",
            "plans-activate",
            "POST",
            "/v1/billing/plans/{id}/activate",
            write=True,
            **_WRITE,
            notes="Activate plan.",
        ),
        ActionSpec(
            "subscriptions",
            "plans-deactivate",
            "POST",
            "/v1/billing/plans/{id}/deactivate",
            write=True,
            **_WRITE,
            notes="Deactivate plan.",
        ),
        ActionSpec(
            "subscriptions",
            "plans-update-pricing-schemes",
            "POST",
            "/v1/billing/plans/{id}/update-pricing-schemes",
            requires_body_file=True,
            write=True,
            **_WRITE,
            notes="Update pricing.",
        ),
        ActionSpec(
            "subscriptions",
            "subscriptions-create",
            "POST",
            "/v1/billing/subscriptions",
            requires_body_file=True,
            write=True,
            **_WRITE,
            notes="Create subscription.",
        ),
        ActionSpec(
            "subscriptions",
            "subscriptions-list",
            "GET",
            "/v1/billing/subscriptions",
            write=False,
            notes="List subscriptions.",
        ),
        ActionSpec(
            "subscriptions",
            "subscriptions-get",
            "GET",
            "/v1/billing/subscriptions/{id}",
            write=False,
            notes="Show subscription details.",
        ),
        ActionSpec(
            "subscriptions",
            "subscriptions-patch",
            "PATCH",
            "/v1/billing/subscriptions/{id}",
            requires_body_file=True,
            write=True,
            **_WRITE,
            notes="Update subscription.",
        ),
        ActionSpec(
            "subscriptions",
            "subscriptions-revise",
            "POST",
            "/v1/billing/subscriptions/{id}/revise",
            requires_body_file=True,
            write=True,
            **_WRITE,
            notes="Revise plan or quantity of subscription.",
        ),
        ActionSpec(
            "subscriptions",
            "subscriptions-suspend",
            "POST",
            "/v1/billing/subscriptions/{id}/suspend",
            requires_body_file=True,
            write=True,
            **_WRITE,
            notes="Suspend subscription.",
        ),
        ActionSpec(
            "subscriptions",
            "subscriptions-cancel",
            "POST",
            "/v1/billing/subscriptions/{id}/cancel",
            requires_body_file=True,
            write=True,
            **_WRITE,
            notes="Cancel subscription.",
        ),
        ActionSpec(
            "subscriptions",
            "subscriptions-activate",
            "POST",
            "/v1/billing/subscriptions/{id}/activate",
            requires_body_file=True,
            write=True,
            **_WRITE,
            notes="Activate subscription.",
        ),
        ActionSpec(
            "subscriptions",
            "subscriptions-capture",
            "POST",
            "/v1/billing/subscriptions/{id}/capture",
            requires_body_file=True,
            write=True,
            **_WRITE,
            notes="Capture authorized payment on subscription.",
        ),
        ActionSpec(
            "subscriptions",
            "subscriptions-transactions",
            "GET",
            "/v1/billing/subscriptions/{id}/transactions",
            write=False,
            notes="List transactions for subscription.",
        ),
    ),
    "tracking": (
        ActionSpec(
            "tracking",
            "trackers-batch-post",
            "POST",
            "/v1/shipping/trackers-batch",
            requires_body_file=True,
            write=True,
            **_WRITE,
            notes="Add tracking information for multiple PayPal transactions.",
        ),
        ActionSpec(
            "tracking",
            "trackers-post",
            "POST",
            "/v1/shipping/trackers",
            requires_body_file=True,
            write=True,
            **_WRITE,
            notes="Add tracking information for PayPal transaction.",
        ),
        ActionSpec(
            "tracking",
            "trackers-batch-get",
            "GET",
            "/v1/shipping/trackers",
            write=False,
            notes="List tracking information.",
        ),
        ActionSpec(
            "tracking",
            "trackers-put",
            "PUT",
            "/v1/shipping/trackers/{id}",
            requires_body_file=True,
            write=True,
            **_WRITE,
            notes="Update or cancel tracking information for PayPal transaction.",
        ),
        ActionSpec(
            "tracking",
            "trackers-get",
            "GET",
            "/v1/shipping/trackers/{id}",
            write=False,
            notes="Show tracking information.",
        ),
    ),
    "transaction-search": (
        ActionSpec(
            "transaction-search",
            "search.get",
            "GET",
            "/v1/reporting/transactions",
            write=False,
            notes="List transactions. [live-unverified]",
        ),
        ActionSpec(
            "transaction-search",
            "balances.get",
            "GET",
            "/v1/reporting/balances",
            write=False,
            notes="List all balances. [live-unverified]",
        ),
        ActionSpec(
            "transaction-search",
            "accounting.balanceNetSummary.get",
            "GET",
            "/v1/reporting/get-balance-net-summary",
            write=False,
            notes="List all balance and net activity summary. [live-unverified]",
        ),
        ActionSpec(
            "transaction-search",
            "accounting.dailySummary.get",
            "GET",
            "/v1/reporting/get-daily-summary",
            write=False,
            notes="List all daily summary. [live-unverified]",
        ),
    ),
    "webhooks": (
        ActionSpec(
            "webhooks",
            "create",
            "POST",
            "/v1/notifications/webhooks",
            requires_body_file=True,
            write=True,
            **_WRITE,
            notes="Create webhook.",
        ),
        ActionSpec(
            "webhooks",
            "list",
            "GET",
            "/v1/notifications/webhooks",
            write=False,
            notes="List webhooks.",
        ),
        ActionSpec(
            "webhooks",
            "get",
            "GET",
            "/v1/notifications/webhooks/{webhook_id}",
            write=False,
            notes="Show webhook details.",
        ),
        ActionSpec(
            "webhooks",
            "update",
            "PATCH",
            "/v1/notifications/webhooks/{webhook_id}",
            requires_body_file=True,
            write=True,
            **_WRITE,
            notes="Update webhook.",
        ),
        ActionSpec(
            "webhooks",
            "delete",
            "DELETE",
            "/v1/notifications/webhooks/{webhook_id}",
            write=True,
            **_WRITE_YES,
            notes="Delete webhook.",
        ),
        ActionSpec(
            "webhooks",
            "event-types-list",
            "GET",
            "/v1/notifications/webhooks/{webhook_id}/event-types",
            write=False,
            notes="List event subscriptions for webhook.",
        ),
        ActionSpec(
            "webhooks",
            "webhooks-lookup.post",
            "POST",
            "/v1/notifications/webhooks-lookup",
            requires_body_file=True,
            write=True,
            **_WRITE,
            notes="Create webhook lookup.",
        ),
        ActionSpec(
            "webhooks",
            "webhooks-lookup.list",
            "GET",
            "/v1/notifications/webhooks-lookup",
            write=False,
            notes="List webhook lookups.",
        ),
        ActionSpec(
            "webhooks",
            "webhooks-lookup.get",
            "GET",
            "/v1/notifications/webhooks-lookup/{webhook_lookup_id}",
            write=False,
            notes="Show webhook lookup details.",
        ),
        ActionSpec(
            "webhooks",
            "webhooks-lookup.delete",
            "DELETE",
            "/v1/notifications/webhooks-lookup/{webhook_lookup_id}",
            write=True,
            **_WRITE_YES,
            notes="Delete webhook lookup.",
        ),
        ActionSpec(
            "webhooks",
            "verify-webhook-signature",
            "POST",
            "/v1/notifications/verify-webhook-signature",
            requires_body_file=True,
            write=False,
            notes="Verify webhook signature.",
        ),
        ActionSpec(
            "webhooks",
            "webhooks-event-types.list",
            "GET",
            "/v1/notifications/webhooks-event-types",
            write=False,
            notes="List available events.",
        ),
        ActionSpec(
            "webhooks",
            "webhooks-events.list",
            "GET",
            "/v1/notifications/webhooks-events",
            write=False,
            notes="List event notifications.",
        ),
        ActionSpec(
            "webhooks",
            "webhooks-events.get",
            "GET",
            "/v1/notifications/webhooks-events/{event_id}",
            write=False,
            notes="Show event notification details.",
        ),
        ActionSpec(
            "webhooks",
            "webhooks-events.resend",
            "POST",
            "/v1/notifications/webhooks-events/{event_id}/resend",
            requires_body_file=True,
            write=True,
            **_WRITE,
            notes="Resend event notification.",
        ),
        ActionSpec(
            "webhooks",
            "simulate-event",
            "POST",
            "/v1/notifications/simulate-event",
            requires_body_file=True,
            write=True,
            **_WRITE,
            notes="Simulate webhook event.",
        ),
    ),
}


def actions() -> dict[str, dict[str, ActionSpec]]:
    return {
        family: {spec.action: spec for spec in specs}
        for family, specs in _OPERATIONS_BY_FAMILY.items()
    }


def all_specs() -> tuple[ActionSpec, ...]:
    specs: list[ActionSpec] = []
    for family_specs in _OPERATIONS_BY_FAMILY.values():
        specs.extend(family_specs)
    return tuple(specs)
