from __future__ import annotations

from dataclasses import dataclass

@dataclass(frozen=True)
class OperationSpec:
    family: str
    method_name: str
    method_original: str
    operation_id: str
    http_method: str
    path: str
    versions: tuple[str, ...]
    version_paths: dict[str, str]
    path_params: tuple[str, ...]
    query_params: tuple[str, ...]
    request_ref: str | None
    response_ref: str | None
    description: str
    supports_media_upload: bool
    supports_media_download: bool
    safety_class: str
    risk_flags: tuple[str, ...]

    @property
    def command_key(self) -> tuple[str, str]:
        return (self.family, self.method_name)

OPERATIONS: tuple[OperationSpec, ...] = (
    OperationSpec(
        family='batches',
        method_name='cancel',
        method_original='cancel',
        operation_id='generativelanguage.batches.cancel',
        http_method='POST',
        path='v1beta/{+name}:cancel',
        request_ref=None,
        response_ref='Empty',
        description="Starts asynchronous cancellation on a long-running operation. The server makes a best effort to cancel the operation, but success is not guaranteed. If the server doesn't support this method, it returns `google.rpc.Code.UNIMPLEMENTED`. Clients can use Operations.GetOperation or other methods to check whether the cancellation succeeded or whether the operation completed despite cancellation. On successful cancellation, the operation is not deleted; instead, it becomes an operation with an Operation.error value with a google.rpc.Status.code of `1`, corresponding to `Code.CANCELLED`.",
        supports_media_upload=False,
        supports_media_download=False,
        safety_class='state_changing',
        versions=('v1beta', 'v1'),
        version_paths={'v1beta': 'v1beta/{+name}:cancel', 'v1': 'v1/{+name}:cancel'},
        path_params=('name',),
        query_params=(),
        risk_flags=('bulk', 'irreversible', 'no_snapshot'),
    ),
    OperationSpec(
        family='batches',
        method_name='delete',
        method_original='delete',
        operation_id='generativelanguage.batches.delete',
        http_method='DELETE',
        path='v1beta/{+name}',
        request_ref=None,
        response_ref='Empty',
        description="Deletes a long-running operation. This method indicates that the client is no longer interested in the operation result. It does not cancel the operation. If the server doesn't support this method, it returns `google.rpc.Code.UNIMPLEMENTED`.",
        supports_media_upload=False,
        supports_media_download=False,
        safety_class='state_changing',
        versions=('v1beta', 'v1'),
        version_paths={'v1beta': 'v1beta/{+name}', 'v1': 'v1/{+name}'},
        path_params=('name',),
        query_params=(),
        risk_flags=('bulk', 'destructive', 'irreversible', 'no_snapshot'),
    ),
    OperationSpec(
        family='batches',
        method_name='get',
        method_original='get',
        operation_id='generativelanguage.batches.get',
        http_method='GET',
        path='v1beta/{+name}',
        request_ref=None,
        response_ref='Operation',
        description='Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service.',
        supports_media_upload=False,
        supports_media_download=False,
        safety_class='read',
        versions=('v1beta', 'v1'),
        version_paths={'v1beta': 'v1beta/{+name}', 'v1': 'v1/{+name}'},
        path_params=('name',),
        query_params=(),
        risk_flags=('bulk',),
    ),
    OperationSpec(
        family='batches',
        method_name='list',
        method_original='list',
        operation_id='generativelanguage.batches.list',
        http_method='GET',
        path='v1beta/{+name}',
        request_ref=None,
        response_ref='ListOperationsResponse',
        description="Lists operations that match the specified filter in the request. If the server doesn't support this method, it returns `UNIMPLEMENTED`.",
        supports_media_upload=False,
        supports_media_download=False,
        safety_class='read',
        versions=('v1beta', 'v1'),
        version_paths={'v1beta': 'v1beta/{+name}', 'v1': 'v1/{+name}'},
        path_params=('name',),
        query_params=('filter', 'pageSize', 'pageToken', 'returnPartialSuccess'),
        risk_flags=('bulk',),
    ),
    OperationSpec(
        family='batches',
        method_name='update-embed-content-batch',
        method_original='updateEmbedContentBatch',
        operation_id='generativelanguage.batches.updateEmbedContentBatch',
        http_method='PATCH',
        path='v1beta/{+name}:updateEmbedContentBatch',
        request_ref='EmbedContentBatch',
        response_ref='EmbedContentBatch',
        description='Updates a batch of EmbedContent requests for batch processing.',
        supports_media_upload=False,
        supports_media_download=False,
        safety_class='state_changing',
        versions=('v1beta', 'v1'),
        version_paths={'v1beta': 'v1beta/{+name}:updateEmbedContentBatch', 'v1': 'v1/{+name}:updateEmbedContentBatch'},
        path_params=('name',),
        query_params=('updateMask',),
        risk_flags=('bulk', 'no_snapshot'),
    ),
    OperationSpec(
        family='batches',
        method_name='update-generate-content-batch',
        method_original='updateGenerateContentBatch',
        operation_id='generativelanguage.batches.updateGenerateContentBatch',
        http_method='PATCH',
        path='v1beta/{+name}:updateGenerateContentBatch',
        request_ref='GenerateContentBatch',
        response_ref='GenerateContentBatch',
        description='Updates a batch of GenerateContent requests for batch processing.',
        supports_media_upload=False,
        supports_media_download=False,
        safety_class='state_changing',
        versions=('v1beta', 'v1'),
        version_paths={'v1beta': 'v1beta/{+name}:updateGenerateContentBatch', 'v1': 'v1/{+name}:updateGenerateContentBatch'},
        path_params=('name',),
        query_params=('updateMask',),
        risk_flags=('bulk', 'no_snapshot'),
    ),
    OperationSpec(
        family='cached-contents',
        method_name='create',
        method_original='create',
        operation_id='generativelanguage.cachedContents.create',
        http_method='POST',
        path='v1beta/cachedContents',
        request_ref='CachedContent',
        response_ref='CachedContent',
        description='Creates CachedContent resource.',
        supports_media_upload=False,
        supports_media_download=False,
        safety_class='state_changing',
        versions=('v1beta',),
        version_paths={'v1beta': 'v1beta/cachedContents'},
        path_params=(),
        query_params=(),
        risk_flags=('no_snapshot',),
    ),
    OperationSpec(
        family='cached-contents',
        method_name='delete',
        method_original='delete',
        operation_id='generativelanguage.cachedContents.delete',
        http_method='DELETE',
        path='v1beta/{+name}',
        request_ref=None,
        response_ref='Empty',
        description='Deletes CachedContent resource.',
        supports_media_upload=False,
        supports_media_download=False,
        safety_class='state_changing',
        versions=('v1beta',),
        version_paths={'v1beta': 'v1beta/{+name}'},
        path_params=('name',),
        query_params=(),
        risk_flags=('destructive', 'irreversible', 'no_snapshot'),
    ),
    OperationSpec(
        family='cached-contents',
        method_name='get',
        method_original='get',
        operation_id='generativelanguage.cachedContents.get',
        http_method='GET',
        path='v1beta/{+name}',
        request_ref=None,
        response_ref='CachedContent',
        description='Reads CachedContent resource.',
        supports_media_upload=False,
        supports_media_download=False,
        safety_class='read',
        versions=('v1beta',),
        version_paths={'v1beta': 'v1beta/{+name}'},
        path_params=('name',),
        query_params=(),
        risk_flags=(),
    ),
    OperationSpec(
        family='cached-contents',
        method_name='list',
        method_original='list',
        operation_id='generativelanguage.cachedContents.list',
        http_method='GET',
        path='v1beta/cachedContents',
        request_ref=None,
        response_ref='ListCachedContentsResponse',
        description='Lists CachedContents.',
        supports_media_upload=False,
        supports_media_download=False,
        safety_class='read',
        versions=('v1beta',),
        version_paths={'v1beta': 'v1beta/cachedContents'},
        path_params=(),
        query_params=('pageSize', 'pageToken'),
        risk_flags=(),
    ),
    OperationSpec(
        family='cached-contents',
        method_name='patch',
        method_original='patch',
        operation_id='generativelanguage.cachedContents.patch',
        http_method='PATCH',
        path='v1beta/{+name}',
        request_ref='CachedContent',
        response_ref='CachedContent',
        description='Updates CachedContent resource (only expiration is updatable).',
        supports_media_upload=False,
        supports_media_download=False,
        safety_class='state_changing',
        versions=('v1beta',),
        version_paths={'v1beta': 'v1beta/{+name}'},
        path_params=('name',),
        query_params=('updateMask',),
        risk_flags=('no_snapshot',),
    ),
    OperationSpec(
        family='corpora',
        method_name='create',
        method_original='create',
        operation_id='generativelanguage.corpora.create',
        http_method='POST',
        path='v1beta/corpora',
        request_ref='Corpus',
        response_ref='Corpus',
        description='Creates an empty `Corpus`.',
        supports_media_upload=False,
        supports_media_download=False,
        safety_class='state_changing',
        versions=('v1beta',),
        version_paths={'v1beta': 'v1beta/corpora'},
        path_params=(),
        query_params=(),
        risk_flags=('no_snapshot',),
    ),
    OperationSpec(
        family='corpora',
        method_name='delete',
        method_original='delete',
        operation_id='generativelanguage.corpora.delete',
        http_method='DELETE',
        path='v1beta/{+name}',
        request_ref=None,
        response_ref='Empty',
        description='Deletes a `Corpus`.',
        supports_media_upload=False,
        supports_media_download=False,
        safety_class='state_changing',
        versions=('v1beta',),
        version_paths={'v1beta': 'v1beta/{+name}'},
        path_params=('name',),
        query_params=('force',),
        risk_flags=('destructive', 'irreversible', 'no_snapshot'),
    ),
    OperationSpec(
        family='corpora',
        method_name='get',
        method_original='get',
        operation_id='generativelanguage.corpora.get',
        http_method='GET',
        path='v1beta/{+name}',
        request_ref=None,
        response_ref='Corpus',
        description='Gets information about a specific `Corpus`.',
        supports_media_upload=False,
        supports_media_download=False,
        safety_class='read',
        versions=('v1beta',),
        version_paths={'v1beta': 'v1beta/{+name}'},
        path_params=('name',),
        query_params=(),
        risk_flags=(),
    ),
    OperationSpec(
        family='corpora',
        method_name='list',
        method_original='list',
        operation_id='generativelanguage.corpora.list',
        http_method='GET',
        path='v1beta/corpora',
        request_ref=None,
        response_ref='ListCorporaResponse',
        description='Lists all `Corpora` owned by the user.',
        supports_media_upload=False,
        supports_media_download=False,
        safety_class='read',
        versions=('v1beta',),
        version_paths={'v1beta': 'v1beta/corpora'},
        path_params=(),
        query_params=('pageSize', 'pageToken'),
        risk_flags=(),
    ),
    OperationSpec(
        family='corpora-operations',
        method_name='get',
        method_original='get',
        operation_id='generativelanguage.corpora.operations.get',
        http_method='GET',
        path='v1beta/{+name}',
        request_ref=None,
        response_ref='Operation',
        description='Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service.',
        supports_media_upload=False,
        supports_media_download=False,
        safety_class='read',
        versions=('v1beta', 'v1'),
        version_paths={'v1beta': 'v1beta/{+name}', 'v1': 'v1/{+name}'},
        path_params=('name',),
        query_params=(),
        risk_flags=(),
    ),
    OperationSpec(
        family='corpora-permissions',
        method_name='create',
        method_original='create',
        operation_id='generativelanguage.corpora.permissions.create',
        http_method='POST',
        path='v1beta/{+parent}/permissions',
        request_ref='Permission',
        response_ref='Permission',
        description='Create a permission to a specific resource.',
        supports_media_upload=False,
        supports_media_download=False,
        safety_class='state_changing',
        versions=('v1beta',),
        version_paths={'v1beta': 'v1beta/{+parent}/permissions'},
        path_params=('parent',),
        query_params=(),
        risk_flags=('no_snapshot', 'permission'),
    ),
    OperationSpec(
        family='corpora-permissions',
        method_name='delete',
        method_original='delete',
        operation_id='generativelanguage.corpora.permissions.delete',
        http_method='DELETE',
        path='v1beta/{+name}',
        request_ref=None,
        response_ref='Empty',
        description='Deletes the permission.',
        supports_media_upload=False,
        supports_media_download=False,
        safety_class='state_changing',
        versions=('v1beta',),
        version_paths={'v1beta': 'v1beta/{+name}'},
        path_params=('name',),
        query_params=(),
        risk_flags=('destructive', 'irreversible', 'no_snapshot', 'permission'),
    ),
    OperationSpec(
        family='corpora-permissions',
        method_name='get',
        method_original='get',
        operation_id='generativelanguage.corpora.permissions.get',
        http_method='GET',
        path='v1beta/{+name}',
        request_ref=None,
        response_ref='Permission',
        description='Gets information about a specific Permission.',
        supports_media_upload=False,
        supports_media_download=False,
        safety_class='read',
        versions=('v1beta',),
        version_paths={'v1beta': 'v1beta/{+name}'},
        path_params=('name',),
        query_params=(),
        risk_flags=('permission',),
    ),
    OperationSpec(
        family='corpora-permissions',
        method_name='list',
        method_original='list',
        operation_id='generativelanguage.corpora.permissions.list',
        http_method='GET',
        path='v1beta/{+parent}/permissions',
        request_ref=None,
        response_ref='ListPermissionsResponse',
        description='Lists permissions for the specific resource.',
        supports_media_upload=False,
        supports_media_download=False,
        safety_class='read',
        versions=('v1beta',),
        version_paths={'v1beta': 'v1beta/{+parent}/permissions'},
        path_params=('parent',),
        query_params=('pageToken', 'pageSize'),
        risk_flags=('permission',),
    ),
    OperationSpec(
        family='corpora-permissions',
        method_name='patch',
        method_original='patch',
        operation_id='generativelanguage.corpora.permissions.patch',
        http_method='PATCH',
        path='v1beta/{+name}',
        request_ref='Permission',
        response_ref='Permission',
        description='Updates the permission.',
        supports_media_upload=False,
        supports_media_download=False,
        safety_class='state_changing',
        versions=('v1beta',),
        version_paths={'v1beta': 'v1beta/{+name}'},
        path_params=('name',),
        query_params=('updateMask',),
        risk_flags=('no_snapshot', 'permission'),
    ),
    OperationSpec(
        family='dynamic',
        method_name='generate-content',
        method_original='generateContent',
        operation_id='generativelanguage.dynamic.generateContent',
        http_method='POST',
        path='v1beta/{+model}:generateContent',
        request_ref='GenerateContentRequest',
        response_ref='GenerateContentResponse',
        description='Generates a model response given an input `GenerateContentRequest`. Refer to the [text generation guide](https://ai.google.dev/gemini-api/docs/text-generation) for detailed usage information. Input capabilities differ between models, including tuned models. Refer to the [model guide](https://ai.google.dev/gemini-api/docs/models/gemini) and [tuning guide](https://ai.google.dev/gemini-api/docs/model-tuning) for details.',
        supports_media_upload=False,
        supports_media_download=False,
        safety_class='compute_read',
        versions=('v1beta', 'v1'),
        version_paths={'v1beta': 'v1beta/{+model}:generateContent', 'v1': 'v1/{+model}:generateContent'},
        path_params=('model',),
        query_params=(),
        risk_flags=(),
    ),
    OperationSpec(
        family='dynamic',
        method_name='stream-generate-content',
        method_original='streamGenerateContent',
        operation_id='generativelanguage.dynamic.streamGenerateContent',
        http_method='POST',
        path='v1beta/{+model}:streamGenerateContent',
        request_ref='GenerateContentRequest',
        response_ref='GenerateContentResponse',
        description='Generates a [streamed response](https://ai.google.dev/gemini-api/docs/text-generation?lang=python#generate-a-text-stream) from the model given an input `GenerateContentRequest`.',
        supports_media_upload=False,
        supports_media_download=False,
        safety_class='compute_read',
        versions=('v1beta', 'v1'),
        version_paths={'v1beta': 'v1beta/{+model}:streamGenerateContent', 'v1': 'v1/{+model}:streamGenerateContent'},
        path_params=('model',),
        query_params=(),
        risk_flags=(),
    ),
    OperationSpec(
        family='file-search-stores',
        method_name='create',
        method_original='create',
        operation_id='generativelanguage.fileSearchStores.create',
        http_method='POST',
        path='v1beta/fileSearchStores',
        request_ref='FileSearchStore',
        response_ref='FileSearchStore',
        description='Creates an empty `FileSearchStore`.',
        supports_media_upload=False,
        supports_media_download=False,
        safety_class='state_changing',
        versions=('v1beta',),
        version_paths={'v1beta': 'v1beta/fileSearchStores'},
        path_params=(),
        query_params=(),
        risk_flags=('no_snapshot',),
    ),
    OperationSpec(
        family='file-search-stores',
        method_name='delete',
        method_original='delete',
        operation_id='generativelanguage.fileSearchStores.delete',
        http_method='DELETE',
        path='v1beta/{+name}',
        request_ref=None,
        response_ref='Empty',
        description='Deletes a `FileSearchStore`.',
        supports_media_upload=False,
        supports_media_download=False,
        safety_class='state_changing',
        versions=('v1beta',),
        version_paths={'v1beta': 'v1beta/{+name}'},
        path_params=('name',),
        query_params=('force',),
        risk_flags=('destructive', 'irreversible', 'no_snapshot'),
    ),
    OperationSpec(
        family='file-search-stores',
        method_name='get',
        method_original='get',
        operation_id='generativelanguage.fileSearchStores.get',
        http_method='GET',
        path='v1beta/{+name}',
        request_ref=None,
        response_ref='FileSearchStore',
        description='Gets information about a specific `FileSearchStore`.',
        supports_media_upload=False,
        supports_media_download=False,
        safety_class='read',
        versions=('v1beta',),
        version_paths={'v1beta': 'v1beta/{+name}'},
        path_params=('name',),
        query_params=(),
        risk_flags=(),
    ),
    OperationSpec(
        family='file-search-stores',
        method_name='import-file',
        method_original='importFile',
        operation_id='generativelanguage.fileSearchStores.importFile',
        http_method='POST',
        path='v1beta/{+fileSearchStoreName}:importFile',
        request_ref='ImportFileRequest',
        response_ref='Operation',
        description='Imports a `File` from File Service to a `FileSearchStore`.',
        supports_media_upload=False,
        supports_media_download=False,
        safety_class='state_changing',
        versions=('v1beta',),
        version_paths={'v1beta': 'v1beta/{+fileSearchStoreName}:importFile'},
        path_params=('fileSearchStoreName',),
        query_params=(),
        risk_flags=('no_snapshot',),
    ),
    OperationSpec(
        family='file-search-stores',
        method_name='list',
        method_original='list',
        operation_id='generativelanguage.fileSearchStores.list',
        http_method='GET',
        path='v1beta/fileSearchStores',
        request_ref=None,
        response_ref='ListFileSearchStoresResponse',
        description='Lists all `FileSearchStores` owned by the user.',
        supports_media_upload=False,
        supports_media_download=False,
        safety_class='read',
        versions=('v1beta',),
        version_paths={'v1beta': 'v1beta/fileSearchStores'},
        path_params=(),
        query_params=('pageSize', 'pageToken'),
        risk_flags=(),
    ),
    OperationSpec(
        family='file-search-stores-documents',
        method_name='delete',
        method_original='delete',
        operation_id='generativelanguage.fileSearchStores.documents.delete',
        http_method='DELETE',
        path='v1beta/{+name}',
        request_ref=None,
        response_ref='Empty',
        description='Deletes a `Document`.',
        supports_media_upload=False,
        supports_media_download=False,
        safety_class='state_changing',
        versions=('v1beta',),
        version_paths={'v1beta': 'v1beta/{+name}'},
        path_params=('name',),
        query_params=('force',),
        risk_flags=('destructive', 'irreversible', 'no_snapshot'),
    ),
    OperationSpec(
        family='file-search-stores-documents',
        method_name='get',
        method_original='get',
        operation_id='generativelanguage.fileSearchStores.documents.get',
        http_method='GET',
        path='v1beta/{+name}',
        request_ref=None,
        response_ref='Document',
        description='Gets information about a specific `Document`.',
        supports_media_upload=False,
        supports_media_download=False,
        safety_class='read',
        versions=('v1beta',),
        version_paths={'v1beta': 'v1beta/{+name}'},
        path_params=('name',),
        query_params=(),
        risk_flags=(),
    ),
    OperationSpec(
        family='file-search-stores-documents',
        method_name='list',
        method_original='list',
        operation_id='generativelanguage.fileSearchStores.documents.list',
        http_method='GET',
        path='v1beta/{+parent}/documents',
        request_ref=None,
        response_ref='ListDocumentsResponse',
        description='Lists all `Document`s in a `Corpus`.',
        supports_media_upload=False,
        supports_media_download=False,
        safety_class='read',
        versions=('v1beta',),
        version_paths={'v1beta': 'v1beta/{+parent}/documents'},
        path_params=('parent',),
        query_params=('pageSize', 'pageToken'),
        risk_flags=(),
    ),
    OperationSpec(
        family='file-search-stores-operations',
        method_name='get',
        method_original='get',
        operation_id='generativelanguage.fileSearchStores.operations.get',
        http_method='GET',
        path='v1beta/{+name}',
        request_ref=None,
        response_ref='Operation',
        description='Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service.',
        supports_media_upload=False,
        supports_media_download=False,
        safety_class='read',
        versions=('v1beta', 'v1'),
        version_paths={'v1beta': 'v1beta/{+name}', 'v1': 'v1/{+name}'},
        path_params=('name',),
        query_params=(),
        risk_flags=(),
    ),
    OperationSpec(
        family='file-search-stores-upload-operations',
        method_name='get',
        method_original='get',
        operation_id='generativelanguage.fileSearchStores.upload.operations.get',
        http_method='GET',
        path='v1beta/{+name}',
        request_ref=None,
        response_ref='Operation',
        description='Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service.',
        supports_media_upload=False,
        supports_media_download=False,
        safety_class='read',
        versions=('v1beta', 'v1'),
        version_paths={'v1beta': 'v1beta/{+name}', 'v1': 'v1/{+name}'},
        path_params=('name',),
        query_params=(),
        risk_flags=(),
    ),
    OperationSpec(
        family='files',
        method_name='delete',
        method_original='delete',
        operation_id='generativelanguage.files.delete',
        http_method='DELETE',
        path='v1beta/{+name}',
        request_ref=None,
        response_ref='Empty',
        description='Deletes the `File`.',
        supports_media_upload=False,
        supports_media_download=False,
        safety_class='state_changing',
        versions=('v1beta',),
        version_paths={'v1beta': 'v1beta/{+name}'},
        path_params=('name',),
        query_params=(),
        risk_flags=('destructive', 'irreversible', 'no_snapshot'),
    ),
    OperationSpec(
        family='files',
        method_name='get',
        method_original='get',
        operation_id='generativelanguage.files.get',
        http_method='GET',
        path='v1beta/{+name}',
        request_ref=None,
        response_ref='File',
        description='Gets the metadata for the given `File`.',
        supports_media_upload=False,
        supports_media_download=False,
        safety_class='read',
        versions=('v1beta',),
        version_paths={'v1beta': 'v1beta/{+name}'},
        path_params=('name',),
        query_params=(),
        risk_flags=(),
    ),
    OperationSpec(
        family='files',
        method_name='list',
        method_original='list',
        operation_id='generativelanguage.files.list',
        http_method='GET',
        path='v1beta/files',
        request_ref=None,
        response_ref='ListFilesResponse',
        description='Lists the metadata for `File`s owned by the requesting project.',
        supports_media_upload=False,
        supports_media_download=False,
        safety_class='read',
        versions=('v1beta',),
        version_paths={'v1beta': 'v1beta/files'},
        path_params=(),
        query_params=('pageSize', 'pageToken'),
        risk_flags=(),
    ),
    OperationSpec(
        family='files',
        method_name='register',
        method_original='register',
        operation_id='generativelanguage.files.register',
        http_method='POST',
        path='v1beta/files:register',
        request_ref='RegisterFilesRequest',
        response_ref='RegisterFilesResponse',
        description='Registers a Google Cloud Storage files with FileService. The user is expected to provide Google Cloud Storage URIs and will receive a File resource for each URI in return. Note that the files are not copied, just registered with File API. If one file fails to register, the whole request fails.',
        supports_media_upload=False,
        supports_media_download=False,
        safety_class='state_changing',
        versions=('v1beta',),
        version_paths={'v1beta': 'v1beta/files:register'},
        path_params=(),
        query_params=(),
        risk_flags=('no_snapshot',),
    ),
    OperationSpec(
        family='generated-files',
        method_name='list',
        method_original='list',
        operation_id='generativelanguage.generatedFiles.list',
        http_method='GET',
        path='v1beta/generatedFiles',
        request_ref=None,
        response_ref='ListGeneratedFilesResponse',
        description='Lists the generated files owned by the requesting project.',
        supports_media_upload=False,
        supports_media_download=False,
        safety_class='read',
        versions=('v1beta',),
        version_paths={'v1beta': 'v1beta/generatedFiles'},
        path_params=(),
        query_params=('pageToken', 'pageSize'),
        risk_flags=(),
    ),
    OperationSpec(
        family='generated-files-operations',
        method_name='get',
        method_original='get',
        operation_id='generativelanguage.generatedFiles.operations.get',
        http_method='GET',
        path='v1beta/{+name}',
        request_ref=None,
        response_ref='Operation',
        description='Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service.',
        supports_media_upload=False,
        supports_media_download=False,
        safety_class='read',
        versions=('v1beta', 'v1'),
        version_paths={'v1beta': 'v1beta/{+name}', 'v1': 'v1/{+name}'},
        path_params=('name',),
        query_params=(),
        risk_flags=(),
    ),
    OperationSpec(
        family='media',
        method_name='upload',
        method_original='upload',
        operation_id='generativelanguage.media.upload',
        http_method='POST',
        path='v1beta/files',
        request_ref='CreateFileRequest',
        response_ref='CreateFileResponse',
        description='Creates a `File`.',
        supports_media_upload=True,
        supports_media_download=False,
        safety_class='state_changing',
        versions=('v1beta',),
        version_paths={'v1beta': 'v1beta/files'},
        path_params=(),
        query_params=(),
        risk_flags=('no_snapshot',),
    ),
    OperationSpec(
        family='media',
        method_name='upload-to-file-search-store',
        method_original='uploadToFileSearchStore',
        operation_id='generativelanguage.media.uploadToFileSearchStore',
        http_method='POST',
        path='v1beta/{+fileSearchStoreName}:uploadToFileSearchStore',
        request_ref='UploadToFileSearchStoreRequest',
        response_ref='CustomLongRunningOperation',
        description='Uploads data to a FileSearchStore, preprocesses and chunks before storing it in a FileSearchStore Document.',
        supports_media_upload=True,
        supports_media_download=False,
        safety_class='state_changing',
        versions=('v1beta',),
        version_paths={'v1beta': 'v1beta/{+fileSearchStoreName}:uploadToFileSearchStore'},
        path_params=('fileSearchStoreName',),
        query_params=(),
        risk_flags=('no_snapshot',),
    ),
    OperationSpec(
        family='models',
        method_name='async-batch-embed-content',
        method_original='asyncBatchEmbedContent',
        operation_id='generativelanguage.models.asyncBatchEmbedContent',
        http_method='POST',
        path='v1beta/{+model}:asyncBatchEmbedContent',
        request_ref='AsyncBatchEmbedContentRequest',
        response_ref='Operation',
        description='Enqueues a batch of `EmbedContent` requests for batch processing. We have a `BatchEmbedContents` handler in `GenerativeService`, but it was synchronized. So we name this one to be `Async` to avoid confusion.',
        supports_media_upload=False,
        supports_media_download=False,
        safety_class='compute_read',
        versions=('v1beta', 'v1'),
        version_paths={'v1beta': 'v1beta/{+model}:asyncBatchEmbedContent', 'v1': 'v1/{+model}:asyncBatchEmbedContent'},
        path_params=('model',),
        query_params=(),
        risk_flags=('bulk',),
    ),
    OperationSpec(
        family='models',
        method_name='batch-embed-contents',
        method_original='batchEmbedContents',
        operation_id='generativelanguage.models.batchEmbedContents',
        http_method='POST',
        path='v1beta/{+model}:batchEmbedContents',
        request_ref='BatchEmbedContentsRequest',
        response_ref='BatchEmbedContentsResponse',
        description='Generates multiple embedding vectors from the input `Content` which consists of a batch of strings represented as `EmbedContentRequest` objects.',
        supports_media_upload=False,
        supports_media_download=False,
        safety_class='compute_read',
        versions=('v1beta', 'v1'),
        version_paths={'v1beta': 'v1beta/{+model}:batchEmbedContents', 'v1': 'v1/{+model}:batchEmbedContents'},
        path_params=('model',),
        query_params=(),
        risk_flags=('bulk',),
    ),
    OperationSpec(
        family='models',
        method_name='batch-embed-text',
        method_original='batchEmbedText',
        operation_id='generativelanguage.models.batchEmbedText',
        http_method='POST',
        path='v1beta/{+model}:batchEmbedText',
        request_ref='BatchEmbedTextRequest',
        response_ref='BatchEmbedTextResponse',
        description='Generates multiple embeddings from the model given input text in a synchronous call.',
        supports_media_upload=False,
        supports_media_download=False,
        safety_class='compute_read',
        versions=('v1beta',),
        version_paths={'v1beta': 'v1beta/{+model}:batchEmbedText'},
        path_params=('model',),
        query_params=(),
        risk_flags=('bulk',),
    ),
    OperationSpec(
        family='models',
        method_name='batch-generate-content',
        method_original='batchGenerateContent',
        operation_id='generativelanguage.models.batchGenerateContent',
        http_method='POST',
        path='v1beta/{+model}:batchGenerateContent',
        request_ref='BatchGenerateContentRequest',
        response_ref='Operation',
        description='Enqueues a batch of `GenerateContent` requests for batch processing.',
        supports_media_upload=False,
        supports_media_download=False,
        safety_class='compute_read',
        versions=('v1beta', 'v1'),
        version_paths={'v1beta': 'v1beta/{+model}:batchGenerateContent', 'v1': 'v1/{+model}:batchGenerateContent'},
        path_params=('model',),
        query_params=(),
        risk_flags=('bulk',),
    ),
    OperationSpec(
        family='models',
        method_name='count-message-tokens',
        method_original='countMessageTokens',
        operation_id='generativelanguage.models.countMessageTokens',
        http_method='POST',
        path='v1beta/{+model}:countMessageTokens',
        request_ref='CountMessageTokensRequest',
        response_ref='CountMessageTokensResponse',
        description="Runs a model's tokenizer on a string and returns the token count.",
        supports_media_upload=False,
        supports_media_download=False,
        safety_class='compute_read',
        versions=('v1beta',),
        version_paths={'v1beta': 'v1beta/{+model}:countMessageTokens'},
        path_params=('model',),
        query_params=(),
        risk_flags=(),
    ),
    OperationSpec(
        family='models',
        method_name='count-text-tokens',
        method_original='countTextTokens',
        operation_id='generativelanguage.models.countTextTokens',
        http_method='POST',
        path='v1beta/{+model}:countTextTokens',
        request_ref='CountTextTokensRequest',
        response_ref='CountTextTokensResponse',
        description="Runs a model's tokenizer on a text and returns the token count.",
        supports_media_upload=False,
        supports_media_download=False,
        safety_class='compute_read',
        versions=('v1beta',),
        version_paths={'v1beta': 'v1beta/{+model}:countTextTokens'},
        path_params=('model',),
        query_params=(),
        risk_flags=(),
    ),
    OperationSpec(
        family='models',
        method_name='count-tokens',
        method_original='countTokens',
        operation_id='generativelanguage.models.countTokens',
        http_method='POST',
        path='v1beta/{+model}:countTokens',
        request_ref='CountTokensRequest',
        response_ref='CountTokensResponse',
        description="Runs a model's tokenizer on input `Content` and returns the token count. Refer to the [tokens guide](https://ai.google.dev/gemini-api/docs/tokens) to learn more about tokens.",
        supports_media_upload=False,
        supports_media_download=False,
        safety_class='compute_read',
        versions=('v1beta', 'v1'),
        version_paths={'v1beta': 'v1beta/{+model}:countTokens', 'v1': 'v1/{+model}:countTokens'},
        path_params=('model',),
        query_params=(),
        risk_flags=(),
    ),
    OperationSpec(
        family='models',
        method_name='embed-content',
        method_original='embedContent',
        operation_id='generativelanguage.models.embedContent',
        http_method='POST',
        path='v1beta/{+model}:embedContent',
        request_ref='EmbedContentRequest',
        response_ref='EmbedContentResponse',
        description='Generates a text embedding vector from the input `Content` using the specified [Gemini Embedding model](https://ai.google.dev/gemini-api/docs/models/gemini#text-embedding).',
        supports_media_upload=False,
        supports_media_download=False,
        safety_class='compute_read',
        versions=('v1beta', 'v1'),
        version_paths={'v1beta': 'v1beta/{+model}:embedContent', 'v1': 'v1/{+model}:embedContent'},
        path_params=('model',),
        query_params=(),
        risk_flags=(),
    ),
    OperationSpec(
        family='models',
        method_name='embed-text',
        method_original='embedText',
        operation_id='generativelanguage.models.embedText',
        http_method='POST',
        path='v1beta/{+model}:embedText',
        request_ref='EmbedTextRequest',
        response_ref='EmbedTextResponse',
        description='Generates an embedding from the model given an input message.',
        supports_media_upload=False,
        supports_media_download=False,
        safety_class='compute_read',
        versions=('v1beta',),
        version_paths={'v1beta': 'v1beta/{+model}:embedText'},
        path_params=('model',),
        query_params=(),
        risk_flags=(),
    ),
    OperationSpec(
        family='models',
        method_name='generate-answer',
        method_original='generateAnswer',
        operation_id='generativelanguage.models.generateAnswer',
        http_method='POST',
        path='v1beta/{+model}:generateAnswer',
        request_ref='GenerateAnswerRequest',
        response_ref='GenerateAnswerResponse',
        description='Generates a grounded answer from the model given an input `GenerateAnswerRequest`.',
        supports_media_upload=False,
        supports_media_download=False,
        safety_class='compute_read',
        versions=('v1beta',),
        version_paths={'v1beta': 'v1beta/{+model}:generateAnswer'},
        path_params=('model',),
        query_params=(),
        risk_flags=(),
    ),
    OperationSpec(
        family='models',
        method_name='generate-content',
        method_original='generateContent',
        operation_id='generativelanguage.models.generateContent',
        http_method='POST',
        path='v1beta/{+model}:generateContent',
        request_ref='GenerateContentRequest',
        response_ref='GenerateContentResponse',
        description='Generates a model response given an input `GenerateContentRequest`. Refer to the [text generation guide](https://ai.google.dev/gemini-api/docs/text-generation) for detailed usage information. Input capabilities differ between models, including tuned models. Refer to the [model guide](https://ai.google.dev/gemini-api/docs/models/gemini) and [tuning guide](https://ai.google.dev/gemini-api/docs/model-tuning) for details.',
        supports_media_upload=False,
        supports_media_download=False,
        safety_class='compute_read',
        versions=('v1beta', 'v1'),
        version_paths={'v1beta': 'v1beta/{+model}:generateContent', 'v1': 'v1/{+model}:generateContent'},
        path_params=('model',),
        query_params=(),
        risk_flags=(),
    ),
    OperationSpec(
        family='models',
        method_name='generate-message',
        method_original='generateMessage',
        operation_id='generativelanguage.models.generateMessage',
        http_method='POST',
        path='v1beta/{+model}:generateMessage',
        request_ref='GenerateMessageRequest',
        response_ref='GenerateMessageResponse',
        description='Generates a response from the model given an input `MessagePrompt`.',
        supports_media_upload=False,
        supports_media_download=False,
        safety_class='compute_read',
        versions=('v1beta',),
        version_paths={'v1beta': 'v1beta/{+model}:generateMessage'},
        path_params=('model',),
        query_params=(),
        risk_flags=(),
    ),
    OperationSpec(
        family='models',
        method_name='generate-text',
        method_original='generateText',
        operation_id='generativelanguage.models.generateText',
        http_method='POST',
        path='v1beta/{+model}:generateText',
        request_ref='GenerateTextRequest',
        response_ref='GenerateTextResponse',
        description='Generates a response from the model given an input message.',
        supports_media_upload=False,
        supports_media_download=False,
        safety_class='compute_read',
        versions=('v1beta',),
        version_paths={'v1beta': 'v1beta/{+model}:generateText'},
        path_params=('model',),
        query_params=(),
        risk_flags=(),
    ),
    OperationSpec(
        family='models',
        method_name='get',
        method_original='get',
        operation_id='generativelanguage.models.get',
        http_method='GET',
        path='v1beta/{+name}',
        request_ref=None,
        response_ref='Model',
        description='Gets information about a specific `Model` such as its version number, token limits, [parameters](https://ai.google.dev/gemini-api/docs/models/generative-models#model-parameters) and other metadata. Refer to the [Gemini models guide](https://ai.google.dev/gemini-api/docs/models/gemini) for detailed model information.',
        supports_media_upload=False,
        supports_media_download=False,
        safety_class='read',
        versions=('v1beta', 'v1'),
        version_paths={'v1beta': 'v1beta/{+name}', 'v1': 'v1/{+name}'},
        path_params=('name',),
        query_params=(),
        risk_flags=(),
    ),
    OperationSpec(
        family='models',
        method_name='list',
        method_original='list',
        operation_id='generativelanguage.models.list',
        http_method='GET',
        path='v1beta/models',
        request_ref=None,
        response_ref='ListModelsResponse',
        description='Lists the [`Model`s](https://ai.google.dev/gemini-api/docs/models/gemini) available through the Gemini API.',
        supports_media_upload=False,
        supports_media_download=False,
        safety_class='read',
        versions=('v1beta', 'v1'),
        version_paths={'v1beta': 'v1beta/models', 'v1': 'v1/models'},
        path_params=(),
        query_params=('pageSize', 'pageToken'),
        risk_flags=(),
    ),
    OperationSpec(
        family='models',
        method_name='predict',
        method_original='predict',
        operation_id='generativelanguage.models.predict',
        http_method='POST',
        path='v1beta/{+model}:predict',
        request_ref='PredictRequest',
        response_ref='PredictResponse',
        description='Performs a prediction request.',
        supports_media_upload=False,
        supports_media_download=False,
        safety_class='compute_read',
        versions=('v1beta',),
        version_paths={'v1beta': 'v1beta/{+model}:predict'},
        path_params=('model',),
        query_params=(),
        risk_flags=(),
    ),
    OperationSpec(
        family='models',
        method_name='predict-long-running',
        method_original='predictLongRunning',
        operation_id='generativelanguage.models.predictLongRunning',
        http_method='POST',
        path='v1beta/{+model}:predictLongRunning',
        request_ref='PredictLongRunningRequest',
        response_ref='Operation',
        description='Same as Predict but returns an LRO.',
        supports_media_upload=False,
        supports_media_download=False,
        safety_class='compute_read',
        versions=('v1beta',),
        version_paths={'v1beta': 'v1beta/{+model}:predictLongRunning'},
        path_params=('model',),
        query_params=(),
        risk_flags=(),
    ),
    OperationSpec(
        family='models',
        method_name='stream-generate-content',
        method_original='streamGenerateContent',
        operation_id='generativelanguage.models.streamGenerateContent',
        http_method='POST',
        path='v1beta/{+model}:streamGenerateContent',
        request_ref='GenerateContentRequest',
        response_ref='GenerateContentResponse',
        description='Generates a [streamed response](https://ai.google.dev/gemini-api/docs/text-generation?lang=python#generate-a-text-stream) from the model given an input `GenerateContentRequest`.',
        supports_media_upload=False,
        supports_media_download=False,
        safety_class='compute_read',
        versions=('v1beta', 'v1'),
        version_paths={'v1beta': 'v1beta/{+model}:streamGenerateContent', 'v1': 'v1/{+model}:streamGenerateContent'},
        path_params=('model',),
        query_params=(),
        risk_flags=(),
    ),
    OperationSpec(
        family='models-operations',
        method_name='get',
        method_original='get',
        operation_id='generativelanguage.models.operations.get',
        http_method='GET',
        path='v1beta/{+name}',
        request_ref=None,
        response_ref='Operation',
        description='Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service.',
        supports_media_upload=False,
        supports_media_download=False,
        safety_class='read',
        versions=('v1beta', 'v1'),
        version_paths={'v1beta': 'v1beta/{+name}', 'v1': 'v1/{+name}'},
        path_params=('name',),
        query_params=(),
        risk_flags=(),
    ),
    OperationSpec(
        family='models-operations',
        method_name='list',
        method_original='list',
        operation_id='generativelanguage.models.operations.list',
        http_method='GET',
        path='v1beta/{+name}/operations',
        request_ref=None,
        response_ref='ListOperationsResponse',
        description="Lists operations that match the specified filter in the request. If the server doesn't support this method, it returns `UNIMPLEMENTED`.",
        supports_media_upload=False,
        supports_media_download=False,
        safety_class='read',
        versions=('v1beta', 'v1'),
        version_paths={'v1beta': 'v1beta/{+name}/operations', 'v1': 'v1/{+name}/operations'},
        path_params=('name',),
        query_params=('filter', 'pageSize', 'pageToken', 'returnPartialSuccess'),
        risk_flags=(),
    ),
    OperationSpec(
        family='operations',
        method_name='delete',
        method_original='delete',
        operation_id='generativelanguage.operations.delete',
        http_method='DELETE',
        path='v1/{+name}',
        request_ref=None,
        response_ref='Empty',
        description="Deletes a long-running operation. This method indicates that the client is no longer interested in the operation result. It does not cancel the operation. If the server doesn't support this method, it returns `google.rpc.Code.UNIMPLEMENTED`.",
        supports_media_upload=False,
        supports_media_download=False,
        safety_class='state_changing',
        versions=('v1',),
        version_paths={'v1': 'v1/{+name}'},
        path_params=('name',),
        query_params=(),
        risk_flags=('destructive', 'irreversible', 'no_snapshot'),
    ),
    OperationSpec(
        family='operations',
        method_name='list',
        method_original='list',
        operation_id='generativelanguage.operations.list',
        http_method='GET',
        path='v1/{+name}',
        request_ref=None,
        response_ref='ListOperationsResponse',
        description="Lists operations that match the specified filter in the request. If the server doesn't support this method, it returns `UNIMPLEMENTED`.",
        supports_media_upload=False,
        supports_media_download=False,
        safety_class='read',
        versions=('v1',),
        version_paths={'v1': 'v1/{+name}'},
        path_params=('name',),
        query_params=('pageToken', 'pageSize', 'returnPartialSuccess', 'filter'),
        risk_flags=(),
    ),
    OperationSpec(
        family='tuned-models',
        method_name='async-batch-embed-content',
        method_original='asyncBatchEmbedContent',
        operation_id='generativelanguage.tunedModels.asyncBatchEmbedContent',
        http_method='POST',
        path='v1beta/{+model}:asyncBatchEmbedContent',
        request_ref='AsyncBatchEmbedContentRequest',
        response_ref='Operation',
        description='Enqueues a batch of `EmbedContent` requests for batch processing. We have a `BatchEmbedContents` handler in `GenerativeService`, but it was synchronized. So we name this one to be `Async` to avoid confusion.',
        supports_media_upload=False,
        supports_media_download=False,
        safety_class='compute_read',
        versions=('v1beta', 'v1'),
        version_paths={'v1beta': 'v1beta/{+model}:asyncBatchEmbedContent', 'v1': 'v1/{+model}:asyncBatchEmbedContent'},
        path_params=('model',),
        query_params=(),
        risk_flags=('bulk',),
    ),
    OperationSpec(
        family='tuned-models',
        method_name='batch-generate-content',
        method_original='batchGenerateContent',
        operation_id='generativelanguage.tunedModels.batchGenerateContent',
        http_method='POST',
        path='v1beta/{+model}:batchGenerateContent',
        request_ref='BatchGenerateContentRequest',
        response_ref='Operation',
        description='Enqueues a batch of `GenerateContent` requests for batch processing.',
        supports_media_upload=False,
        supports_media_download=False,
        safety_class='compute_read',
        versions=('v1beta', 'v1'),
        version_paths={'v1beta': 'v1beta/{+model}:batchGenerateContent', 'v1': 'v1/{+model}:batchGenerateContent'},
        path_params=('model',),
        query_params=(),
        risk_flags=('bulk',),
    ),
    OperationSpec(
        family='tuned-models',
        method_name='create',
        method_original='create',
        operation_id='generativelanguage.tunedModels.create',
        http_method='POST',
        path='v1beta/tunedModels',
        request_ref='TunedModel',
        response_ref='Operation',
        description='Creates a tuned model. Check intermediate tuning progress (if any) through the [google.longrunning.Operations] service. Access status and results through the Operations service. Example: GET /v1/tunedModels/az2mb0bpw6i/operations/000-111-222',
        supports_media_upload=False,
        supports_media_download=False,
        safety_class='state_changing',
        versions=('v1beta',),
        version_paths={'v1beta': 'v1beta/tunedModels'},
        path_params=(),
        query_params=('tunedModelId',),
        risk_flags=('no_snapshot',),
    ),
    OperationSpec(
        family='tuned-models',
        method_name='delete',
        method_original='delete',
        operation_id='generativelanguage.tunedModels.delete',
        http_method='DELETE',
        path='v1beta/{+name}',
        request_ref=None,
        response_ref='Empty',
        description='Deletes a tuned model.',
        supports_media_upload=False,
        supports_media_download=False,
        safety_class='state_changing',
        versions=('v1beta',),
        version_paths={'v1beta': 'v1beta/{+name}'},
        path_params=('name',),
        query_params=(),
        risk_flags=('destructive', 'irreversible', 'no_snapshot'),
    ),
    OperationSpec(
        family='tuned-models',
        method_name='generate-content',
        method_original='generateContent',
        operation_id='generativelanguage.tunedModels.generateContent',
        http_method='POST',
        path='v1beta/{+model}:generateContent',
        request_ref='GenerateContentRequest',
        response_ref='GenerateContentResponse',
        description='Generates a model response given an input `GenerateContentRequest`. Refer to the [text generation guide](https://ai.google.dev/gemini-api/docs/text-generation) for detailed usage information. Input capabilities differ between models, including tuned models. Refer to the [model guide](https://ai.google.dev/gemini-api/docs/models/gemini) and [tuning guide](https://ai.google.dev/gemini-api/docs/model-tuning) for details.',
        supports_media_upload=False,
        supports_media_download=False,
        safety_class='compute_read',
        versions=('v1beta', 'v1'),
        version_paths={'v1beta': 'v1beta/{+model}:generateContent', 'v1': 'v1/{+model}:generateContent'},
        path_params=('model',),
        query_params=(),
        risk_flags=(),
    ),
    OperationSpec(
        family='tuned-models',
        method_name='generate-text',
        method_original='generateText',
        operation_id='generativelanguage.tunedModels.generateText',
        http_method='POST',
        path='v1beta/{+model}:generateText',
        request_ref='GenerateTextRequest',
        response_ref='GenerateTextResponse',
        description='Generates a response from the model given an input message.',
        supports_media_upload=False,
        supports_media_download=False,
        safety_class='compute_read',
        versions=('v1beta',),
        version_paths={'v1beta': 'v1beta/{+model}:generateText'},
        path_params=('model',),
        query_params=(),
        risk_flags=(),
    ),
    OperationSpec(
        family='tuned-models',
        method_name='get',
        method_original='get',
        operation_id='generativelanguage.tunedModels.get',
        http_method='GET',
        path='v1beta/{+name}',
        request_ref=None,
        response_ref='TunedModel',
        description='Gets information about a specific TunedModel.',
        supports_media_upload=False,
        supports_media_download=False,
        safety_class='read',
        versions=('v1beta',),
        version_paths={'v1beta': 'v1beta/{+name}'},
        path_params=('name',),
        query_params=(),
        risk_flags=(),
    ),
    OperationSpec(
        family='tuned-models',
        method_name='list',
        method_original='list',
        operation_id='generativelanguage.tunedModels.list',
        http_method='GET',
        path='v1beta/tunedModels',
        request_ref=None,
        response_ref='ListTunedModelsResponse',
        description='Lists created tuned models.',
        supports_media_upload=False,
        supports_media_download=False,
        safety_class='read',
        versions=('v1beta',),
        version_paths={'v1beta': 'v1beta/tunedModels'},
        path_params=(),
        query_params=('pageSize', 'pageToken', 'filter'),
        risk_flags=(),
    ),
    OperationSpec(
        family='tuned-models',
        method_name='patch',
        method_original='patch',
        operation_id='generativelanguage.tunedModels.patch',
        http_method='PATCH',
        path='v1beta/{+name}',
        request_ref='TunedModel',
        response_ref='TunedModel',
        description='Updates a tuned model.',
        supports_media_upload=False,
        supports_media_download=False,
        safety_class='state_changing',
        versions=('v1beta',),
        version_paths={'v1beta': 'v1beta/{+name}'},
        path_params=('name',),
        query_params=('updateMask',),
        risk_flags=('no_snapshot',),
    ),
    OperationSpec(
        family='tuned-models',
        method_name='stream-generate-content',
        method_original='streamGenerateContent',
        operation_id='generativelanguage.tunedModels.streamGenerateContent',
        http_method='POST',
        path='v1beta/{+model}:streamGenerateContent',
        request_ref='GenerateContentRequest',
        response_ref='GenerateContentResponse',
        description='Generates a [streamed response](https://ai.google.dev/gemini-api/docs/text-generation?lang=python#generate-a-text-stream) from the model given an input `GenerateContentRequest`.',
        supports_media_upload=False,
        supports_media_download=False,
        safety_class='compute_read',
        versions=('v1beta', 'v1'),
        version_paths={'v1beta': 'v1beta/{+model}:streamGenerateContent', 'v1': 'v1/{+model}:streamGenerateContent'},
        path_params=('model',),
        query_params=(),
        risk_flags=(),
    ),
    OperationSpec(
        family='tuned-models',
        method_name='transfer-ownership',
        method_original='transferOwnership',
        operation_id='generativelanguage.tunedModels.transferOwnership',
        http_method='POST',
        path='v1beta/{+name}:transferOwnership',
        request_ref='TransferOwnershipRequest',
        response_ref='TransferOwnershipResponse',
        description='Transfers ownership of the tuned model. This is the only way to change ownership of the tuned model. The current owner will be downgraded to writer role.',
        supports_media_upload=False,
        supports_media_download=False,
        safety_class='state_changing',
        versions=('v1beta',),
        version_paths={'v1beta': 'v1beta/{+name}:transferOwnership'},
        path_params=('name',),
        query_params=(),
        risk_flags=('irreversible', 'no_snapshot', 'permission'),
    ),
    OperationSpec(
        family='tuned-models-operations',
        method_name='cancel',
        method_original='cancel',
        operation_id='generativelanguage.tunedModels.operations.cancel',
        http_method='POST',
        path='v1/{+name}:cancel',
        request_ref='CancelOperationRequest',
        response_ref='Empty',
        description="Starts asynchronous cancellation on a long-running operation. The server makes a best effort to cancel the operation, but success is not guaranteed. If the server doesn't support this method, it returns `google.rpc.Code.UNIMPLEMENTED`. Clients can use Operations.GetOperation or other methods to check whether the cancellation succeeded or whether the operation completed despite cancellation. On successful cancellation, the operation is not deleted; instead, it becomes an operation with an Operation.error value with a google.rpc.Status.code of `1`, corresponding to `Code.CANCELLED`.",
        supports_media_upload=False,
        supports_media_download=False,
        safety_class='state_changing',
        versions=('v1',),
        version_paths={'v1': 'v1/{+name}:cancel'},
        path_params=('name',),
        query_params=(),
        risk_flags=('irreversible', 'no_snapshot'),
    ),
    OperationSpec(
        family='tuned-models-operations',
        method_name='get',
        method_original='get',
        operation_id='generativelanguage.tunedModels.operations.get',
        http_method='GET',
        path='v1beta/{+name}',
        request_ref=None,
        response_ref='Operation',
        description='Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service.',
        supports_media_upload=False,
        supports_media_download=False,
        safety_class='read',
        versions=('v1beta', 'v1'),
        version_paths={'v1beta': 'v1beta/{+name}', 'v1': 'v1/{+name}'},
        path_params=('name',),
        query_params=(),
        risk_flags=(),
    ),
    OperationSpec(
        family='tuned-models-operations',
        method_name='list',
        method_original='list',
        operation_id='generativelanguage.tunedModels.operations.list',
        http_method='GET',
        path='v1beta/{+name}/operations',
        request_ref=None,
        response_ref='ListOperationsResponse',
        description="Lists operations that match the specified filter in the request. If the server doesn't support this method, it returns `UNIMPLEMENTED`.",
        supports_media_upload=False,
        supports_media_download=False,
        safety_class='read',
        versions=('v1beta', 'v1'),
        version_paths={'v1beta': 'v1beta/{+name}/operations', 'v1': 'v1/{+name}/operations'},
        path_params=('name',),
        query_params=('filter', 'pageToken', 'pageSize', 'returnPartialSuccess'),
        risk_flags=(),
    ),
    OperationSpec(
        family='tuned-models-permissions',
        method_name='create',
        method_original='create',
        operation_id='generativelanguage.tunedModels.permissions.create',
        http_method='POST',
        path='v1beta/{+parent}/permissions',
        request_ref='Permission',
        response_ref='Permission',
        description='Create a permission to a specific resource.',
        supports_media_upload=False,
        supports_media_download=False,
        safety_class='state_changing',
        versions=('v1beta',),
        version_paths={'v1beta': 'v1beta/{+parent}/permissions'},
        path_params=('parent',),
        query_params=(),
        risk_flags=('no_snapshot', 'permission'),
    ),
    OperationSpec(
        family='tuned-models-permissions',
        method_name='delete',
        method_original='delete',
        operation_id='generativelanguage.tunedModels.permissions.delete',
        http_method='DELETE',
        path='v1beta/{+name}',
        request_ref=None,
        response_ref='Empty',
        description='Deletes the permission.',
        supports_media_upload=False,
        supports_media_download=False,
        safety_class='state_changing',
        versions=('v1beta',),
        version_paths={'v1beta': 'v1beta/{+name}'},
        path_params=('name',),
        query_params=(),
        risk_flags=('destructive', 'irreversible', 'no_snapshot', 'permission'),
    ),
    OperationSpec(
        family='tuned-models-permissions',
        method_name='get',
        method_original='get',
        operation_id='generativelanguage.tunedModels.permissions.get',
        http_method='GET',
        path='v1beta/{+name}',
        request_ref=None,
        response_ref='Permission',
        description='Gets information about a specific Permission.',
        supports_media_upload=False,
        supports_media_download=False,
        safety_class='read',
        versions=('v1beta',),
        version_paths={'v1beta': 'v1beta/{+name}'},
        path_params=('name',),
        query_params=(),
        risk_flags=('permission',),
    ),
    OperationSpec(
        family='tuned-models-permissions',
        method_name='list',
        method_original='list',
        operation_id='generativelanguage.tunedModels.permissions.list',
        http_method='GET',
        path='v1beta/{+parent}/permissions',
        request_ref=None,
        response_ref='ListPermissionsResponse',
        description='Lists permissions for the specific resource.',
        supports_media_upload=False,
        supports_media_download=False,
        safety_class='read',
        versions=('v1beta',),
        version_paths={'v1beta': 'v1beta/{+parent}/permissions'},
        path_params=('parent',),
        query_params=('pageToken', 'pageSize'),
        risk_flags=('permission',),
    ),
    OperationSpec(
        family='tuned-models-permissions',
        method_name='patch',
        method_original='patch',
        operation_id='generativelanguage.tunedModels.permissions.patch',
        http_method='PATCH',
        path='v1beta/{+name}',
        request_ref='Permission',
        response_ref='Permission',
        description='Updates the permission.',
        supports_media_upload=False,
        supports_media_download=False,
        safety_class='state_changing',
        versions=('v1beta',),
        version_paths={'v1beta': 'v1beta/{+name}'},
        path_params=('name',),
        query_params=('updateMask',),
        risk_flags=('no_snapshot', 'permission'),
    ),
)

OPERATION_BY_COMMAND = {op.command_key: op for op in OPERATIONS}
OPERATION_BY_ID = {op.operation_id: op for op in OPERATIONS}
