# Generated by scripts/generate_zone_settings_coverage.py; do not edit by hand.
from __future__ import annotations

ALLOWED_ZONE_SETTING_PATHS: frozenset[str] = frozenset(
    [
        'aegis',
        'fonts',
        'origin_h2_max_streams',
        'origin_max_http_version',
        'rum',
        'speed_brain',
        'ssl_automatic_mode',
    ]
)
